apiVersion: v1
kind: Secret
metadata:
    name: tka-tailscale
    namespace: tka-system
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:uwq+tn2t3RXlpZdvG1LmSA8XqtxLH9+YVSxP3VptmffWck2o13XLKuDKr20RdzMcJk8YzqCxTwC3VwpOaw==,iv:I8FpsCB6siphk0HYOlCPu5Mq4Jjpt+EzwuRHkO86wAA=,tag:7PaZGLPzXjK48mzYO2EG6g==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0d6UlQyU0NtSFp6ellX
            R3RIcjhHS053OXZZVWgxVmpESUlJZnorYzFFCkdMcm1ZVzYzaTM1VEZQVlh3UW1i
            Vmt6WEtYQ0NkYVZ6dUVKd09nMlFmYUUKLS0tIE41S29tMlp5M2VxZmE5U1JaOEF2
            bDhOVzQ3UFAyU0F3ZXpUZWZrZEVmWW8Kjt2g1J3CxsFeR9cDXb2QmECSkDUyh1S8
            iY8hSaO+RgqYZYcm1RRXqwp3lcKaRW4oE5Qo1/dmNuYsNKeBfmE3Gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUWRUVEd3dXZ4aCtpTTBB
            V0w3WVFHeEZ6ZXRFZDFuQTFNMkNWTjh6UWtjCmVVUjZjYWFwNnZLeU9RdkVjVUJR
            b1NsTE1iL2Fpb1BHem04QVNWakRIRmcKLS0tIHk0R2JQOVFTNEhKL3pmT1B2dkZx
            cFBoN3d0NHgyTG5WeG1QYlFuSU5xeWsKTJlHNXjTfxKLX/05Q8vZNjs+yso144hg
            wCpVh77GNatli+CUe2fG3CZ6tYgwOwBAuvnKZ2pMBlC6stYWM1U8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGgrZ1hjVUNLS0ZFOHJu
            Z2tzaDlQTm9Zcm5Sek1kdDJSN09RaEsveFFzClFzaVJ5YXBTY3U0REcrNDdhUGlh
            VS9Na0ZQRmVGcHVEdTlsblVhNmd2ck0KLS0tIEJQNXZxTFRBRnkwV3N6OFI2WXNo
            SDdDMkdBM2t5L1NxQnhTU3Y2QVl5QmcK8edLeobRHljTZBSMab1UiWEnoSzWAq9N
            V6PPGNV/ntDa8cxmSTYVwvZon86IjJaj7TkmfzdCj6QuDeqwNcdNOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:nuFab1gQ8AGAmldNDRpUvBY6FRh1afyRfzIsFv+ngy42Y326eGZRNw1NmCWSkA5nwapZ9Qc4wSUbfh65/PzrcJcfUrSICoPtLgHW+JLWkBKiSVNGCGJjlZGCtyX8zd3FH9YFvUQkGqkI+pMIU1nvClqweipzoMRDXi7K94ksocA=,iv:JKsMkFSx+T+23ufUBznmYki+c9PBRl/I9UVSqZZ4yCQ=,tag:4fMHONYPBzMBjoSnvTxbbg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
