apiVersion: v1
kind: Secret
metadata:
    name: tka-tailscale
    namespace: tka-system
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:8xw1v8cOxS6+JEirm8puS8mxBRHGZNktMsxP+wZqUuz3quXug/tj0AsFA5qq/SycyvaViDeIX0rQYcQwHQ==,iv:wCKTSyV6PRPBXewSoWnZ7BHpn97f8/O8KD1xJpYhdcE=,tag:CsTymxVFpzJZMIhBaQBnpA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RGNCUks4NzFMemhrclNC
            Q08wM0ZwTG1rY0dXMjJzNUVIa2dDVUUycmo4CjBjS3p6eW5wUE5pRUJ3Z0ZJZ2Fk
            WHYrdzByaXppYTZxaXRXaEc3YmVZMW8KLS0tIEdnbW10Qm5qOE9YaWZBSmVuRFlo
            WmJ4R3FzNDRPTjhIRFA4eDVJM05UbEEKQNH4TJ7WWx0JJcUkI+UUqghwbRmSdbCg
            5QvEnVMpY1FXEMzsxWphluX07hswocHyHyf2I46cWQmu4l1BV+LQ9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONGtxenJ5aXNGVjFqYUlW
            SUwwR1A3YS9tanU1TmZ6cDN6UFhiTjZwMlJ3CjRSNzUzTVlXQVFnNnV2REhUSFFQ
            eEhJdmRpeGJ3K0ZqRUVMVkdycUdVb1kKLS0tIEJtVWc3T25vWFlmZzJ4L1IzcVpX
            MHJKSlhVVmdoM0hvbnpqRDJrR1JZdzAKj33WMNmxklF/jOkgShpflteEWMcEbz7q
            jir1hoMu7AJVRM6aTOoyG7BkyfyAKgnRknF/7H6AOcr7K5jAeAaVcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ3ZCdkJBZnZnRUs3TFJm
            d1ZPY0VaektmcDhzdklPUnk5UWQxWk9UbW1RCjUveVRxMWtySlEraWF3S08vWXFz
            TFE3UUQ4a0FXUUFBS1BhSmJYaGFBVm8KLS0tIEFsVlg2MytaeEd0SFp0NTFhdWxP
            VlJOQkdjT3VJOHJ1c2VYYk9nRWd1M2MKdYQ/2uA3QHfy8+fwVxMTbwuBUWmuLuYo
            1qtMgFw1RcNeL5qvaL1bi3qrwGNtoe3SbhDRlkBZfbLim0we+ivHdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtajVNTXNjbXBpTXcvNkhK
            SytHU1c1KzNrcmZjL2FSUGFTUnRzeVpIM21VCm1FS3VnQXQrVWhReHBQMEY5d0Zx
            TlZmSjZhQkswQzhUZVV0RHFYTTgvUU0KLS0tIHByb0tFT0kvTXBvUEVhMGhHb2Vy
            UUFVNTN3dXZnTVVOd3hkQUVwMFdKZ00KsiDXBWZRiTo8MX9eZaiRU8i3akTwv0qV
            hKrFS8XQfIlLReFwAsH0ALEZygAH5gsYS2v6KGtQ7igTFt5dw0d6lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:SNlvLZDBuveMqCHG9lRE/tK+qMOTLFcK6+5JCGaFQgRFGjui1IH5/mtrQNzkAIbXG2rQcFI9egjRNf0VROeBn+loA8yUY+Nkj5L7nB/Ckg7JrXBEYXLV6xUP8L4F3jyd2BLfJJmQfgO+nXKsicdETVYw32xINyj8HHO6AhY7Vys=,iv:ca9vvzhuQ+sBzJYvcKXHxQR3VGAso61D1NSEsUhHK90=,tag:UFbzBHOx69mKLrOF45PJMA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
