{
 "title": "Certificate Checker",
 "description": "Dashboard for viewing the status of production certificates. To be used with the cert-checker project.https://github.com/mogensen/cert-checker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Broken Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid == 0)"
    }
   ]
  },
  {
   "title": "Certificates about to expire",
   "type": "stat",
   "description": "Certificates with a lifetime < 30 days",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count( ((cert_checker_expire_time{} - time()) / 86400 >= 0) < 30)"
    }
   ]
  },
  {
   "title": "Min TLS Version: SSLv3",
   "type": "stat",
   "description": "SSLv3 is cryptographically broken and should not be used.\nSSLv3 was deprecated in 1996",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid{tls_min_version=\"SSLv3\"})"
    }
   ]
  },
  {
   "title": "Min TLS Version: TLS 1.0",
   "type": "stat",
   "description": "TLS 1.0 was deprecated in 2020",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid{tls_min_version=\"TLS 1.0\"})"
    }
   ]
  },
  {
   "title": "Min TLS Version: TLS 1.1",
   "type": "stat",
   "description": "TLS 1.1 was deprecated in 2020",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid{tls_min_version=\"TLS 1.1\"})"
    }
   ]
  },
  {
   "title": "Min TLS Version: TLS 1.2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid{tls_min_version=\"TLS 1.2\"})"
    }
   ]
  },
  {
   "title": "Min TLS Version: TLS 1.3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid{tls_min_version=\"TLS 1.3\"})"
    }
   ]
  },
  {
   "title": "Good Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cert_checker_is_valid > 0)"
    }
   ]
  },
  {
   "title": "Certificates with errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(dns, issuer, not_before, not_after, cert_error, tls_min_version) (cert_checker_is_valid) == 0"
    }
   ]
  },
  {
   "title": "Certification Expirations",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(cert_checker_expire_time{} - time()) / 60/60/24"
    }
   ]
  },
  {
   "title": "Valid Certificates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(dns, issuer, not_before, not_after, cert_error, tls_min_version) (cert_checker_is_valid) == 1"
    }
   ]
  }
 ]
}