{
 "title": "Node Exporter for Prometheus Dashboard",
 "tags": [
  "Prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU % {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100)",
     "legendFormat": "Memory % {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Low",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "(100 / node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}) * node_filesystem_avail_bytes{fstype=~\"ext.?|xfs\"}",
     "legendFormat": "Disk util % {{instance}}"
    }
   ]
  },
  {
   "title": "Resource Details: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})",
       "system": "})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free inodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_filesystem_files_free{instance=~\"$node\",fstype=~\"ext.?|xfs\"})"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
      }
     ]
    },
    {
     "title": "Used RAM Memory",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
      }
     ]
    },
    {
     "title": "Disk % Free",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "$node": ",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "expr": "(100 / node_filesystem_size_bytes{instance=~\"$node\", fstype=~\"ext.?|xfs\"}) * node_filesystem_avail_bytes{instance=~\"$node\", fstype=~\"ext.?|xfs\"}",
       "legendFormat": "instance"
      }
     ]
    },
    {
     "title": "Used SWAP",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1) / (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU% Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$__rate_interval])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$__rate_interval])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$__rate_interval])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Avaliable"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}",
       "legendFormat": "15m"
      },
      {
       "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPU cores",
       "system": "}) by (cpu,instance)) by(instance)"
      }
     ]
    },
    {
     "title": "Disk IOps Completed（IOPS）",
     "type": "timeseries",
     "description": "Read/write completions per second\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "Disk Space Used% Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "$node": ",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_ IO time"
      }
     ]
    },
    {
     "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
     "type": "timeseries",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Read time"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{device}}_Write time"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}",
       "legendFormat": "used filefd"
      },
      {
       "expr": "rate(node_context_switches_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "switches"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "timeseries",
     "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~'$node'}",
       "legendFormat": "Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
       "legendFormat": "UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$node'}[$__rate_interval])",
       "legendFormat": "Tcp_InSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$node'}[$__rate_interval])",
       "legendFormat": "Tcp_OutSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[$__rate_interval])",
       "legendFormat": "Tcp_RetransSegs"
      }
     ]
    },
    {
     "title": "Network bandwidth usage per second $device",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "$node": ",device=~\"$device\"}[$interval])*8",
       "expr": "rate(node_network_receive_bytes_total{instance=~'$node'}[$__rate_interval])*8",
       "legendFormat": "{{device}}_receive"
      },
      {
       "$node": ",device=~\"$device\"}[$interval])*8",
       "expr": "rate(node_network_transmit_bytes_total{instance=~'$node'}[$__rate_interval])*8",
       "legendFormat": "{{device}}_transmit"
      }
     ]
    }
   ]
  }
 ]
}