{
 "title": "Tailscale",
 "description": "Tailscale - Point to point VPN. Shows traffic and some other metrics. dashboard retrieved from random guy on the internet.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Summary",
   "type": "timeseries",
   "description": "Inbound/outbound bytes/sec per interface",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(tailscaled_inbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[2m])) * 8)*-1",
     "legendFormat": "{{instance}} RX {{path}}"
    },
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_outbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[2m])\r\n)*8",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "title": "Dropped Traffic",
   "type": "timeseries",
   "description": "Traffic from relayed connections. DERP (Designated Encrypted Relay for Packets) servers act as a relay server when a direct connection isn’t possible. Relay connections might result in higher latency.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_dropped_packets_total{job=\"$job\", instance=~\"$instance\"}[2m]) > 0",
     "legendFormat": "{{instance}} RX {{reason}}"
    },
    {
     "expr": "(rate(tailscaled_outbound_dropped_packets_total{job=\"$job\", instance=~\"$instance\"}[2m]) > 0)*-1",
     "legendFormat": "{{instance}} TX {{reason}}"
    }
   ]
  },
  {
   "title": "Direct Traffic (P2P)",
   "type": "timeseries",
   "description": "Traffic from direct peer-to-peer connections.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(tailscaled_inbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[2m])\r\n)*8",
     "legendFormat": "{{instance}} RX {{path}}"
    },
    {
     "expr": "(sum by (instance) (\n  rate(tailscaled_outbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=~\"direct_.*\"}[2m])\n)*8)*-1",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  },
  {
   "title": "Relayed Traffic (DERP)",
   "type": "timeseries",
   "description": "Traffic from relayed connections. DERP (Designated Encrypted Relay for Packets) servers act as a relay server when a direct connection isn’t possible. Relay connections might result in higher latency.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=\"derp\"}[2m])*8",
     "legendFormat": "{{instance}} RX {{path}}"
    },
    {
     "expr": "(rate(tailscaled_outbound_bytes_total{job=\"$job\", instance=~\"$instance\", path=\"derp\"}[2m])*8)*-1",
     "legendFormat": "{{instance}} TX {{path}}"
    }
   ]
  }
 ]
}