apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - ../../../bases/envoy-gateway/
  #- tailscale-envoyproxy.yaml
  #- tailscale-gatewayclass.yaml
  #- tailscale-gateway.yaml
