apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: tailscale-lb
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: k8s
          tailscale.com/tags: tag:core-infra
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                tailscale.com/hostname: k8s-load-balancer
                tailscale.com/tags: tag:core-infra
            spec:
              loadBalancerClass: tailscale
