apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hcloud-exporter
    namespace: monitoring
stringData:
    token: ENC[AES256_GCM,data:/3Q4ABZZ69+ugMGxeomf2hjWezyJmylU8LLbS+TiqgtCm9I5sKtrh+N0B0GluhhMjlbCQ9/ToYZoFXUtOBng/A==,iv:jBZwRt0yjiYjV8zKV5Vu1pzgQCpF353vksm09DKNQQg=,tag:gbW0Yxoh19CNRbfJBWI6QQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WUhmelg1OUQxZ1crS0tC
            ZXFlU1pxbFAzWU5CaXBhUWcrcHNscllFVjA0CkpoSXM2T0JlTWcrWVBtUHM0M0I1
            emFrZytWQXpML21yVE02cXFycThnaGMKLS0tIE4yOWV0cDVLVXNVeXRPbE50ck1B
            Uzk1cEs5UXJwNno2cmRvbitadEhmbDAKRHOjlsnxnv8j3y/nM9I7MovGbAOTGmW+
            rfn2kDT8BXcrivYRgI2UwX3hcvNEEpOa9xzBnBc6HBiVFBcv9sjC5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWXFZOHdCRklaMVFYZE9I
            SVJDSFNnMDZub2NqNVFIU2F4Q1JUVUQrOVRFCmlFMUdGcHdqZDQwYVJlZ0Jqa3N6
            VktLMDg4K0lvbjR6MFZKaFRibjI2VncKLS0tIDNkdU5yb1pIQlVTRzhzWHBHazJt
            WmhPQjh3Y0p0V00yMzRoeWhnV2VGTU0K2O8yKc1k1un3UcJCbmr0Z59cahYN2K2R
            iWtLdtCocW/17ZhdLN6yRkvxv4UbZ39IS2+Tr20JXoosUGl6wwYtOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMUFNam1rN001UGc3VVNo
            N24rL2t0TnV4SUExclREa0lpMHMwSGEzSnpFCjN3aTBJUHZpRjFqOGU3L1pUUUp5
            YXpZai9ISnorblVoNysvTnFrbFFUT28KLS0tIDUvUE8vNjZCVDhHc1p4ZWtLTXEw
            ckppS1BBMDAvUk9kaUlIZ1M3WWtXU2sKbSHwxcMsSTSMiqll9ICjjXkLi3btrShw
            a5c+5lnLx9O0e8b+6VZ4mml+UszEYvxYNMpRZ6HVhfI4yvUgz0F/Ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYlhnSTVQZ1hOY2Z0UEpk
            THZZUGdnTm13SU0rdHdidENDSzlIY2pCYUhZCmVSU0M1dHJzYkFEaE1WTnlWWE9O
            SjFnQ0FIaTVSYXhucWNwTFh5OFZ4VWsKLS0tIFVUcFRIRTNNNkJ4TW9Wc0U5VHRZ
            Z1AwS0xrTTJsVk1wSVpWME5JOUVRT2cKwtQCq4Om24O1/l1gJfyTQyaC4Mb9+UB/
            luMV/BXs8j3LHGILj2dv7jkZoWkl/G1a+TkJUFJ5nJlXpXY/YMInaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T21:13:19Z"
    mac: ENC[AES256_GCM,data:8PxUWtvSpXKGWY2Uav6DtxYe1JhuQmzxqQks9P6DmSVsqN+ngAYFicGVy3arFrDSR0EGvYg9KBZEIkNnWjmdskN4uVMnjMqgdEKIRZ03oPZB2H9VHJzxsCk8GYe3e0UfwsKJHV9/kVWiLfRmAhJjx9BJJAZ62WvsLzfmkPdw06M=,iv:T/oT8stDbcPdhbswU8S60QfZuX2zICetKVH/Z+QQOxo=,tag:cB2XFR+MkYDUinLR6mAHjA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
