apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: holmes-secrets
    namespace: robusta
stringData:
    openAiKey: ENC[AES256_GCM,data:8I/67qiQIdA8lE6c/c3oiznVsbwUgpXwXiK2cGT3ScepPPpG2UI1jD+HSAwW3cpBxW7+mq3/LVi8paqtO5bTGDIty3mg7X3hTK6sB2tF82tbC5Q9P7qb7pUAVCrRocztMXQeES9m3UmPwS1uhOA/lBKcHDaZFkQwVHsKu5SvfrOI7nb8qaKPTA7C6K48oOUwMr99nqIIfXA5fFw6cBfle7yD/uE=,iv:jg4efu9FWpHEJngR1WYKfoO0zlxmmCN/0LYstyCmiJA=,tag:iPWfc0XFLDWwnXKmRhbHZQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0emxZbHoyS0ZJV0hKRk9H
            bDlzSS9zdUphWFJoVjRQd0ltSy9Md0VhcDBRCmJZRHQ4bGYzUUR0K09MaXVGaEg4
            c0ozaWpQQS9yK2V4ZFZHMkRGY3VyQlEKLS0tIEExNW5heDZFNitkbGhiWElwWjY2
            dURNU2EwejNlc2E5MDJVanFRdll3QlkKqAE3IVINvKEMrUC2mWIqcBkBAo+hcR4o
            1Ldb9IpFE0exFcgRN+Caox6NhouLhW1FrOaBvMXUz8uYYVfVRe8SlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTGZTUEs1Z244WUJINXhQ
            aUJtYTZMbDZ1eGJDZkkwbGcyYVpDQjVzTWlnCjlwWkMrR0d0RXNETGtPY1ZVRlJh
            WXJ4WEUzZ0JuNFMxdEh5SHYrTWFYc1kKLS0tIEpISC9sQ1lVcGc0MVczYy9EdEty
            SVpERG9xSmNDSWRMODB5OWZlRHA5M00KuwCCV4uTIUaUDdfvVbrJF5CHL01n2NjD
            J+ZM/jzkBn8tyB7ZJsQwGZmToiPyqGX0qrMTTeq/ik+7iImrWPtc+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkFaa1lGL25hTUREL1NE
            akFOU0NrUXYrUHdtdDc5dnJYclMrZEdUM1VBCldEMEcyZURTaFFWSnc2bHVyeXRW
            SWcrZ3MyNUFka3ZEdGJ2eHFmTStrNFkKLS0tIEhpeHcraDNZaW9yaExOVG80bURj
            cWFqVWFFc28yeUs3WmxrQkxlbWxXQ3cKzxFogXgPF0xDocgVVjV4k5y9EOQ0S17m
            irnxWDnhw/SUiJNZaFJwMiqshnmjpm7t+zPOs27ARw7zku235feUzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:lw0dNIZ+rBapvv/YUQng6Q0SeHEpgmY+jc/hyrXhM8qyc7E9A2UnLfmrP8MuWczhGhC9DvOpGzf+hsVjWXpsK3JCrn2hpZ4DDkCrmTiLgNQzLli12bYNhJPgqqVUvlzrldof9kS6kuXo+rb9Rq7FIsb/XEkqorI368DqdhUwSOo=,iv:QAYEfD3/pK412pVOCPIzRnkWg6R1cVXJYD10TTykKHU=,tag:uT5t4TuUbSjRlo7eH6fdxA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
