apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: robusta-secrets
    namespace: robusta
stringData:
    signing_key: ENC[AES256_GCM,data:m8WHZXkmm3j3n5NA/AeL9TnSrpvDS9T24R3OSDNLv6/CH2RY,iv:ibJgkav+y0iJJxmoJodjEPIRlBVFqUs0cEiERSufDQM=,tag:ZxQrbHuDvH/RXKUma3Ngog==,type:str]
    account_id: ENC[AES256_GCM,data:vfJncrVY+aACFYqQJqUvxF6IV4VOXfg2ftCfiaAcTnO0qVZK,iv:+WPtcQLJIVDtT6nXaq5VUO3ashehnYyECYHQEKgNFQg=,tag:v0amdoqNsGxSkBhuxEHbtA==,type:str]
    robusta_ui_sink_token: ENC[AES256_GCM,data:J9NwsDW+lr/zCdUExFgzBq8joUOOz8KlpiZQ66STG0o4Ne6OjGMTM0WDc94OtPD2b5lBUnWmT0jG9IAmMGZqRvC+tiUu0XyhUtcKQa890fEi9iWL0YwV9j+NQOf4nr8blXaclMSxDzieoWY9owQrYf1iCwoD8oQcJFS7Nefcadl7IMnCy+28fpZFPPSzIwFUxQezbPmeXJiCodWXUhfgPH7X3FuDsmaSA9Qi3n5Vyiu2duSWXeHPnqAoaPiwhLVoaFUhr21RFE0/u5dWY/jwr8+2s1Skhg1N1LAWhmzHnl7YfD094vXlgPf6ls2gL4QToCIhqefSYtgziyOL6NXmnMXdG/NbVxO2u6eJYonQUFApRmisi6pTcUKqxSXQUZjS0CgmO9x13IbVR+05H8QEln/guKpvW6lIAs54mzciPwurWztVlAs44XwuuVmkrK5c4Du81kEtdKQE2gVRtqy4fsNXhLirHuDy5tl8YGGuSGb0X8APBXdNSTH0pM+vxRLrEl/VBJ7SUuvnp9m97Kc+Pnk9fSlrv86NRoXJZiAiR29lH1g+TnroFG55kxOlFSG04i7uhwRgRLY77Iiw9vLIDxV6TmsuFEcsElfIt2YRCghM+ThRbfkC55FftIIG7ldHORfcjlJNDbmwOTWUONIddkTRjZc=,iv:RAW6mHcoGE9iuupScB6TbYzZP1KapnB4TJNRv9+65T4=,tag:K9Fc/59rihFYqetIROKJSg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbGNGUDFXYnNUenlnWTJt
            MEtjQzFOUUdtdlQ4Wm9BWHNyeW5nWXlOVENVCjRhTTVJaDhkeWZyNUJ5eXNmRVdz
            bkNNdkI2V1VwaXFQbEJRVExDVmJxNVUKLS0tICtFaVEyT0RPQndCc2NNTkFlQjA5
            R2s3aG9CdFR5L2RJQXNwck9VU1FXdlUK3drTMJET8nLNJLfyeleXvemKOIkCDkzH
            Q8x0R1z/icjs0u0X8AFOpGZ04S9pDtWtn/hSSA6dHhoUIEIbfPB5KA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eFV2bzJaa0h3TzRQcitn
            TVhoNkRneHcrRXUxUHNNSlN6eVdLMEU3KzBjCkRMQVl4TUNEVm9MaFUvYTlHUllP
            eVlpMWd6UkJLSzBrZFc2NWF6MEdxZXMKLS0tIFE1a25iUGx5ZURCTjNZUC81Mi81
            dkQyLzB4MHJkTzVYZk94aUtpMlkvWDAKGyljmGj2mTEgA+DvSKu5vpdKXhlq5Ogv
            w1mNmfdCumEbPSzTNpXeC9pTVtAymW0bhF6DXYlRwTOtg9nhJHO5mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z25la2NoVkl3MW9QNU5h
            K2dLa3pQMjRoenhvY0tOV0VnRnpYNDAzZ2pJCnF1SWZxL1MyTWJ0SElLNGFHcVQ4
            VDBTaytIZG5iY3N2cTg2c2RLVm9HZE0KLS0tIENlTGhxdVhmamRmVDNpS0VINEt4
            bjZBZDZrUWRjWk5RMC9jbkJpUnREcmcKfx/+E+8pw1enwo9Y91f/TVxLaRRjTbJ0
            AFnzVugeuF95YD1jEjMKmJuMUNvlvT1uwbNfkkL22Bf/B/kM51EMkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:alER9Raj/2WgWWigXFakOadnC09nUwFrlXAXaixUUPnqUGlUYX387NSkrqZbKzNdov69LPyStzEaRltmR4MeYrgDBrmI9mFLXm5APiUAygISWkOVjxZkLAc+Ro+c+bSing8e/qlDwZ+LADXgSL58M582Vl8ehJkOW1PbTfxYb4g=,iv:hN4Ce//d8I+UCyScIhcqsv2v/GnQQzldupZXZ2qCWO0=,tag:kAiijM8GniX35xCNn4qZ1Q==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
