apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: robusta-secrets
    namespace: robusta
stringData:
    signing_key: ENC[AES256_GCM,data:PfubJhW+ij3G90fiRlsi29677rzAWWZVMLtvlb/OsLTo2nIR,iv:PD4N3j+u5fB8DP1agwfQG53wW5tzU7LFsnefWkK0D8A=,tag:SeJGPE5rZJGn6LDgx08RlA==,type:str]
    account_id: ENC[AES256_GCM,data:ASrr6SKudyJJD+t2xGNb7XpO8zzpxtu8R5p1xpHIzcuO9HVk,iv:rh6LruKcJowoIIXUFGTo3rrxJ1gIe/6XbRZCh5seqGg=,tag:N+p2iaaYzayx6mZigY7tBA==,type:str]
    robusta_ui_sink_token: ENC[AES256_GCM,data:aTzs8mXGKGtA2+eS7DTNp5Ml43fTT7gl7RUCzPxAE5fLN5dvyX8ffDHepPhwZqG1BgeF3Hm7qpre/hi51F0M3Nq5NezMdljyEYznV2GjfnE6Acagvw9qkgrv5uMA9JEe6lMuChu5WU+E+YjURV+OTTPeIidXIm93I3p/zuBiqy+5pZ3GlVwg5SoptQKBytcnA7M/BBOo8IczU3XdlbFpYWoN07i/llq/bmpfbbbDrevY2DMlur1LwmMcKBzDgIohbMpRuUzRg9seD6vUikk3gTYPbibSP5bNbxViO94VoMzx1AmJQ8zkCMpURFyWFs6ImNQ1qdSC5jMt2+gZE6KigcvqR4LCuB4WQY1dgjroeNOaOumHSjWW/zyEN9CIFYoBCvhwAbAZrpK7cVDh2DeyjUAu41BHFh/GRXFRARgwUebhP1VMEoRkBuimMyJ72jLNuYm1bnjws3AC7kCOPjQUpwvZ5L8yYGZhohheJakYSLgYxsZY9d6ZkcQ2Mjxb7UF3nMn9OTWSme9G1lHnP4ylAClGCbCNbHO9L5nESIdwCXBWZ6kz25OP/vV1bSCtXrg9kRRnR6W/QqZ1CIwF6eCxhinKrgh+HG9y8IdakC4z+GDg1w4Zdb5XASjlpJwieHV+S3hheS7MHwadZ3KDCQ/E82c58CA=,iv:nN79KAkjLcsTSAZWQOwtxnSZymq7dzauuvPWmJ410g8=,tag:DPhEq/UGiMIDUlKRtULczA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSmVqOXhGRGJ6ZWFFWnZH
            dit2TzR1Wm1ZUFpEYm96ZStUckFwbFFDaDE0CnY4N2RLbm16bmJPZWhuSVVYVDdU
            aC9vVGhheldmMGpkbjY1cFB3VU9BWGsKLS0tIEczdUthbUJSblc0U2liR0wxUnJm
            YysrYU9HWUdQWXpVZUJCNHM4RFVCUFkKmLAK6sT84Od4p8iX5nBgWE4nWR6Monu7
            FSFrnNS4GipiM8VCS6UmCd8rCj6m5n8ciF2kWvYS0D0D1vPj+Q4t9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1akIrTnVYQ2tCT1N0Ymxo
            V3RhTnhaZ1BRdFdXeVJxNFp2bjRCMll5RVc4Cm10b2x2N1NyM1gyQ01odmM1REky
            bE1ZaGkxUXRuSU5PcDV4ellzKzJXcjAKLS0tIFdFT09aSGhPZU9QRjNlMjFRSUNV
            Nzh6emhvOVdUbkxreWlyL3QrVm5rQm8KIstdI2t5Q19Hnd3hZWFFIDKcx/B2p0eT
            D4oCQ1rsVKONQiC9vFY7TsrkrW6uxS692K5pmyWgAHfknSgc1IRlYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraWpLYWJTRVg3azFqRjZ0
            ODlacFBUQnZuV3hxWFpUN3prT3k2QVA0NVVBCmRrWThuQ0lhaU41eVN3RjJVMkw1
            cmZqZmQyVDdxOCtaS1JFbG1BQUs0S1EKLS0tIGpRWFN2MlE1UlkvRU9nSzFXRy9Z
            RTVocEZCWmpiNjIza2VVbkI3UnVlcjgKFl21zZRJAg1LQjfDlnvV4O/fAfvrBSuP
            Kc56Jef0AfYmZTFlGR0Y0iSu2UUiOaw7IzGL0Jlfvneq9sqoH2hAYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT08ydTVUSGRuRlAxcjBK
            aW9INzdiTXVmeUM1Sko3T2h3VHRWQVZQeVVZCnE1T3F3clhLVXU0N2pxenhxcmdz
            YitTVUFpa1lWamhiNFhNeWd0NmE1QWsKLS0tIEVaOTVwNkkyaG91eitVQk1YdUdw
            S1ZzYnhGak1xL1RVSUxBbkdTSmt1bDQKZEa+BudNdT9Od3dvxDjiJG3DEyGnjMWT
            ftP1kcbrR2Gyx5sZAxHGDdUA1arCp3dI81T1r2CHfouq48sfta1BDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:SvYtP/QJauLkPF5oCLfe2t5lNUMjRqhQJtJNsF4HLK3Exjgi658hMCOtB5al45H8d3fXGQ49r982ZF2hfeFHMQgPlorwOBpowbmbrmR29BbdvinYN47Qa6i3q1KBgxmFF/IXmNupbCAHHj8M3H92a/lFN/8kzuX70adVAXW2YVU=,iv:lsFJdsjawbcOlWi3jswZBN3borXwQRXLtt5xVuEhssY=,tag:bnasDU4/xO9TcZsK6sBaAA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
