apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hcloud
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: hcloud-csi
            path: apps/hcloud-csi/cluster/specht-labs-v2
            namespace: kube-system
          - name: hcloud-ccm
            path: charts/hcloud-ccm
            namespace: kube-system
          - name: hcloud-exporter
            path: apps/hcloud-exporter/cluster/specht-labs-v2
            namespace: monitoring
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: "{{namespace}}"
        server: https://kubernetes.default.svc
      project: default
      source:
        path: "{{path}}"
        repoURL: https://github.com/SpechtLabs/k8s-deployment.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
