apiVersion: v1
kind: Secret
metadata:
    name: tempo-s3-secret
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:LRxkv7VtP81DDn2IzAYm2oeUU4JjDTGcPg==,iv:AIhwoCwS2zVGFWASCW0WapnQRPwXMV0dcmsl2No8y2Y=,tag:urjzkkKv2Wadl49GtvD/xA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:F3GN7yRXzqKP9Gw/I5x1TqFvRhtH+/oZnyvApyJWDw==,iv:IAcxlA8WWKQJ9BdTzBPA3GBIKYZurYJDe+02XiKYOvk=,tag:0+lJ589FKDtA/bmvjBBwCw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzd5N2hhWUN4cmxwZStz
            NmZWbytETm1jaUZxMmJhM3dwZVhUeGRWT0RJCmQzUGhTV2F5VmdHQVl5YTQ4OHND
            TVkwQW96QzZheEovcTBodi9pNVZiS0kKLS0tIHVkRCs0Zk1OWUVBRzI5c1FNSm9N
            b1dSeitDMnU2b1B1TUtSbXR0WjRSeWsKZTEYPyE0giSL8saccitkVwKxbzgPLdoA
            UVKwroRO7LVX99jddcvLFYdAcMXmhibE/LHbYWZ7KJB667IyUWlMSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXlLSDhZRFQzallDR3p0
            SUZ0SUpkci9CZFE0bVdYQWZCM085RUlmSHpFCktobjR2QjdEaHoyUVRtSEV2dk8z
            bWZHRnYwUXRvNzZKTTYzeVhSS0JwYXcKLS0tIDJFYkxTam9YUzc5NnY2Q21CbldQ
            TTU5N1NzR1VSV0VtdFk4aFJVRDRNYkUKuSUPE2cbIJ1yNafA9FcdWvZDJqhtbPgh
            YrrBComT3d+ZJHPE5eHNMAUF6L3/5oxpr62vP9Fo9uQAqdKoNyog5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTanB3dm9rcTQrMFp3RjNv
            Y2FoaHFtZHFLZERYVzNsUmYvTm9FMFZHTFVjCmd1WVJrc3hOeGVkNU4vYlFJdnNS
            Uktxb2VpWmpRNDVsalVtcjNIakxhZHcKLS0tIEtwd21QRzN4TXh0RW1WMUpHS0dP
            S2ppa2hzaTJMSUNaNnYxRzBvTEtscUUK5Ysvq3hcS2BX619DaLQhCdnQK5bXJ5fJ
            nxbq8DY1KP07IPpuswDm95P2PF7WkIGnwiq16wLYwg6ucxmGoYRZxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:dbXGX3RWn7oruCDTeIhcIx9F3w1UlfWhWlP1aQp/1fqxho22jSif72vBzqR3FBHH1KRSg9Ee8baWgMIKWmexnCYOvZ9Hb1ninNcCOA4AFuN0TRzXaBTIjs+YDJp3myVLcEjk+jLOe9oGo11sspv+JFXqscTlvNXSVwiv2dPcwfc=,iv:skOkb3FxqR/ifCZ1IRnx4i/md8kT5c7JgvJ1B9ROOdQ=,tag:IIJBjxGDKYmZS8WhHNmFYQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
