apiVersion: v1
kind: Secret
metadata:
    name: tempo-s3-secret
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:vPTPDX1cvFTzFFNE0uoQb/X+GnjLhk/3cA==,iv:IgVLWb8keDXvrsMMp+X9SzZaXwFHCt2ACcX2QVT5HCk=,tag:ZrWFaf9KDtBFcOWjSzQb4Q==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:f9zzTk1jRpzzcWLf8PC+oLAZiW8WEmsxwLGlDezeOQ==,iv:9nYqNUpmqaLv1FVszWeSvABrX2gaQoOPEz2ZuDjflzA=,tag:TXnQtor9J/+DRpwk9kfR+Q==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRGFENHl5NllyRlp2L1BD
            M2NpMG5RQThNMkxidkZzWVpCanFYSzM1YjJnCkU2RCtqY1EzMDNyNkpKb1N3RWgv
            cFY5TDVJYkpPcmQ1dGpmbHY5S1F2ZWcKLS0tIDRmWGhzTjJSMFBWS09pcnRUUE1K
            ZlIwaDZCR3JRckJuMWRqeTdqclN1YTgKdtUTbGidtL9InPwgkNRVwWED3I3/uRS2
            FLpnh5/Eg6+B6/lh0q1LtNRpMaXnH2/xlwiFogKvqKncxsWJOqNAGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb2Z2cFp1dHpvRHQ4QTFt
            S0o4akpCeFc4cjhSVmEvOWRsQWFpSHRJb0hVCkhNMlBHODIzcVJiZ1QwUFIvUHVz
            MkRMSG5PVExBRjFjZzZiWlZuWDluMEUKLS0tIGRhQXU1NTBYemp1MG4xT09ISnMv
            MkI3cGdKTTN1ZkFtK3IrU01lTWdDZEkKSo4nkXJ6YFdQJwAOG9HocpO6aW7v2wHf
            N+kKqJtNaeVNO8I0cOSt8qE7IhnOKEOaCs94w4ekl95ddGXucqGIzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjZYbVQ3Q0M2U0tKM3dU
            aDRvQ1BnYVQwdW5nb1gwWGdRbXRXUktuV0hVCnFmUUswNkptd290RzhOMEk1bHZH
            cWVaNHVYRHlhVm1QY0wvQ0g4YWZycDgKLS0tIGE3bWs0d2JhKzAwbE1rdGY5L1l3
            ZEpNOFZNNUp1clZlOFJTS3JLSVhkaTAK91BH5ssmLsH38bKtZ2mR0zGIH0IJ3SZG
            ottBNQpkAS8bDjj2rmcbSlUQL9Crv0ZghC+vrudFO6D9A727FevDDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRDRPNzF2VWhoT200OVI0
            L09XNnVtMTk2U1ZZdU1RbUd5OUY2ZWpNbTIwCkJwWmZvK1hmOUYwOVA2ajh5c2Z2
            R3orQWtnVGhmM29HV0d3cG9VcUxLN1kKLS0tIFlOUHhscFVkdCtCWmwzVDVhZEoz
            ZjUrbWhoRE5aS0Npcmk4aWFFL1ZhTVEKbn4CesfPFtfnml14wPcNOt3m/SEzbr15
            nu5piUly1Vx8OTWLX1wxZRfzNQfjGL6N52Kvl3EbodDBTSY1rZ20+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:Jtv/qRZi93eNkdT6L01r+i2nZaYBPg65h17hTxXmEKwYmZMldWmtGWbMcFxm7PM1D+jTVx0aQhsKHrxtjVXhcL6VvYTO/TCzqj1+YblhIzsBymOWgj81dPK9rj67aYdl43gio/qkgaYELkxH4+KaKo+ivxbP+dAVmHHQS375IRc=,iv:K4PSewe5IYP6zdQ9Mb0ViQpBhNmyNmQq7vjPH9xdzYY=,tag:Z7qLPP90J13DcXbwNEqgmg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
