apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-hornberg
  labels:
    app.kubernetes.io/name: tunnel-hornberg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tunnel-hornberg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tunnel-hornberg
      annotations:
        kubectl.kubernetes.io/default-container: tunnel-hornberg
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tunnel-hornberg
          image: ghcr.io/fam-kienzler/tunnel-hornberg:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
