apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pyroscope-objstore
    namespace: lgtm
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QNvLq2hOuE76lf+AXW/xw53uSoEYSDZHIuBseSS7tw==,iv:yuwxTQss8K7UbQ7NOlE7AYavKkKYqeX/H8YzIIv8PYo=,tag:CIncGObhJpoE3Apmon9qrQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LnGVY/sxOtzWZJPlXQn0CJNKCIX/GTmmBvMo6kq9Wg==,iv:20MJCECnVl+wBtIRkHUYwg4In5h6Uqd5czAeMmBFTNc=,tag:U6cTXL6Z1/uENYa/i+RgqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMTM4U09pQTB3U2xKYkxx
            cmR1Y29sMTVYckIrd3pXR1BYY09LRjFxeGxBCkpQc1JqL2JCNkpSQnA2bWg1Z1ZQ
            R2hYa0MwRjRxYmxqZ0sydXJzZ2V6VEEKLS0tIEg4Q3Vpa0h2NEZ2QUM2Ym8xWWN0
            Z2VCVGhpSW0zVTBJV1BmK3AydFplb3cK5e5yI1LGMx3ZZR9xbQKHVsM771ZSsHs/
            oW8n9HO18e+9rLn4iE/5lXdk6qzrthezSmByncAyIbBqfgp/d3Rkhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT045NG9vYnVHRG0zdUEz
            QWFOZjVJYnlTdGNKeUJqWEEzMlZ5aFJxSzFNCllHNWFjeGF1dkN3SzhxcnJhUmZV
            K2M0L0lESDhRcDZ3TzU5ZnNXckRHa1EKLS0tIHA1QTlaTGRCQXpPdjZjYkFmNkFv
            dzluTjdjVGdsUDdyeUh1ZWJzUkFpaXMKZdX8U/NfruWSFKEwxOuNyz88uyfIXni0
            qH+tLKe7+t6RvGU8QvPqSfQ1MEi3iuvh+KLrbvtdgf/+z+ELfQW1Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a2VDY0JiNmdUNlFZK01j
            dTV0ZkIydC9VM3hyaUtyTTkzRGlBbWRyZXhFCkdnTzE5UDMrcVE4QmNSQUxRSk8v
            STNxbWc4MkRUUVNxQ2xVNU1lVjNBOVEKLS0tIHFJVUl4U2lrMjhHT2ZYQjMvYita
            VWhjb0tkOEtpaTlrL3pHUnIwVm9xZzAKEXyI6/Afm1yYA2CkMZ+26PZfifHKwaUL
            OR0yBZDcz0aNsYZ7LS5J3Xcr+gWIWzx07KQXIjD1ZAio9HCPY/fo7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYmdKUEVBTGd4L0xydTFu
            Q0g3amFYcXdVcVpGQS9NaEF1YjgzQTJycUdJCmhwZVlQckQ5NThSUTlCUUtQNnYw
            RFg5cTFqemVlSUhZVldjMGR6bkVSWjAKLS0tIFQwSVMxVTZlQ1pWNEJQdzVTMzBQ
            Vm5mbFowT3B1M3NkSm0wdm8ySlZ6MncKdCttFqpQIgD4ZcsgA0X3fXlJeHb6n5oW
            0G8fVrZC/CUQTzKsy/Gvgix3IBxWU5uyumWGkqzmiMV5ZKW3gfC/jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    lastmodified: "2026-06-17T22:11:32Z"
    mac: ENC[AES256_GCM,data:4tuG3hjADgAp11C5AlESwzDqf/P5vUgeIsA8biVBG/h6dGdO7WUKgc0WzPJvKBExBlVj2J3o6osmurF4qxPzTfv1Du9BHnHHr5k71MrxGzjuYfmoJ8ruZA1Ce+a8/Q4R4JX2BIxVIr1cmERLkyIU0G1nZAD55DKGCXbbCJY68bA=,iv:0Vhl0Ff1IpiuQ7lmt1bfpuMztV8XqCv6ce8vtuOcDLU=,tag:8YU3AnMjJRWe5L4+28xSSA==,type:str]
    version: 3.13.1
