extends: relaxed

rules:
  line-length: disable
  new-line-at-end-of-file: disable
  indentation:
    level: error
    spaces: consistent
    indent-sequences: consistent

ignore: |
  .yamllint.yml
  apps/**/charts/
  apps/*/cluster/*/*.secret.yaml
