apiVersion: v1
kind: Secret
metadata:
    name: tka-tailscale
    namespace: tka-system
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:Ddj65wLqfP4W24AJpVxX7x1iqct4iA0yX0JMDpi2A2kw/Z/pjlXMYE/EcfU0mjIAuH5x8/wg4McUXszJNA==,iv:jfD/8x3kgDMiiEA5jbz/tRySjUMMTY/iFh8lAGumglE=,tag:ZDMALGImZqSDMcoNgsKUNg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSnhQdnd1R0p4VnZCVmpv
            WnllWVhuT0FtSFlXYmNMM3d3N0srY09CZFNNCmZLY0VUWTdQcFI2aCtEUnpXdFNF
            SHlibWxxaDM1MjVLMFRjRkxMNFZLRVUKLS0tIDhIOFJpd0VmTTZPTldIZzl1WjA0
            T2t4ZzF6MVJpQVE5cnkrQVlsbDJJeHMK/zMcMwqiCSKyWDP5mAXb2R28rS/VJKYl
            xYEX2KAu0L0GLfZZO0rvecanrDWY1sU/XN3xxikfImAOf8bJcOn3mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTFdZSlZHRUNJcXhuc1Jk
            MVdENGxhc0xiQnQzVkpGMzQyUWRacGw1TEMwCnpMSzZyUXU2QVc5N1B1ZlpxOUJN
            a1dqMnVNN1ZZUStiUFpXTUl3M3FsVXMKLS0tIEVZT1E3VjQ1TGJkUWJ2SjFDdmVL
            MHdHSlFaMFU0L0QvRGcwcEJuMXlab2sKEwFLHtB8PHi27X/UQszJK/yZEZOP9Gtq
            MVNMDPR9BkdXuJrqugMoctlRIlgCDQgswKNZt02QrifUZoJ4ctSW4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjJWMERkMlBETjBxQy9K
            eXBLZmNMclpSWFg5RzF5bE4rbzFtejJNRmxRCjVRVGdOVlpCMkpWMVhpeHRjQ2Rh
            SHI0NVZCVEdLL2hKN3hxQTQrQ1hBaFEKLS0tIHIvS25vcFFEMnVod0Z3dFd1aFNm
            QVNHQlA4cGdHNmNXOFhZM3EvY0RyVWMKPL93xvmFG0I4jMMW+Elmc+v4IzKYahEH
            WMtGKLGJcSFVBT71LGmfs5+k/gtmbOQKFDVSRkyPXSzOQTjt4ruU/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieEN4aDk3SlQ0eHl6TXBn
            c1lFQW1TYTF5L1IrcVdHZ2dQWjBLUGtESFRzCmtKeVNxQS81QkhsVTExQ1dlUzgw
            YTlST3Z3TUFzWEtkTzdLOWRuZnZzdlEKLS0tIERwbjdkNW9US25SYTNUcjhsbCs3
            WmlPU1FyVHVGdnZjcXFyb3hJLzVOVmsK2CfYzHrkcKvyojbfPkP/0N4rGDNXNqrq
            vaKdp6nfuaACyXhHA4QXoO9sQieD+E9HLacBqLFQGfZ2AqfuIKmYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:V1xmfchauD9rscIOvTKhajuweuUuTxq8aNpc+knUDp1MOQbe/r2AfTDQHy1S1Ks+IHrz8qOVX9D0r48ZKtbe49zsRJ2cLxNXpxBlN6EojUISUa7RaBnXUY8QF2OF+s6f35yCVF+eVn1gSnNeBuSc+mrxlNy91JaKtLe8rCfS+kM=,iv:TN8/smtsNdKmu+aEhlNkvvXnBtIl/tRfTKgDaXP30IQ=,tag:B1elGD/eG3BInjb8dHsVKw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
