global:
    resolve_timeout: 5m
receivers:
    - name: blackhole
    - name: grafana_oncall
      webhook_configs:
        - url: ENC[AES256_GCM,data:aeDHgydd4CfC6aCfKPn1cHJbqmoHKGtMgVs5cxOqzXAduVFFjt+sI4EkAEW3sXMFTDvh096vAw4761FX20Dr580Z0LKW2WX92TWOTrqU78mVVhTPpI9r,iv:oAGUaWu6Yg/6Zuj3X2gIm65PIgtnjEdZn6h+LHMXi7g=,tag:IKLcMJmtWqMbOi7zIMaa+A==,type:str]
          send_resolved: true
route:
    group_by:
        - alertname
        - job
    group_interval: 5m
    group_wait: 30s
    receiver: grafana_oncall
    repeat_interval: 12h
    routes:
        - match:
            alertname: Watchdog
          receiver: blackhole
        - match:
            alertname: etcdHighNumberOfFailedGRPCRequests
          receiver: blackhole
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNTlNbEZiSkRjWEE4WFhk
            VTYydHhOUHlJcnpNUSsrNUlOWW1VK2NYZkNRCkdRNlBLSUMrZm5DS3hzQjhvNkxl
            cG9sblJaYVNySUpjRHVTd1VVbUdrQ28KLS0tIERJaVdXNzRHLzhid202UGZIS3Rm
            T0xQWDFvNXMrOFZTZXFuSXRuZ3k3VlkKCDECOeHO4pqcfZsL2i4A6CCM6qZzx9OX
            r22/T9w9JV/u+NXwaigRDiJPiyHOPrsivcWBhJVe76vA2imZcpdGwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ0JPZzJYcFVEaStKeElN
            N0xhQTc1K0l5dWt1R29kdmQ2cFhrTThpamtJCjB0bkVrUmpaSzNPbEdFY1h6WFNs
            WGtqVytCVlg1cTYyN3ZLRUZ0YW1vTjgKLS0tIElkc2ZJS0FGeHRSVnZ3TDVFaThL
            akJnb0NtOC9yVDhHd1RtVXR1L0FSTlkKCwzvGXvCsdOMfeOtsGNhCCRiN5THMhc2
            wRm0Ncj6l6/OW2IwN7uXeVsLpMwI0sKTokJN8pwmboV3Blrv2j+1Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVTRvdEkvZ2ZiR1VVckx2
            L1JNN1RUTTBiTUliZHpNTHU5UGRWTWI0TmgwCkxDa1RKZmR6YXpQa2lldkQxYmRR
            SUxSMVJPSnRzRVgvbDlDcTRwR214dE0KLS0tIG1acXU1SHZBU0ZnWmdnZmVrMkVQ
            d0FubDFrcXRCK3FucjBDajdiOGZRS2MK/cHblgMZ6AaPuyrAMcO/WMO5vB8XuDJR
            izHquyqKN3IDOAR6Lo5D68A8F+TGjn51NeOLBbjdva6fqNS5D3RSKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU3o4WFBnUllsWW03TGlw
            VGZ1dS9zQ3pBUExaeEJJL0xQUVEyQ29NS0YwClh4OFJmNjVqZVUrWHp3TWwyMGVt
            b0c0cUZwVjJ5MVBISHBRQ28rT3NUK0kKLS0tIHNzTysxT0tuWVM2c0VwR21MRmRT
            dWk4SFhRQ3FBYnpIMmh6QVZmYkF0cjQKTl0mu4BCEzfdGouQLpdhnDUR8QqPToKn
            c6yDkMhNt/kedaH7MpgnOU4HoygOzjIp3T3pFZxOWm4aMhVZrYUOkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:nCZnRA0jjG7Df3L8r7xk4gNHKpj7qy+EVJi39r1sZMOXffLO/eojHvY0BqO86y+45G4BfFc5rA3z3qfmVxBWuf+eihNf+j48jjIAK7Q/u76vT673ncSbUmfbT3iG0qHBAh8rcBO+xebCvZT+JX2nbrMUINmmuUYEG7Oo5ATYJlQ=,iv:v8c0YvvQaInsMArsciLbBYGX/DfdaTLASRtZ3cr34kI=,tag:3Ayh0va9q0/qNIJmGgMFdA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
