apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - machine-template.yaml
  - controlplane-template.yaml
  - config-template.yaml
  - cluster.yaml
  - machine-deployment.yaml
  - machine-healthchecks.yaml
