apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-pdc-agent
    namespace: monitoring
stringData:
    token: ENC[AES256_GCM,data:1VxilwgGtI87gDE2q1QJBGHNBX7OWSfFiurXzszHXKddCcdCFg4pCGu8ESasty6E9vdCG8z7tVLYxiGWEA/vay8S0xvjPReCcYTjmIowJyH6hSF4tzvVLrgsq2MTlLVXnAY9fnDy9hlk6q3iC78lF8+X+N796gxSsqKISltC/QuA7HH7NJdpldJisYR9aet/uzZCbt6uvinoTjeZz1H3vQ==,iv:THrGTrlzepzCdN94NQqJaE+2NudmQJTXpRSgLNgywYM=,tag:G3HzRRsKJbTd9ZNgUfHrlQ==,type:str]
    hosted-grafana-id: ENC[AES256_GCM,data:uT2zV0+akw==,iv:QU3Oibwuf0ePhNaredpX/Bndn3gf84bAp+dORePiM8k=,tag:4glH7NfngFnT1tP/h+SD8Q==,type:str]
    cluster: ENC[AES256_GCM,data:djS5WPXtVa9NDDGx46M=,iv:BryH9HEsRMMJnYk6y8qTO4BUE3xA4Gz1e0k9a6v43OY=,tag:aFeNvK7Wc25AgXcTybVtlw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOE5ORUsvRjRDWnRtdXR3
            b29qNWVGZGE4WU1hZE1hRmkvazhyTTAyQUZRClBQdzJKNWhSMWYwc1ZSOVFQSWw0
            YWdtOFI0R2dnaHU0bzU3R0dObklVZjQKLS0tIGNOTmhaZndWdnlWazAyb3dVMi9n
            ZjcxODJ4LzhZcUdvblRMdmhaRWRyZ3cKWBYACJdXP5jKP/acHqqNDcp/pHwUxCFb
            w9MtBv7cfil7TYbyye4dE2/cdEcY3XBMf3aBnMpa2xrSNYLwZREsAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1d3UXlEUVpDdENrbkov
            eUg4RTlVS0xQbXkwYWNJMTFiNkdqd0FpY3lnClVrUk5oUXFFclZSaE9pNGZUZG4x
            dmh0dXFacWF2aW9ONitlQXNwZEl1TjgKLS0tIFlwZHYvbktSV3Z4dXg1aWhmM0Q2
            RmVmNmlteW1aejNwbzNpTVBidnhsQnMK260N196qTFQnaFvyTu50k7bh40ONpuup
            egxzrPCBo2W7DhS+21yVGxbGuZGfj9gLqT3Y02Zv87PRzs/0004p4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFDN1Z2bXh3akFUb1c0
            a3JMSFM1bnlTUml3dUVnOEtqRzZlZjU0ZVZnCjM1dE1zM0tETG9yT3IxR09xSGRO
            YXhTRXFLWDQ5T1VOVW5vdjhycEhJaWcKLS0tIHZ4aDRySkY1bytpQXJhek1HdzQ5
            UVRtekFLVVVPRDQzd21FOEVFaGYwQTAK42lggS/vBOhPUAfXZJF0SnUSEIm4oMPD
            ngS+tp6yQ7UBzk1GC8RdQFhqUPYdZLMI6UvBzF+uukLUIHDhm4ghwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTUludEUrNnhKbEFBMUpw
            OW0rdzRUQ3NVajcvRys5M0dKVy9PdHBVM2hVCjBHNVdrRklkT01IMFVQOEZzazlk
            Q0VDeURwV1E5TXFMNnNVb0xOTWJaS3MKLS0tIDBqWWcrV1JFdzJGNzdieTF5SDBm
            dWV0NS9VbDE4VXY1elV2dkYrSlVHd1UKDlQTxxZGqndXoBuEVHgQ3+6Ew3uF8sMf
            VgBmhF5aW+5/s+Qj2qZOdoCCbY/rE2jE7KBDcAEnQzBeohY2A9VxZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T19:24:03Z"
    mac: ENC[AES256_GCM,data:pM9TUotz33AqyGgT3p3abLb0Cj3cduOcNIrsV4B0RUXxXtvw5E1MWE6GU3gIQPzuTnajwwZHYHXwQGIZC4RxNOAZn2ftFWBZf+/HB/N5IjlOvAeu5jRrMmhSQhbHrxO2IQFzkChl5mG95E8tamMLByVlznasZ/nXC127PQsH+mA=,iv:lTHTef5j8ZtXLK0Mju3VNYw6+n0jAyqChKod1UqBEOc=,tag:P1+0JHXffqiKXoETHld+Qg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
