apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    client_id: ENC[AES256_GCM,data:pX5u655h/wroSj+Ucaa9lM4=,iv:DQc3XDFp7tChWgRoaPbAsVepcteOi3u3P9jXz62M0nI=,tag:tQbXmJxHo/Mnv4DAFA030A==,type:str]
    client_secret: ENC[AES256_GCM,data:Co0cjg/XsueADn6O7mRQCmAjA81WLFctVl98Pxjp/hn0zjFha13/UWgr201D/kbn6jg/XcctjFj40u0zyvZL,iv:hVgcQ2YjrGT9wh9hl8WkJmrMfNNI93cQVXEFYZHpDA0=,tag:dfQ3OtdkWYwGrC5dTMid6A==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUx1QXQwelhwUVh4YmZn
            d2t6aHZJME01TEpkSU9WMHpVNWVoYy82MHp3ClB4SUdwUTJwM214eGFjT0lMV3No
            dFpsa3ZFR2EvOFgybjFsamZJWVRZM2MKLS0tIEoyb0hYUnFJSUhYcXZOWUtoeTRT
            eDFsZTFOWW1WSG1kYUJ5STl5NW9hWUEKPzL6Eti9nFWSNluCeFW761WY6FqVx4VC
            /nlM/U0wNv/5Gw62owsJRaoaW9AbH1IqPhBxpBwGJT6XvorI3Cur5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUFhpaHZjWTV6QXR4WDdh
            ZHB3aTE1Vklaa3kxblJCYzRibytTaUtiU0dBCjFNRDJEMFZ0aXE1d205YmFtTkVj
            Y0lPM0FHT0dRUzY1a0d5OEhHUDRRU1kKLS0tIFZURzhvM09oZVhqcUQxNUdTQUhX
            NjRjTWJBQW9qbUsyMHJqSS9UTXNNaTgK54nm9x6lk2CO1nVu7wb5jB4CGoNLIW5G
            mApgu7NZ7LvE04EloQZ145V8Gp+BQRCHXbTpLTMzX36xDOOC0HbpoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVFlUb3ltUGxpdG5PVUxL
            T09la2VQQ002SWtlYk1xSXJHakxZK2hDMDJRCnpqV0JWem9YM0lzU0g1cUozRnlJ
            MDZya29JM2QrOEFsTGQzY2M4VFNhY3cKLS0tIFZmeU03NlRDOERXdFFTM0lzY0dX
            V2ViNFNQZWEzTmF3cFM1MzFxL0VpZGsKyIXdgutRlT3PqlvdwZDE/A3x9OmdbD48
            AclO3RrIK2todr786JVB6TTg3gFKksAhMXa2/U7o6fE8Jl8EoFXh/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:m1bYi1Klh1CyP0hxc5jBNzibohoKVkuLxjZCe43rVu2jRnLbQ3cx9OHUtxCuLUMqfe3WC1xVJmWA6GxqcfpYf+kD29Fr248oIRv1ZR/inYxKiUJ8/0FjhZwgUdA97f5JFjyx+0p/kWQCnoO9iUfc699rz8Gd27zPnKRm6a13JmA=,iv:r4/hyNWED/tc7dXilFkQ9M16qFSA9XzJZTlInUPVBKE=,tag:/oE8hcZwIGdQts7S/IM2cw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
