apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    client_id: ENC[AES256_GCM,data:FlP2DyrsmAguUBHBXrwy+0k=,iv:t46N2O3X11Jk4loZ4Ka/LXunpT2052evGsuJMsjx8WY=,tag:9CTrm64+QgSM5FlrCbi9Jg==,type:str]
    client_secret: ENC[AES256_GCM,data:7iQ6aQRgxEXpj6wnAbu1AY/TY8a++UM5A5HfwiBYAzcJp4VA9RJFBE5UQFlMAmDJYgr5CqyJ9tr8/UXx2YQN,iv:6q+eRoTVL85/8soD6uRFFSyZG01eF3JGuK12a5EGtCQ=,tag:yvi84gY9BHx4m2S9P0Bjsw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmo0R3doQ0tvdThicGxE
            cm5IZlBUWGlMMmQvMzJxeW80cDJWN1BvMmtRCi9aSThjL1V0MlJJRnpteE14ZDE1
            ZVJrVFNERlVnRExsNFdqcTQ4U28vaWsKLS0tIEJZZGhFOUNKeHRvV2VodzZoT0pu
            ekhsd0ZUWmY4TEM3bFI5RXJweWp2czAK1ONZaYKJ509zbJk4zOx1PCYgC3dUa8MQ
            H+QF2aJT3/DkVMBqfDE9WtWCmx2ux8T8Aa4Scu9/LPr5TQkLM8Kjzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNCtaWDd6L3hZWnltU010
            QXU1OTFZL2xyWk5lSHJyaG52Y1RHM0tWWFFvCmw0bjNweWJ4NXpBQjM4U01xLzcx
            dXBkYW5aSGxLZ0JRbjZHRzZwdG11bG8KLS0tIFJpMzEvcTAzMFl3bi9IMlNkN3JH
            Zmk3R0NDNlBrN1lWZGFyMnJHVHFoTkkKn3DEbPVEyDDHz41tw5iCorCA42a585Sv
            jZuf2tOE8NjH2SofTt+kFxAgSSkNgjDo++5YCNsr+Lz9MMr4NF/yEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVnE3aTFqdVA5ZjgzYU9t
            RWRyc3U5UlJoY3dTYm1HblRjb1MwL3dwcHlrCk5CZ1NlQjJLK29OZkNFc3ozRytm
            WmZuSGM4MTA4dlNnN0NHVnVpOXVROVUKLS0tIFUrUkhISGEyZ25acEw3YkVVVDdQ
            Y1JrbTIzbEdOMjQ2TG1aaEROczRlVDQK/7QQG/YmNmPXB67rc9/Tq0Td2wTDCM/A
            ScR6CqekEsoQKbkgfvLAJVvXx9VtUxR+s13918befIVfr5CtQZAydg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ajhwZTVqczNhZjAyRVQz
            QWwvT0t2UnhHcW5VYWF1alBIRVhBbDFCUERzCk9KZ3UxRlJ1OTd6VEQxQUlMcFZZ
            aFI4eThiOVRaVXVvTEV1WlRKM0dzWjQKLS0tIElXWkpJa0MvaUNjcS83MzNod3Jz
            ZXlLeUFaL2pzZEM2QTRzMVF4VXdPbDgKpmELrt4zyT5Gp+h+SBF92K2wEG1tw1pf
            LgzTnW0qAPxgGOC8Bu2a66SGreeDERSQ89cicf3UtGi/Pl/PpbUNkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:ERDh/Y6kAZ5eK6hfbYWJU6bjG30PIxFLf9vWN4VGJnxX7MWuE7eyFcFxv29ktx+yC+rYF5leFLZD7TI3zBbdxxT1brlUMPTKQiTlgZ50wcG5XYqA2RIEhZE9HELGWO6Gyc0BlB47DS/ynBndHUrf4uM6nOMlzYMbvAwK7gt75cQ=,iv://1JCE8pIsfrKDAuWU/98YL8H7dNET3VWrEz/w53DoI=,tag:WAnLAKfN6OmhJZ8QNSc3og==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
