apiVersion: v1
kind: Secret
metadata:
    name: urlshortener-oidc
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:ioIfx7t3StfAe9fIVqmbj5+ONSc=,iv:0PHySWsTFXfxPOGeN86+Vd/3A8im3gJRr3T7IwDa+k8=,tag:dJJ1FE+vDC6VdaQlpF1BJw==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:7fsQ/XnoSpX7aKxuazJ2PDWuWMQND0cSjJQNt9RnIC2n1PuTExFkgw==,iv:nMMDCNQiXodT+w3+q/KuAVAIvZMfp4g7NYZYewTs878=,tag:9ZY2UZtKSRQpS9skCmNDqA==,type:str]
    SESSION_STATE: ENC[AES256_GCM,data:jluTiQ7K22Xa7A==,iv:erec2+Jq7eJKit4ePcjeRjH7XpeQvtvx+R4M9vhGUdM=,tag:zlNJG1lJjrzi5hrs9LKOGQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZmhlUmNEYXhTNjFYU1lB
            dU83R1hKWnEvcU1CME80U3pkN3luNW9DY3dNCmtObW9tT3A4VG9lcWt5UGNreG9s
            Q3hRbDJoVGdXdWc1TUlzM2x2S0hvd1kKLS0tIFFCUlREQ1hvd3pibUkwcDlOWFEz
            WndoZDVJVmwvKzJ1T3hLajZ2Nng3aHcK+KbdqyA0bYRCqVp35uCSompu0cnbyDUO
            ncorf8QgFAffzdfeVtCW0b6z0i1t3eOy6uycBOGLS/8qXYeewBvPGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFpJOXB4MTA5ZlpJamxP
            RnlnRVNDOTQxWXhnTVBERzIwZCtjV3A0SFM0CnVYUjhMakFDbmpzOHBKUHYzbEFr
            RE81Q0hsSXBCejVJOTJiZmd3QnFpSzQKLS0tIGo1RVc2ZXZzWHFwVXVWL0xtQ3pi
            d210Y0NoVUdQb3ozblN5dEZNT2hQUTAK17Rn7KE+d6Nqv0jfqTCK+O7/vHyFWhOk
            Wq39kXE5rE/Z4ECvJjg4PAolPAHFodFBNxhw4fd0iXueOzdZQAwkjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L3puTWZtOXdQeFlyampJ
            YTIzNjdpUlJnOHR1aDJSZFQ0NUh2VVgvWjNVCnptaGpRZGpVZ2FyWERnSUdna0RL
            Vjd4aFZNTnM2TnloQ1hsRE9KZzFVWEEKLS0tIG5vaDhYaDl3TTZ0d1Fwb1lOMTBm
            dm9Na2Z1VzRYSHJOb1NNNWJpMDJrM1EKpRkps2gLiw2uS//dGv+hJqDzHhob7PY6
            C1U6plRru3kosjNYQA6aDN2A1GowTiKKSWsTvfhSAohVlyJY6wUq/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaHBoaUxHazZyZ3BaNmV1
            Mjg2Zk1OdG5sUDBuQ3V0T0dBZWNPQm9HdndrCkgycW9xTGZrc08vRHhKQnVEWDlN
            VUNoT3FyalVpOFF4d3REVjVuL2YwTkEKLS0tIGxDNzlnZnBnaVBHUE5HY3hJR205
            c0M1MUo1ZHpuM0FtcFJ0VnNRWmxPK3MK6wBDC1ToaD4tSa9H1JNpDpG+Dp8TVY0/
            lltRM53kUHLqf8d9sgxdIRjWhJRLkAzISDOa6lWJk/maiDlndLbiTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:MZ4frOLRqho2SR3BVYaZ580/QJlo4h7YAOfiud92wkAoqNkywcEca03cvgVe6pE5clYxDosQOcBZBZ4LLSX6Zmgdcu4rh/e8l80ZIlunqHyDc6oCxoxbIhtbuXD+sTZODrT+F7eQjlrY/glhN06s0U+xYQP2nKWuPY2Pz7DjpnM=,iv:CQ2eqMQCNt82jTJpJ4D9/r9GUjQyuu9OigImm3MSWw0=,tag:H2fZSKNliVXTbmgbWcVbSw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
