apiVersion: v1
kind: Secret
metadata:
    name: urlshortener-oidc
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:kFj5oTgtfXfviPmWXX4mrSvOr2k=,iv:wSDscJE/ByrQjA7iUqlm65Uc1Ss3+1KgP9Ye0SB7aC4=,tag:hn7JHtRw9I95mg7rn9mqxQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:xn73I3CWn8adpXSsl4oIHCHPS0CMqIsKqG/9s/aqBQIhUb+e3HscRw==,iv:MDgvO+zpyZLkv6pCr/CzSKjgMZrluxVfDyLhUa+VCvc=,tag:m0E8IZa5at+Gpph825XdKQ==,type:str]
    SESSION_STATE: ENC[AES256_GCM,data:WNZohyyMIFz1sA==,iv:570A56H4x6d7sTAk7wIJcbNTMW2Zigl9pufZo/XmnTU=,tag:4SgTyKuNVMbBmlpXvmqd5Q==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S1hvbXlmbWM4bTBxak96
            cDkxcHNrazUzR0dhaFg4bEl1M3N4UXVoK1dZCm0rb2NFTXByOWRpSEdpYytiK2Js
            VlBtdHhjSUdVOXArdkZNM3BCaDNKOUUKLS0tIEQ4QmNSenU0V3NseVF5eU9mRjlP
            QXQ4a1VvNCtnZm9pZk4zK0s5SE9yakUKsyvSRRshwNwjugyJCzuwI2gsmn/qKGvW
            ignD8HXReZncRHj5qIGSQ7sPR01Sj1+s5Cu1MGhX5B6fXNm3ZaCruQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZjFFc2ZTdUx2OFpJZ3Jh
            RnN0VTBacFNGM08remYySTVJVERSVVJEc200CjQzSGJKUHZGVWlOQUFweHdyRGEr
            WjdHem5QU205VThHZHFtbDNtMGFsWjgKLS0tIFYvYXJ6eGxYUVZJcExxOHRjQXA1
            WEdFWExIQVhKUG45cGcwRDZFZnZ0bmMKn4MDwZCEebf4lDj5456cCUqASo3hsfO0
            xxhh3Q0AGvh/yODHH0bXKhJAPYWTrsh9H6allSk0XUT8KaCDG5mMeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQThsbHZLK2ZHSmc5Y3FV
            UDdYRkV4blY2R0ZkcGJxSElranpiVkZzblFVCnZVSkFrN3B1MVQ2VlhQZDJpNk1i
            bitOQW0zQ3JNSWpOM2VVK3J4ZDZrTU0KLS0tIEx1and1NzhMVlNlOXJnTFBYekZ3
            YTlqRWlpQlhWd1pIUjlQQWFSOGc2SDQKtvrHqsN3LpaVebX2nBslUFdDFBZBw8W7
            2GDy8pPELjKfv2yMUuCNdx+VHCJBKQj00Cvigu1NBU9Q373SbGYnDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:WPyQp0Tp4rXQDm4JE+Guyo5T+WjxaHG0qN1G7mzoE0jpEYDoE20erRjnpCgOpWFkeQs62vcL2kZfL0Z7f4PUKbowUd0f8Urods2tTSf0K0oa015HA7IEraFUyL4MIhTtmkYI51imBOpaDJJQvf1pKw4oIOMMmSUwnrK5pmrFrpw=,iv:xvPrEeaxP5xnmbkFgp5W+qTK6pnhLNYiBPzk1cAetMg=,tag:c/1kK8rXAaB8GRBGzKcztQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
