apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tunnel-hornberg-tls
  namespace: envoy-gateway-system
spec:
  secretName: tunnel-hornberg-tls
  dnsNames:
    - tunnel.kienzlers-world.de
    - tunnel-hornberg.de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
