{
 "title": "Urlshortener / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Shortlinks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_active{type=\"shortlink\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Redirects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_active{type=\"redirect\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls to short URLs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile urlshortener",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (gin_request_duration_bucket{container=\"urlshortener\"}))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "95th Percentile Dashboard",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (traces_spanmetrics_latency_bucket{service=\"urlshortener-ui\"})) * 1e3",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_request_duration_count{exported_service=\"urlshortener\"}[1m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Error rate (logs) per service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app) (rate({namespace=\"urlshortener\"} | json | level = `error` [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Distribution of shortlink calls",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shortlink Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (gin_request_duration_bucket{container=\"urlshortener\"})) * 1e3",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (gin_request_duration_bucket{container=\"urlshortener\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum (gin_request_duration_bucket{container=\"urlshortener\"}) / sum (gin_request_duration_count{container=\"urlshortener\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Dashboard Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (traces_spanmetrics_latency_bucket{service=\"urlshortener-ui\"})) * 1e3",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (traces_spanmetrics_latency_bucket{service=\"urlshortener-ui\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum (traces_spanmetrics_latency_bucket{service=\"urlshortener-ui\"}) / sum (traces_spanmetrics_latency_count{service=\"urlshortener-ui\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Shortlink/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(urlshortener_shortlink_invocation[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Calls per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum by (path) (increase(gin_request_duration_count{exported_service=\"urlshortener\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shortlinks over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}