apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    admin-password: ENC[AES256_GCM,data:bVM/dYRJaaqNK2QbWuBb0r4wXmbIVBY+gROpmtw=,iv:yZoTyy9VfEBoqmJtNSfR/84RN0AUrkfXBPMYOUb6EW8=,tag:EMkQsrzBr61CAx1QO2uDAg==,type:str]
    admin-user: ENC[AES256_GCM,data:04aa1UI=,iv:3uUV7Pj5onKL44WA/jjP0FUNHhL5eN1noCrQdLYMPZE=,tag:RFXK4/a6lXy4qexxVlnSeA==,type:str]
    ldap-toml: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMHBxNlRSV1dRUmxUY29p
            RkU5QVJ6MTRkWTJCQ2dSMXptdkNVdHFjOXlrCjNVUVhwWjRWYm5UamtCdFVGVGVx
            UWVmL1hQS2NDR1BTNEs0N29aaHVPdVkKLS0tIFA2RFBWZFBPVGp3N0JZNkpnanIy
            enBhbnUwM3JCYUhsanlZNDRTZzdiMVEK4SqnDCB9CnQrrJhmhll+quEYW5EdC6U6
            8bYouzWeo84bRlzeYww1YsxodDu/PPE4XygHKpoIzF6rAS+ArjJ3oA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ME9QTFdRRnY4UTd6UDlq
            ZkxQQzEvdEg2U3hYdXpnMC8xU3JZWW41VUZvCjQzMVRKY0RuSXFVeG94UUNpOFhx
            L3MrU2U0bkJ2UTk5dFhJWjBNRlBROG8KLS0tIDZPamJ6YmZnQkxJSXhxRGdBVTVv
            Tm5JbDFiRENNcFNpSXpHdWhsbTBXSHcKF8NfhzyNhe/p2gNbIJ8/rZq2HZbh+96k
            n64IVaXZco2f/wLunDswLY8gph1gcZJgHP1e3mWIeZ3Xwh5kldRT+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQlJHUnVyTDZISjdxcHRM
            ZEwzd2RLa1dCcWJIcWRMVDJLaEtvQTIzMW1VCkZVcjl3V2l0YkFPdGRVMGtTS2Fy
            Z1Nock9nSzh1U0VVL1l6c3E3RVVzY2MKLS0tIEZQak03ZFpwa1h6S3FoYXpheXJ0
            UktxbHcvVVgvZ3lYZlBoS3RleGRpeWcKJf8nGQ4pOi7FMpApHQpFhlKu6tCATfcq
            PvCyKnGl1O9H2dLI4wmR3OFWAtxxrbOf+8CzHCBq70kKWHYgyitgWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWUdvNlNKMFJGbXBvS0NK
            aEYxenhQNTgrMDRyczFXc3BUQlVCZVhmNG5FClV0b2xzMWp0WXJWMXRwdGNVeU5y
            YUZTRmszOFlGUkI4WlNwVGVNbDhqbkkKLS0tIFl5NzBEQmpMR0s4QVR5L3JWSTZt
            Znc3Y21yNk1USzhoWUhLQXRmeW5Wdk0KQNF6vffq+w7eQkGSkcurad2L8EHmQcpE
            VYOCIuPeTKo0gAFwsJDeMA2hKKMoHzilQ310PsMT4bjDK0bYWsWyuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:huBKhTXWZwKOIz4e4g9aGs5RR7uUXZAiTQkG7wpuXSrRIGUOwmapHboZ/oUYmN/WPkqZQZe5bQyWHqT+k4rJahpHq7gYBF/hriGLAO3Ie2QSF1OnoD5R1Kgmo91oDMMZfRYJPa7fgNxGYdG08ZxfB0wXC+bxZiNPTsf1NgoFnFU=,iv:TT/wYwyquNfX1JbBgvnyHm0UKOlKdBaVbBPVbbN72Bo=,tag:6ipPQ4lCBsw3fHCOV/4AXQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
