apiVersion: v1
kind: Secret
metadata:
    name: grafana-oncall
    namespace: observability
stringData:
    MIRAGE_SECRET_KEY: ENC[AES256_GCM,data:SE0qC658743FqATo6Isql2attxntTFGQItHLtuRyaKaefpabHxgvnxnJ7llxK90NQUxh8gje,iv:JuQQ9Bp8Y6X1e0YsfCLOYvp+tJdfPzspwlLXyNmhLv4=,tag:HXMH5hvY3oKXhYsWVECjZA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:YdUmPdeCk4YTaEj3ws+6fkPkcQ++igvjK5QdqMJi6PrLZibckLZTHUtoPlEyUgu8EqLUhV2T,iv:wRnEEVXvcDkkq/0nQoDV8yuYMpbbUrwOQ3YhZ2W8hGM=,tag:ygQmkr211s58qdIiUwQPIg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OWdsNStvemYzVzJJNktE
            cFVWRGhnVkJHY3dDS3NoOUdtWko0TmQ2Tm0wCnFMWEtiTHBLNU1leXgrUW92U2dO
            azJiVDVmdVJnV2JiQzJzR1h3cEdUQ1EKLS0tIGI0M0h3ZG5lMG14Yzg1bmFWL1lQ
            TGxZcWxva2hTSnEwMVkrVUdocjM0UlEK/RpVFAW1bKxfe1yQ5jeZy91GY6526bvY
            QqhXbqYC3efLjTY1X5VLz6VldWdXzpiHi2U5TJYhsLosxAEkcye8OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTHB4NTBHcTErUk5IYkx6
            WVhhZTlURk4xRmpqMEJtK2U3S1h5bjA0alFBCmZ4NTdHRTQrRmc2NUJncFpzOVFR
            TU9EeWNZMXozY292YlZUMFlqYTk5TEUKLS0tIEdZcldWa0w4aTY1YXJzREphaUpJ
            SDFFaFRQOW9EMnFYdFNQdUNLK2RoRTQKXhJGH0gSXuAv6wBi/FIMo4ZMejrIQ3Ri
            4lyh9rm7RwuEJ5tP9PRL9Tn42HEkUpvPzd7ZKMvojW+m50iv2Pux2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNUFudEIrSHVidkVtdFhX
            TndkeXhIbXp2Y2JxbU5PdGhqUHlWSGRyYVJvCklSVWJncDRkUWdqdW1QNTY1S3Ni
            Zm55TW0yU2ZTV0kwY0pheFZOUXFFTEUKLS0tIEpBWFhmZkdaQkt2eFcwU0l6Q2I5
            dFg3NXRvK2dmR3h4U1krVGlOdDVvNVkK+Z6eR7DUA4G6UhFO/CZXVk+brCWhmZlJ
            e9fb+AjcuV4DV8WkyNg4SMBAaI+0QeOjveP/u5lhtXtHpc2UbJpGEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicWpMS1plUVhpbDUwdUIw
            RlJXL2c1U2pCblIxT3U4ejlpaWNlY0gxbXlrCnhjbmpQdFJMZlkvaUd0V1dvUnpj
            T2lkall5VWI5elZEa2NWbHJESjdxc0kKLS0tIC9Xek5DMlJJSFlQdjdFSHBJNDhP
            VTZnQVZjbUh0SzBoT0l2QVZxazFCMmMKFtAt5j9WyOAoiYn3VO3+LZoapPFAkJNq
            rL88mN8icXIU8F23xzjVhJaxYwjW99SnXpCApmIBopMR7qqYws4zpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:wXkcyYwpQ9LzGz1S1k9fUZqgDy3wSB+7+wD77uS0vZRmdPPWYdl6uU7yNn4BBrC5a7N5h9fOm7V4leU57LrEbOAMGUF2X5DHcgZe/0cdoYDr8Q3rs/zg0ezkkB7axvoZZyUe9v5vQvO+TaqiDhWtTxWyGcYS9vJ4GGsB7navjg0=,iv:S/AkS/DaO6O6dSjxhJKTO5v++YH02Q5wItNU7YkE7TI=,tag:HDB4hLT5KbPtUnRSDcuWJQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
