apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: helm-secrets
    namespace: argocd
stringData:
    age_private_key: ENC[AES256_GCM,data:ZJU61/gx4B0rz+kRLQ+I65vWPoaw42LYCwk7CFyMtYeeys2GmgF0zbdWbN9pFKWRnNf5cWFN7cLevkFfT1zBWFs+CIUPbsrYPqI=,iv:09ARz+q63/qPEHtRo+ZiQvzmXIPVfjrQYQAufDvM8Bk=,tag:1pqQkTbP7qKiOv1f90YecA==,type:str]
    age_public_key: ENC[AES256_GCM,data:1jzkARXyodoDaJ6cV6DIdR0mjWg6atyZEYdvHOf5FjpUTuX3BVymPeGFberwkCtwlRhjcaUjQPr2XphHReM=,iv:6LDSF0dCyFdWbPFKiURsAr4WzF99oyAGtgIJOzLEVgE=,tag:TpAyYU2kizLpgN6iodNGAQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c1QwcmFDdVVCRnIvamh0
            NlhlSmRPdkwyTmg5eWYzTjRVc2pGaUlZZ1hVCm1lbSt6eFA5TEpHN1Vpak84YS9K
            NjAxaHFFSEVLbWI4OFBrT3VrVERCdVEKLS0tIHhwYVFZTkpYdTJuQThCWWEzak15
            RWV3S0tLd0hMTWZnUndrditRNjBDTGsK65iJd4NBWvu0F3kOg/jjl8SBrj0fKjQ3
            cn0y6dvyp26jm4hNxWvBL8dagVOrDJi/GzbwF1wkmqbtGU6oubpUDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSWpjZHNBYXhnVlgweHdJ
            aXp3dG50MS9NVEVjdTQ2ZUFqbzUyZVByVHpZClAyZTh6YjU3YktxaVlOU3Q4d3Jz
            U3JyUkdUZnIzYTFxVXlHc3pLaTl6elUKLS0tIENhRU1DRFR3VVBBZUFKTXh3bTZq
            Z0NCTkdBZjZaOUVRZW9ZeFdlL3BXTlEKZC2eEc3qCRzhOuypUEEJZ92FUrX4tlPT
            475WU3XD3mspTsh9XxQnNtShIL1HiJX+yoz88JRcO+Y8n1PFmEaRqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaFF6ZUc4VkRRNDZBa1Fl
            QWtmblF1L1d4TVFSamtFaFJxSDhMZDVjMFEwCmdmSllDRXZ2OXYwSDhXRFVmYlNT
            UXFWN1ppOEtKMklqVHlYbDVIcmdkcGMKLS0tIFlvWU16NGdMUkJkbldvOUR0OHZE
            QjNCQ3ZjTWVjTWNiekhlQWVSclNuTEkK6SyUc2L1d/tAQPeHbtrb8hhiN3NYKqIw
            mhJfp8xwMI0M3v7BZtAZODl07uaDVlkcufSe2DOKHkH/+kjdzqOQFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ2w0OFBYemxoOGQxSU93
            Y0RVOUxLQlZWZ1ljK3FxQlo1anVZYlJIY0VnClNUdU51YWw3OUFlOW5QN1kwTXZv
            b0RCdFNFT3Rjb1dOY1lZZXpYRm1IMTgKLS0tIFdzS2l4L2o1S2EyV2pOS215ZjN2
            ZDJKRlgxQy9UZlhITHNFcGFVUHRpb1UKStUsdPf+WbAfvKRPzTtW+FPUsi7NpiMi
            iuJR8KsVO52IArXmmnFepNkO5hT3wFK2/tWsgpyQzSlqa5IDkWXbvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:FGFSGuliM3DG1Ia9Syz3+pgEjOIvinYpgDglQRLSyav49hysA/k8LfhshiqCdjWgX5GRxEoD1xWj6TRNZ4pFnXiiEmLFc0tH5sMrWwqdrIjEmylAVO1z/7fJoXxhKAI5OAruCIBJboQTJnfjEQFKb+hAYuw0xFkRq+NV0fhU5cs=,iv:es0GvO/32S6qaSE6+w+qJCM7fR/glpKMmIwPr61bsd0=,tag:7ykXQoy8KoWyI44I7lm15w==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
