apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: helm-secrets
    namespace: argocd
stringData:
    age_private_key: ENC[AES256_GCM,data:yD9YmIsCuUCSHFhFnsVX2+6yauX2lS2SyxJBr3kxNsI7sqMYd/8hBcpIp0EaX9nqY0cR2vItKFkoralXp8fBGeko/FQzCvBeTCg=,iv:7ZSzNJpuLYgJVCkx/kpz0kZ7mwIJDaIJ0HGDjAnnYJk=,tag:rD9lcsIaG2oI/0jcPv8B7Q==,type:str]
    age_public_key: ENC[AES256_GCM,data:6zqmJ2uED8KFRiRsjhXgZpShqb8rumngRC5RQMG++eERIEyzrqUF0HNly+yRRjv7Sj83EnQ/SBdclAVZR8I=,iv:3+lvgkXdxAASv6oZHHf5Rrh8uZl14wgKqQKG8WYifmg=,tag:pJwHek30VLDy6lDooP/MVg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERHFTYnhQQStmd2RDYVBo
            SzJhYzNFOTIrNDJSRE52alllOUVVYkE2V3hJClJubnhXdzBhUnh3dXhOV1Y2eTFI
            NzFPeXd3VXRQSS9aTkpkdWVvZlVmcE0KLS0tIGl5S3VNQmR6WldTNzRnNEFTS0E5
            OVlwZk5DS3V4QkFqa01CTTJxQnJ5L1kKK6eojHM7ChxPVAAaSZmXh1X6/M2NV47G
            E+TwBZuWuENdA34GtG8JpHsSnFDLuXi515e5LC1m3fAOm+GY1cgmAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTGsxaEpib3ozT2ZJY2U5
            WnRwWVZvTGQyNlJXU2RLeTZrVjNPY1hGdFJRClYwUUxMMDFaS2dVR0ZndTFJbHU3
            VU02TmN2bDZWb3g2cSs3d3BmVHVPSnMKLS0tIHl4cS9nZlRMcUt0bzgzY0R4U3dw
            SXpCdDd1ZHg1UGJPNnRkeURQYi9ialEKXz/cMmN+J2iUZZl5aXnmQqRsmP+oQBr+
            +n/BMWYZNkGXlI8lpjwTUK29FSOCAMfXoJz2MZOglvqMMP2921qv2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVA5cTRDRzlTaFJ4dkVp
            VWhndHJwbWlwdlhMODFtOEFsbVJ5M0VtQ2c0CkIwMWt1MUlpK3FhYzdIeWtubDVQ
            d3NnVzIvcVJKclNjeW1MdkFGREFHdjAKLS0tIDJRR0RodEVsaGdocFRITmtyYkdR
            RndJaEFRYzBNWHg1Snl0Q0VLdWVJbTQK3APMhN5JweVuxA9UGmp9l/aVa2F8rWJ8
            Ps6MzFqYoFGZ091SjAfuCfetGh6nPAU5ZWOaOOqKCJkp3SKVSk4IUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc29RUjdIYk9wRStKVjhv
            QVN0Nit2TkdMZW1Ia3BNanBQaHJ5SG9tOG1BCklpMkJsOWU1R3k1NVlzK3JLUUJh
            bElaQkFORG9iSk9Vb0hyMmhrb2RvVlUKLS0tIFF0Q2pCYjZDUUdYYUdITDJ1Zmd1
            dFZaSVoxS2UwTHRIRm1GZHQ2NHhSN0kKby3lzQGPGILHw+DY5XgmzzNXUjTrr8pJ
            SsgndXADi8FKvh6TBbDSNKmb2T3Wv8fa5NpqQZgPYad54HyX7Wl9Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T19:48:17Z"
    mac: ENC[AES256_GCM,data:Uj9T41Y0bH70kWUqDQZzpHx2sM5nt3UJ38sQOps4emlB8NiIECU1jPjzm6hUrPQxDnEkmHtFVgtQHEcMnxdcb+jSO7OJYWmKWYD7svBbs5hhIWCrmjlmhSN2HcIiLwNIxyGZjML5LIOxNODvceprYtSI5gsiDgPdIkP2PEtG1BA=,iv:OqS2zPlPlwNUrFIoTYESXFikSZBL1XSInomTRlEc0kA=,tag:sKH36MQ1z+vWFtENuPP1Ag==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
