apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token
stringData:
    api-token: ENC[AES256_GCM,data:FroYwIZAseXsYVVcp7ACs4zHphdab5izMiZ5LW6G2iqo5vvdkHLVOA==,iv:6/eRS8MyXDOBMiL6SQGSr4B2L2jfzsgf5eauqi9+bvw=,tag:OAAY2dpJuhUAMWVflEh+bg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RUhENGgrRVZEa29sNWdZ
            WFlhNHoxZGJXUDZ1cWxxL3JXUGNBRHNVdUhVClNlM2lqVjBCQURYcXAvVXNiWCtK
            QjR3S1l3QTR2R2ozOSsrOUlHc0ptbXMKLS0tIFIyTlBMNUJGb1VnRm9zL1pzSDVK
            ME1HRFRWMmlDYzQyMUN2UW5qU3dDUE0KSVxeFTdUr0L7HnJpnmtFjJZXXa1PF6zs
            +0icb3/JmY/P6kTAwRnQAqmPdSMZKTpTauZv3ly5JcOibGUWDqq4Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UVIrYlBQRDg5NUUzRGx3
            OXo1ZlZUODNWdkRjU204NmE2UVBSTkJhMnpjCk1oaTJnYjhQRWdUaXk4NWxIZmVq
            VURUcmw3clVVdWJ3YXNFd2tmWm9sdzgKLS0tIGhXenVGTXJCRDBnWmFrV25NUHhs
            QzZHLyswc1dtQUVwUFBwTS9LY0FmMDAKrNK3QUHUWcUSjuMcbEU7DfI+HkIFwOZT
            Z32ORvXQAqM8L1nR9Vpt6rz/QMyib4Q0Ds64ev4tWEgRuccgOxfe8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c2Y0RDI1cjQzb3VwS1Ew
            TEw1UUxEOHlQWnAvMDVwUnZGSnU5b1BYd0QwClNzZWVNem9STzBCQ3BVZ2drdXVx
            eXNNK2lDQmtoMGlyeHNlaDZCVUdOWjgKLS0tIEZZZ0U4dG40NU9ndGJVWEticFUy
            L1E2TDlVZHVtaTMvR0xyY2JHNzNOMDgKu3IhPoissnbOP0ZOVkLGo/9pC5G4WUWK
            rOF93o240xxJWIrW09k5HdQQ7DduNTepn+nvsEX3vyJWWV+Wrcm6sA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOEZ3Z3MyQ1BBSnN4emZO
            cGp0VTVERHIrUmlSL3BsTXoyeGVzYUpiMG5jCkVLQjFMSEV5M2VKSUZQcWNSeDI2
            WWxYZ3RDQnI1cTB3NUdrRjZwejk0NzgKLS0tIEZYemNEVFR3R1Zjd0VPSlk3OGc1
            MnpSRktBeVdRSlhzUXhvOXgzdDVJWHcKsy1x8cyzlvNe78VUbdmrJRsOa/q1/p2g
            X4xijSjVkwAV/1DSu0RC72Uo2PSM4vsDQqa8ui/SRyBzyCcrKWezmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:6i66V17U4cizuwm52ljmwhEKL9kSCs//ZzGThQiGo96oIy9GOTIkUCqQb+Sc9MEmMe/hMtAdAp/P4dgMIDVjY+uW4B4llHijQK3IzyW8RyZuR7oVtQJuGCe2P9zLuQJkM87/2qBlY8n91j4YRNcO1lb9ULjzej2GytaFs7LrWWU=,iv:mZG0c77QY6CHZkzKQJQl8CAijKESnV0rRtxy5UCx834=,tag:6RmJR7R1HT3CyyrWO5D6Ug==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
