global:
    resolve_timeout: 5m
receivers:
    - name: blackhole
    - name: grafana_oncall
      webhook_configs:
        - url: ENC[AES256_GCM,data:76SmdPv7NzVf3Igj1cgpcDBurRKap2LFmTuZ4J9fjz9cYptvG9d020YnthpMWsDq3v6qoewQdw8G/ZDB50P4WuydFp5qVu2eZILKX9KWfmfMuogrEZo2aL7wLwlvwmfBrGTQvcjKZvg=,iv:NMXV+JbJ+AhairIrQCjamG1O4KtusqSF+Fu4zqyn6zA=,tag:fBII0Mdw3BynHDWQzoyPGg==,type:str]
          send_resolved: true
    - name: robusta
      webhook_configs:
        - url: ENC[AES256_GCM,data:RmPMnp0is96oZxirjBLKk437DffK4oGpoSxW8jYNtUmaFNB3eKhRYnsoRiev/cmO0vvquetYBe7G9g==,iv:FiX9jg3+rykK1rmV7xZ8H7smkf40LTug8OI7ZyAFNkI=,tag:94YBkvpav64WoY69ZDDnpw==,type:str]
          send_resolved: true
route:
    receiver: grafana_oncall
    routes:
        - receiver: blackhole
          continue: false
          matchers:
            - alertname = InfoInhibitor
            - alertname = etcdHighNumberOfFailedGRPCRequests
        - receiver: grafana_oncall
          group_by:
            - alertname
            - job
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
          continue: true
          matchers:
            - severity =~ ".*"
        - receiver: robusta
          group_by:
            - '...'
          group_wait: 1s
          group_interval: 1s
          matchers:
            - severity =~ ".*"
          repeat_interval: 4h
          continue: true
templates:
    - /etc/alertmanager/config/*.tmpl
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK29zVWRZdWhwQllWeGhH
            YUlQT1hNN2s0cm9vWEN5cEM0NTk2TW5WMmhjCkkraDgvaGl5Z1JuSk5RaWIvcW5T
            dlpPUnVGY2ZERGVkdmlCMGpUWC9PakEKLS0tIGwrbXNKRlNCRkY4N3JWZTJLTVZx
            cXkvMldBcEdqVlg2MDJoZnkyZTVVOU0KR60w/7SLPPgH83VoZ1X1CjeN7ncvr7Xq
            HG82OJ8wsy09oNaR5T2DqMxaEX8nrk2bmBnsGmguaZcJgkFqBcsz3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydFNVMEZyaDRFczVmV01k
            WUQ1UnVKaTZZN2xIeDB2cmdkM2cyYmtWVUY4CkNFTStza2hvU0VsQWVEWEUxSk9p
            WnpUZmorcDdtYnB4NkJkQ0NsOEs0VDgKLS0tIEFGaW81SndCTUJXTElSTVF6eUxu
            NEJPckMzR1ZMamp6cWRzSzg5Qm1hb2cKMZY9KywHdGvZ0q/jdCNFHE+ZckrJZmtG
            ck/thmSTBcBpXUr2MZEM4NAMNctI7TkUZbuiUPFoMwb36pw/02HY/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZjVsZ0lPK0dHTkdnVXNi
            T21BcEtQT295RzI0UEVZQXdMckRMZFgzV0RZCnNXdDZMTjB6dUN3TDlndVM4K0lv
            QnJ3eU94YTMyeVhDZWQxbWVtYjNTc2cKLS0tIEMrVU5IbG81azV1clFWQU1XNm15
            NzN2SktpeUJXcVNhcWhGVkVOWEJSUTAK6RAd3j6+dp9odOoYoFy12JDBjHoEVBEy
            vaONW+0QFkaHJAj1NhXtCBVMQ48pz+8xK+si5hidrRusqB9dJRIqfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVmdaWlhTdmxXYUV5Wmt6
            M3puMWhNYjZFTnFib09pS1ZScHdYdE5NQ0JZClFJQllIUFpWNUloQXpGU1NNSHN6
            eFpOMjFJL1pKTUlJQzQ0b2dLRHFvY00KLS0tIGttTzhNQWU1MEFVRG1PdnNVT09R
            S3FWWTR4YVVDZGhrUnlNMHE4K2Voc1UKD1UaQmgQZ43otOevwgXGeEOwrTEmlI8x
            onhGuYORpGag3DqcSVKHxVfkULMdTWfLPr3ff1Fl8CBY82jJwrPr+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T19:48:17Z"
    mac: ENC[AES256_GCM,data:H89BD6bp0LKHCq9pJWiKORjKWnNf3pIXAEw5ay+WbPsIh6/LxsBUKp9rYLywsFVgt8ccv9QGmva/v0Zc1baWoYnhjvOeGvjZv9/1oaUebcUsa+VOVeu3c1mjje/kpE0X+Embke3UZVzDmJjIw9F5ssFC0djGiXuVQmBH/0BKt3w=,iv:DeI/KN9mfRKjZ5isq9lcpQRflgn84ce4kOPfL+CrFYg=,tag:Pv/TE/HVrNL14eRI7ItA2g==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
