apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hcloud-exporter
    namespace: hcloud-exporter
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: ENC[AES256_GCM,data:8lsRtD3Kt73dwlJlczF5zHizKddvtP309vuf3Qy5IVSn31hK8tP2pFHRDo1L0Z4BPPMyTAilZ9ZXSwAP3QlmBg==,iv:fyr3BjkJPje5dhmbeLm3/vhv1OH/ROXgKlT5pPTyJmQ=,tag:caEvFDt3Qhj/OfZ9P8tnNw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUE5JOTcrUWY3MkVMZTVR
            WWNsTmhZMUJxZFlaM0ovUmxXdks5UjRQSEdRCi9kUE1GMU4rVGhqeUt4eXhKaFgx
            ZWdrRzY5Y0ZNNXZSQUFuOG5BQmE3ancKLS0tIHFVbHhaYklpaXYzbElYbFJ4VXNr
            OWR6UXRNSjFXV1B3UlpuSC9paXRia2sKsIxuIm8SgzppoD+bvIsHcLU5QRNQU4SQ
            c7lRpUSJ8JbNHqBvcvV1Ox93VF7WwEHx4gQrG7QuH4fByajn5k8jig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUamxJWS9ySW5TSDhyQzNn
            V3VZbkpHZFkya0lUNDZEa1lZNXpLNmhzZlhNCmQ5anQwQW5jdlJyclE4ZUJjUDJw
            cXhnbUR4QkxpeGRBRWkzaUgxZHpGVVUKLS0tIFF5NEoyRXNZZ1dwNGxUT1RrcGJT
            OTdMV1JPZzBtaU5MUlpORE4rN3hZd00Kl6Vf50KccP5fuRmqdomckp/n/mD9iKZY
            j1vi3rk/sVGxu51n1QVkv823o7rOcLGwoyRJGPsuVkkyayg9e4Egtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dEZkcStrd01mZ1F2bC90
            SXZxNUNCUjRSSnBLY3BEdnNOVzdLNEVjZ3dzCjZoWTJINkhqaXViSjYrYzE0c3hN
            dzE4ZTJ1TytQMG5hSTlaQTdjdlhNbkEKLS0tIE14RjRxQmdFTHQrd3o2WVFZU1ZG
            azBWUVRnSVplenVKRzFvQjFyS05HOHMKIT7fxz2QQs4PIiwkiUVeznWDd0hkM9fD
            7oQ2vodwMZrRSjB+0AUtRWADHHE7jVNOntvDTl1sBAkIX4t0j6wp0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQUhvVWc1VHREd2J3anEv
            MGJXTUNxbmgxVUpKbmJOQUt6aTEzc2V2V2gwClBETnZUcjJ1N2VWdHpBenpPTFh2
            WUZzR1hiSXF5cFpXRzkxQVBVVXNqcVEKLS0tIEk1KzlqRzFOYmI0eGJxSlJmVTVM
            OHpwTzZsY2V6NW1JbTEvSjZaYUVVVDQKckSlkJrwjJP1f65U+eetp/bLUEpLoW9O
            ZbUvB3CylBA1GCTlnWLV2iKRMKwHZITRGCbPjtjFy/qOsTNVfpI+Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:i0+ck8ZMefKvfBuM4uFgI/t7g8z/VuTsc59QA5LmbSulm0suPEbfcW+C5/w5AiagHQO4rpcyc2UV7UKVjdgHIpR+aa3jbkbQHA5NL/aY8p87+z54tdFhFs0iMP2S3QuUqhOw9z7267PbX6yP3NlWKRK44yg1CXkMH4eGPaAnK0I=,iv:vpz0ktS+Dx42+XU/lKCWrt/5RgKbIAADOzvMzkXarb0=,tag:2q/n4RLu6N9Ub5wa7soeIQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
