apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hcloud-exporter
    namespace: hcloud-exporter
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: ENC[AES256_GCM,data:iOHw9cdCM8y2ChoAhCnF+pK3BNMf7Z7itRzxkn5dJ2b6D44MKhSmcE8MlFeRGNk20AaMQpMlqRmEQ+J2CLzAtQ==,iv:94zIE9DAi7QE40uRPVNLlLi8f58jkk0pFbsjYSC+h8o=,tag:FFqyNzUaQZ26Y74HELOjEA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTjNreGR4bnRXU2tEMFN2
            K2FCNVZRMkVMQzNuWU51TjdMSUVtdk8zNUJvCnpKQlRObytNQVhGLzFad1VsUmkx
            RkxiVG8rNlUwa3Fjbjhyb3IvYmorVkEKLS0tIHZqY1JFRTl2VFdOTElwS1hJZk9U
            b2w3NnlXenVmNnFhL3RvLzFBbm9qeW8KJk3M6/xYrpwaNry8kIm+X8y7tbXm8/Fq
            /zE6t31jYjV8cnBW/OgBB3zVaSUnBdHI5dbgvOb3C9LK3FZlToic9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdlh4QytOUWFINTI0SHZW
            MDNXYmZPRHIzNnB1SUQyY1pnMWxmMm1Na21VCklJQ1hTV2pqTmRxNGMvNFhxdGV3
            QWplRHpIejRjVm5jUmJSeFU1WVdyTDgKLS0tIExSL2kyS1FKZmJaVytyRUhaOE1X
            Nm4rWWpzMlRMZHJoK1ludGxwMEpZU1EKkT7Gv0tGG228xGF8qnBronSROc5aG1Qi
            cJYZzuhfzq23DEa2NgG7rd0xDP91YySkY/ky6ydslhsjFWM2o4T7sA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbkZnNlpGSWpuekh1ZE9G
            VVhSZ09kbXJyRDlzOWk1TmNadjBKWUtSZ3h3Ck1WcmowRTM3V0xoWHhQQVJPZHlW
            L0VWc2R1Mk1MNWE1eXU1dUxxOWJTd2cKLS0tIFI2L0IwWlh5NGZTNmM3b3pxcFYx
            NWJlNEVxVHlYWUVIUHVjTVFOU2x0bEkKh4oZLDdRR9iEC1XHnC5da+ibO/91JSWh
            BdAPYm3W2xLF3pTLJBIzE2mepq2Ub1mlBRPnCXTR5q29lP0GjjJnWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:wjr5jFAvyWJOzvZw3r5QuejNmnANdr4100qvCha7/zL46vdAhqmC1/64Hp3NGYfPkAZk5EFBy+AKFLQfzMLglxeT1ygmPmS6Zuxg3Ofb11/w57NRF+NDDtkrqBCml/T5+qelYiLPqErg7cW93ATtDilADiHfaQbNXenKjPg+CEY=,iv:iBqAiL/dS8E2blR9pHxNUb1Hn5g7LCzJp9F0mXk3dqE=,tag:egMV9c3Bs42+9dUlj2BFUg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
