apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    client_id: ENC[AES256_GCM,data:iGR4k2GahG7wh5ARtXBszC4=,iv:I6WnAC0Irv14bsxztRTHVxqhsw+PoxVmYJGsOYDAN8U=,tag:Ol438heF/nxyUgDOXaz6pA==,type:str]
    client_secret: ENC[AES256_GCM,data:Vx/9S95/cF0HWHrwqPEDu3hILViAHCh1VkdjxaVYNHqn2qTFiVpDj8I6s+3UY7lDua6U2Z1Ir0F9QEfDkcRC,iv:osLHvup/Ty1OqwheGXTpicgv1RaQVdf0mH0XAi36d9c=,tag:pcM+c0RWlMipbSj6O9f5Zg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveUNSTUd1bHBiRHo5TmNv
            RVlIZVdjSjlaVEVZbHBmb0lGSjRleWpTbDNNClhjZlJPZjNIbUVvZzdDVmpINVRM
            U2hhbVhTSGhvTk9hNENYWlc2RnlvbnMKLS0tIHREYjVLQStXckxzU2ZTMGprb2pF
            S21GMGhXVkdmbTYrT1lXSmFhV0tSVWcKuc7uYNxJF9p5IHXy14aGaK0kwlr1bXRR
            qiGmpv+zs/Hj+v/l8LP1v3lIkpgPheyZsYfBUAp2Y6rVhAih6gOwhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMVlkcW9GeUtEcFR1bmRv
            Ui90WWpxZzVRZVdhU2F6SElHMHV1Z2JLN1dvCmNXMFkzc0pHRkhiNU5Hdm9lY21l
            M2FNSEhZRW41a0ZTV29BL0ttVThreUkKLS0tIC9KVm13ZWRJaVZzRkRmc2FZSU4r
            eWRYdUpReTZXZlllZHpEVk55QURQMncKPKAfk3HMOAr2Y0jlaPE/+2HQlVpPoMqY
            Xg0rW2Hv4HgrvvhBYZukaCRQIFQbR07/RPsNAOq5HfWmr+NegBVqKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVGd1dURvRVVMTFdSK3Jp
            SW44YTZHZ0pna2hUeEFjZDZML3NSVzN3TjEwCmRPcXROZ2ZGb0JmRG1hR2t1WTY1
            MmJDWnk0MjEyUmdOTWZDcThGa0ZjVVkKLS0tIDZEaE9hV0VzSVhrNFZJNDlacWhi
            QmZqYURlVkk2ZkNQc3JZcW4xMTF3VXcKwc6Di64SsMEJzFN60yFghsjyvN7QEL+t
            /CMhxhEzwelroXnqVom7sTjXljWw8YBa1+tlMbcheRgFGeAKcp8p0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:cUBEG5D00iiHWPzERou7EIHHe/Hozt2c+mOA7ML5f4pWKd826bJ4nFHRfOC0J/rKKfFapp+CodXRkhFBc8SnliDNL+Onv4ierBqesrevy9aCxaCljLv3x8o1PRHcQ3QWI7N6U6RiDFX8JtFdUoggF5aYVk/L1LFDeNXVMbYBoNs=,iv:FVrH9CPFQPNkp6Bj3LIIeyGrCg4xSWNpq+iUxbMNUTU=,tag:/AWHtidOR/G7IDg+FSwadg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
