apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-redis
    namespace: argocd
stringData:
    auth: ENC[AES256_GCM,data:zDqCP9iM7GCDjH69tkj2ZP/z26M9XEhG,iv:oHDAg02OYAw+x75AwTHgfruT5nR4Oy2K5FukX3iuFGw=,tag:zeQqiNva1i5RvAT05gPdRw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR0ZYSmZ1SktwK3Y3Rjds
            b2RNWExZbTdISWNkODZzZ0d0dHdoQS9UeEJ3CkpUZGVFOXBqUjZpYzdRdjFGNXZt
            bnVqdTBmWHBKWEsvVllHRGV3aFR3ZFEKLS0tIHUwOTdOM0FpcUdycTV2MlZDUkdm
            MlhKT3ZVQ0haWmh3K1hYcEVnOTk3QTQKt7o7uug11bVym+RJ8hPiqn6nL6PNCfE7
            y7IQ76S0plDH7zbbXYbNa/3ODZNOc8hvkY07Q5YZlVVI7+aXgAbGJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ3BEZmRnNnJIVVNmcFha
            RVR2MWpiOWRKdmZ1NUgyVTYySlBMRk5BeGpRCi9Oa3pWblRCdkUxWXUvbUdLbHJH
            Rmh6U1A0MExZVWJQWUttVHY3ODVhSncKLS0tIGpyblN1S0RZaDR6T2IwVVhBOU9r
            OUdvVmVTL01rSHZTZldmSXYxZ0lHZmsKCbsXxR2zw04RY5gj10HUiubccs/sUBjz
            RPE9/7u4cvc59roIyp5jcClYvp9eqhKOxpXIJL3hDtYyPH4QuFoUBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ2ZndHdVZDdtM2ZKTVFu
            ak44QjczM2N5cllrZXl5dzgxanJybHZITTA0CjF0YjlPOGx4OHdVWndDYjVaVEsx
            MXozcWJVNi9YOW9TWlBpWUVDTldLaXcKLS0tIEN5QUM1dW1FckJ5WUhuMDhmZVRt
            SUdtRG5ZNlgvNGhjQzhJeXhZbktwd0UKRZvv7SpkLRyjqCUFCcpYQt3N0Vr0zkBP
            jXybVb46xT+ZZSvsb/76JTlp429WlQVci8FR59a2rPa7rsTuvogurA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdFdrWFA3VEVNaVNUSW82
            clp4Znd1endWVlFjbWQ5Z0V6TzQvdWI2NWt3CkhxZmJoTWFuQmwwYkVDRkZvcXgz
            U2dZS2dGb2tNWW14cDFPMjd2MFFjNTAKLS0tICtHaGswdFNJbGZDRmk5dThoRnlr
            Q0VzdEVrcmsza0g1bFBYb2gvL0V6VmcKHbErUl7YEhU3lOwccIfmkKpPPtwTw/wH
            ents4hcEZj3xcd6Yv7xMQNEBEJE4VknjcKSFbciRdwAIy4w2CC8MTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:Zuz4oTNYeLfTnnft3Bxps9/8LPo56HifRoPg3TO5AZC/ubqsN1c+lSwdYx7MXg1zGCgMD2eS/oAIox0tUdwYIV+SB4pcvA3ImQlQc9qSThgHXGmsbxNskj91bdq4TH7JMFeoMTZ6b+IAX+lqgNq2weHR+kOop5uEHZWILcz6Vpg=,iv:41+0HWKa5zPo0BTcPEY9WUZ3pL6AYmp4eyzP1FA0U4w=,tag:efzzOcITNSkG7caeYHY44A==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
