apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-redis
    namespace: argocd
stringData:
    auth: ENC[AES256_GCM,data:iPC+GDyx79qAJ/6+Eso6gzmljet1G1Cv,iv:pmrxnOcyKJBVw3ljx8xN7g5t2YinDAzvVWYRrh6vSMc=,tag:2AsodYKxrCLuMcMPsBn1oQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWFNIcXZ1aEIrdEYvaUl4
            STRoL1hpbkRNM3E2Umc4bG96T2xJZTNEbW1ZCk9NMGorMVNZcENLNURnck1vdC9C
            Z2R0WWZkb3FUcldoUGtjQXNmSnhNWlUKLS0tIGF3VEY3KzR1V0l1bmpjRm9sUjNr
            WVNFRERHWHdsRTlNQ2FlNUNrck1tSnMKoeir0jMXlzKe3SKHiToeth8V48zninW0
            41nfTlUKqBuqn9ny7OH4XXyLJJ32m4AZUHZaIeKrf9Y5Co21Ey1Czw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WG1uRHN5eDkyOVlWZ3Rl
            MnNYR3VWL1FWbzdEMDRIVWpEQ2lGNzA3SldZCm9HcStTeExyZWVWZk03VHdQMjdW
            K3pNdjU0Z0tQbzFjcmdXRkpuL1hQU2sKLS0tIFhNWEt3MWdUTHRiV1hpTmEwWW5I
            Q2pGYlY4QTZuM1dFeFhNak53dmU0eFUKQd7xUXvzgUO6rEDrtY3w2W9QRKaDKpmI
            KdyRmUC1KbwE9bsPp5eG0p8pvA8OOj0K4fMfVodJrzYZuLXoV77UHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRFVZVWt5Sk4rMWplOW1k
            UHhFNTlzQWx0WUtDdXZpV2RVZlcxeHVZT1Y0CnN5UGNCLzRVblVaVFU2Z3VOd0Yy
            Kzh5cjB5aE9HK2VoUFo0RUZWNGNLTTgKLS0tIDBjNldiM2xBMzFIdEJmY2RLb2h0
            OHdTc0lwVVA0ejUwUFlqYlJhaFNic2MKAUE+p2oku3gsgeyl3VVZmWynQr2ECiah
            1lLbleQxajjyJ1kt7A5JVM6RESTteJeYlT3+Eom5F//ofTgEebwGEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:bRHHtGkCutOpT3C8FRnVJD4roZfJuQvS7BWBg/Z/FX2q2+jowF3wTIc8iDT+NqciMnUaySLzSvs1R+QvjDdmOv0ooqfh1JEooGh7Vp4PdHox3iogcyCiIiE2rhA/aZpIEjoLCKgYzErtC80qLOqrJdIM350JPc6ICo14BOX9R8c=,iv:9JeoPK8HQXKk1ocHJq/fRPWBnpz4aMx88FxjoPN+y8c=,tag:/bxAa4xlddZ70GxXSjEQ7g==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
