apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: helm-secrets
    namespace: argocd
stringData:
    age_private_key: ENC[AES256_GCM,data:O7PgiVIcW6fCH3KGIYYJ/pG2VqslSwiP7lqNkval9yGAqbIqkDs93nzZ1SGTyKSfqPwaCcra1l+k4oCE1VvKhTqu8WnPR6zSJt8=,iv:R4BT1q2xGaCb5tAI9lV4hilC0VF4svBIObn97XkA02Q=,tag:6IhSC4RbCsLspf38fjCoEg==,type:str]
    age_public_key: ENC[AES256_GCM,data:HbfcBai5CzTP8Bp924cV6i30kkX6NEM+ybmwxWa9jYaCXO8zflgdUtndlGx4VRp4taA78qTf5VSAjanURsU=,iv:iJ8yPb8pAwx7bx7rbY6Wq8IA+vjIxxMWmC2K1u9ujq8=,tag:ikbuKWMg8n1qSTUAszzwfg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZN2JnaVU2cUpDM21xcWJa
            RTN6YW9kZ2lEZlZ3WWdPL2JFbGxLNHNFOXhFClJMcnRjTnJ3U0lXeUFVbTc4bDZS
            dXZTWGVjWitLZjUzZ3VTekc5eXZJSE0KLS0tIFRJSC9IaUMxY2IvdkpyaUI2cWJN
            R0phYUpwMHFWbEdPVWJRZ1hCTDY0eXcKKRvm4GoZZ3koQ/fWKXvT02StvzgBV5CK
            QrDPVIWVEmU3Ix7BA+0L4bEfBTyrvnsClRONmBc+yk6PrLOfmbn2pA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWclRNQWM0amluL0t1UE41
            SnQ2YkZkdis2NHJiUDE3YVZGeEV0ZkpJOXpNCmlzempHUkxKTnU1bU5mQlF0MVk4
            TkM1Z1h5U3hRWnByZXFBTFQxOHp1bDQKLS0tIG9HZFJIU1ZMS0t0ZXdvQng0WUd4
            UWEvVVllSnNzRUpGbmlNTkJpWjhVUVUKhvGKdynQ6AAYn74OZUPaWEcjYcCbPtlh
            sjgeLFQlWYcznNuWSRufC9BKYsjkT9ERph7NUrT1CMElAyxPKnfDAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WU5HV3NHeU50WEUrUTRC
            K0lldDEyclprM2pyUUVBdEY5VGNIMEpnenowCncreDFBWWY1THZITjhnMXhWVU5r
            d0NvOTI5NlBQN2JDaFVMYU5WQ2JKSHMKLS0tIGxzYzE5VGZxc2pzNnBwTnA1SytR
            bEc5dUl3TXRyRUoxT3hUZm1tUEl2OU0KaOuG8vrIOwQg4HqCoDrg6s+L24AasdhW
            hRgDFSkMVmu2028eGSs6XJg4Lcl58II7pNUFvluk8fa1eVEPe3VgxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:pUy4LzOHS9cvIdqC9s4grITJoOu97awPopriqqwHmOAGHrHIJe+zxZTgdcraFdUHq3g37yDS3uk605B7u8vJQolzIRjg3mRGTo+11/mZdWjTyT0OewbjEtz1E3AeMY8KFWJjfTLxotysWpeqbzXqCfLnT7DCJxWTtCPhP9Qz8Nc=,iv:/7PE74ZQgV2eBqBkRYpqJ5HqI7RnWFBkrYokrs/HvoU=,tag:rhfkAFOOnq49ZK/mK2T1Lw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
