apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: helm-secrets
    namespace: argocd
stringData:
    age_private_key: ENC[AES256_GCM,data:v0DeVa6mrrFfWqfXhrwmv8NID90158sQSYroexHqbH6kPj6Qwy3S4VFfNe3KS9rFoZoPLRUp4jroBeeK0x0pCjAnggU6qqB8nQ0=,iv:CiByP67k+4c3340/XGipKa5PfK4VFTls6SEGpbjsofE=,tag:bk5Vvkdlo7hTwtIWEGrdbA==,type:str]
    age_public_key: ENC[AES256_GCM,data:Wnn8g6WAZgLcG/6w8G3bVVpPHMPExuOUEQUKjPj5SNQXWmXoAT/64AwZseu5fXSqTdl8ShFkRGo4IzK5iGo=,iv:NPgFfsE/AMG/mPQxwE16gnBs230rxizLX9uV1AlGvds=,tag:Coyai1ProCDnSAjQC7fuCA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVmVwcFRRSUNTYVdPZkU3
            aHR2OEVzNHJrZTQyOW44TWVEUENyRXlMWkVnClJtOEEvRkdXMFVyeW1vMzAxMm5I
            ejBvRm14T3VOeDFzRnNHMXhiSlRLRFUKLS0tIDRZRzBIamN5Qzh6SG4vbmtzcCtG
            dU1lb01vRktjVTBEWmU5cVFQcndVVm8K54vErg6D43LJ+Yuw6A2UgsK5H16WByxV
            ZjuqTeeIdwgpNBp8GFyZmWNo/FSoTjickOfwmWZwy8s69y5pBnfb2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM2hvbHJTL1JUelJjNVpD
            SjZEV0M1ZExhYUo2ZXNteHN3RmxkQWFvQm00ClJDUklJb1J4NTRBR01xRVVBRm8r
            Wm5EOGlFTDAvdUF3MDNBcERzdjR5Y0EKLS0tIHdoT0tSVTloWXVBaEdINVJiRHpH
            RGNGN0tySXVvanVIUjFmUDFDTXVkd28Kj48YJqdH+tzq8INsxo/SyNq6JlpZbcQu
            r5ZLbdOY+btY4sQgB9BmSqPq/4/3R07YVjX7BGhzP/tlK/ZAZSM7LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYm10dW9QcDNJaVpiMERa
            dVV1TW9ncWhrVm91dG9kSFpDeGhacHoxSGpBClBMWnNCc3BNZDRlTWQ4bm9Ub2Yy
            RGZ2RDNBcGdLWmFoQnUvNkJ3alFtcFEKLS0tIE56NEs3eTBUTkxEZkdtdGtMOWpG
            a3VpdlNIWC9UTmx1U0YvdjdsOTJ4dHcKVNIYJztl/Ch2iRW3HH3o+l73XxfN6+ix
            GF92D4s3GmDQDJsEDuePL55jQVSJF7tWhgTNsUbn4rNFo6m0xCN2OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTUpzVWxxWDhVQk1BNENT
            TFl5RSsvKzk0eUVPb1UrZUZDZE5XQVR4YW5JCk9MTXFFZ0dPOVU3bHdNMWdpWkxZ
            ZWdrZDJySFBCczlvaE9tR3NYZ0tlam8KLS0tIGhTaVg3aFRtRHJ1Tlc0RTd4ZXdG
            OXFETmVLNUlrNFM1dWlZZk01cGIvSkkKs4msZa4Er2vZHS5Tu7gEniO6oz2fytLo
            NzuwmHOcsbY/f4X7y/6NnH43s7AP1Q7Xh3/QuXpiHjJwygX6ONwxqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:vYBzRFAQlQ1UAW09zpJ22RQNiSZcMcQc60kLR6ZG8+qxEPZRX+4uzQTV/BaF5nRMYoBmJaklXmP8yyeUwunq6cG+kGsI6TD9vkVjyUBwiWa6SyytlXA9kiGOYeKaI7FYj6CstsDQkpineIydjx3EzbyoVGGzQXhrfWA8eduSFLI=,iv:MG53/i2rgGfClZjKs6x0jd8OU8R8LfU6pDf5G93yduU=,tag:yUvDiq98dIqgf8RjOGnuGA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
