global:
    resolve_timeout: 5m
receivers:
    - name: blackhole
    - name: grafana_oncall
      webhook_configs:
        - url: ENC[AES256_GCM,data:7/rC0TTU3UQ+H6l0ixTpreycG/LT4d13d71Ypc7VMhiELUkZm1lAXYn53Ew0XQknOdgy/yPXVNTwHZscaUqNazbZg8OdKN/mN4Wmk0yK+gqi9m20WUxPwju2ZmWfqDwrTBAHehe/FZ8=,iv:tpHTugJL8bkGQ7L/d6RVViU2jBf2u3pXZpb+3Lk8WbU=,tag:oijK87ksXs35YaQ3W0+9nA==,type:str]
          send_resolved: true
    - name: robusta
      webhook_configs:
        - url: ENC[AES256_GCM,data:UW8ij+HWPhRaW7QgtPWHPE779hf03iSvUfwbk6gAOzY1705qUCMtQs66pzSPiuOeGq+usBq33pRqTw==,iv:MHIrXYxNguvjIRfAzIHPptg9Sxhu5kD3VuJ0eQMk/hs=,tag:W0H/Oe+6Mt+VBMNpmnffHQ==,type:str]
          send_resolved: true
route:
    receiver: grafana_oncall
    routes:
        - receiver: blackhole
          continue: false
          matchers:
            - alertname = InfoInhibitor
            - alertname = etcdHighNumberOfFailedGRPCRequests
        - receiver: grafana_oncall
          group_by:
            - alertname
            - job
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
          continue: true
          matchers:
            - severity =~ ".*"
        - receiver: robusta
          group_by:
            - '...'
          group_wait: 1s
          group_interval: 1s
          matchers:
            - severity =~ ".*"
          repeat_interval: 4h
          continue: true
templates:
    - /etc/alertmanager/config/*.tmpl
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcUR4SytCVzBjVmZ0eHJS
            RTNVWUlQWE0zcC9tdDdkdXNoSFdhZVB4VjJrCjR6QUdxTndsaG1ZajJIR1p5Q205
            UmFkZWNiangzbGpSM0o1eWhBNEZZdHcKLS0tIGM3a2RUNjhoZlVpQUU0b2ZJUzVv
            Y3BqV2x1b0VTdUN2WG1TTlpHeFNmeWsKVPNCHTyT1hyAvKWpba5t4mti23ZWa0yq
            9/7QI74i1retq2Nj7/OP09SOS4kGaC8wfqoz5nLZ1kqkwQZFiiwWUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWHhCZGZ1eW9ySjFPaDJF
            U2IrR2RuMzd2eTgwam5TenBxZmltSVBXZUJZCnBaajk1QmpaMllEVE92VnJnVTF0
            RS8xK2RqcXJQQUVxNnlPWldTZEtiZGMKLS0tIGlaSmdlVDUrNGd1cG5WWnJ4WGZL
            V2M2Ym53UG5QRzdHMm5sdlhFZzF4bWcK2AmNrabKGxF46Ikkq/Zct/cM1iJJvr0m
            UH41MJqKIjOdegaKGBp1PbiHTwzDayrJiG0CjEYnHAg+lb3a4hu6gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV2J0QlROb21pK0dRVkhq
            WnZnSVhrV1ROeGJLMjYwNlk3ZGVvUFdvbkVJClpXLzJRS1VlYTZYaU14YzJGTWFR
            MHlRUkZKQm1ldk9ROGorRWo5c3d2RlUKLS0tIGJpbFpud2Flb0ZMS3J4UXlHY2Jt
            T1BvV0dFQXZITlA0Q1l0cy9nN21CM1kKo2bspVXVYD0W+yk9cKekPJRew2dP8ljR
            CuOsuATohiUzgw3vm/ScVvyG+12l1budoSE11nQ77ernN9clgO6gew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:Au7iOUMRSCbzbU6Kq0X/2BO/JX3eHlCksVh+UOpHghgD569D0Jd/rGwZ5YqJ2t/CfLtvbPVBp5w9iWl9jNMREWpUIh/23e+BWS8y7ABpGJ2MTSl7oD5UFG851v+7iF7ezAsgwJHCFJIYt3ChtNi+EhFsaM3eQrlDNxSIH6Wtsas=,iv:x0dcEF6wNZwj2plBameMRYSVMjz55B7XfQDUv9eQxgg=,tag:xQXV05OU1ZBnc/dPCsI8og==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
