global:
    resolve_timeout: 5m
receivers:
    - name: blackhole
    - name: grafana_oncall
      webhook_configs:
        - url: ENC[AES256_GCM,data:hboKlw7td23LXmOGeFwAssNOML16OSr2RcrmiVZFjynuLMj1ICpYNe6ixoMWoh8CJKZqx7islesSRO5o3SVs2u9HJ2BVTZ32jR24WKTzIk5Y8pSa53xxyrXTBXaWaCDX28k7UU/udX4=,iv:wc1ImX780A+AIZ+sS4fb0qADUUC4mM6CO1MTCnO/BX8=,tag:Kmi4M3OkkfuQ98248nS+Og==,type:str]
          send_resolved: true
    - name: robusta
      webhook_configs:
        - url: ENC[AES256_GCM,data:0lD6ULXxks4+X4FLA/km+jb2bNLLQK9eMd18HRre4gsmGYKoQZ6bxODU5BWFwVhHCQi1nIknUBEZHg==,iv:Y8K5wfe681wApURoKqNLTtzzYFk3iDTpUGBAxSem2Lo=,tag:aFn7SX9eM/UxvUJMYYi/MA==,type:str]
          send_resolved: true
route:
    receiver: grafana_oncall
    routes:
        - receiver: blackhole
          continue: false
          matchers:
            - alertname = InfoInhibitor
            - alertname = etcdHighNumberOfFailedGRPCRequests
        - receiver: grafana_oncall
          group_by:
            - alertname
            - job
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
          continue: true
          matchers:
            - severity =~ ".*"
        - receiver: robusta
          group_by:
            - '...'
          group_wait: 1s
          group_interval: 1s
          matchers:
            - severity =~ ".*"
          repeat_interval: 4h
          continue: true
templates:
    - /etc/alertmanager/config/*.tmpl
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya2lRQWlXZ1U3cm1YdXR0
            ZS9yS2RHSE9LSEdnTTNzRHJXK3FlK3NweEFFCnk1dU1Ka0p5NDI5RmNJMWsrbE5h
            YXFyOVFXcWNZQWQ1TzZBemJwUXg5aVEKLS0tIDcvMnRLLzNTemt1bm4wNUloQTNw
            K2xVWlg3RkV2UE9vdUczWERmSEpxYlUKZQ23lXpBGolysYV76r+ULKvNToB8KPzL
            /TOVUiwoFR9kwqe+Ce1zWK1wpzNN/0QbJiFmeTKdx43hCJsxaVTkvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dTdRdEJHTVZ4blhKNFB1
            aHIrWVJVUlQ4MUJPMG5uL2pKeEdVaUVjZWs4CnpsczFHZmVZZ21GVGZIZFEwWTdG
            YVlVZi9XWHNxM1A5VzByQVRDb1NnN0kKLS0tIFArU3BBcTZOZUFnZWFSQkhnUXVP
            MG0yRVgzQU9vOFAxeEE4ZWkyVW5BR2cK/zhHne+u75q/HmdcstrKmElVfVKpkQFK
            mYj7Wh5AX6wySAD8dor19ytAe9Er5TdPcyzHazVAK66tMnJYaN2m6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTGQzTitYeTVhem41RnM3
            NThMOWJRNy8vaTNyZmNMR3ZtMEVZK2QwQlhJCjhhall3ZHRmc3pLcWxvVzBpZytx
            Nk9jZDBlQUVqSms4ODB2TWFqaW5vaG8KLS0tIDhxbG1ZQkhZN2hDUjNNR29Bbjhx
            KysvYW85dnhmN0NWRlRERVFZSXBzNUkKqL8qThcoeksJx+IFTIotJFKY1v4/QpWr
            P88XA53yCSB82/K24fQAy1bO40EnGaYN39jLnj59j0rNpg5vCw1Z6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY09pQkFTSEhORldzeDlo
            dGRRemdEdEE5OVp1S2pUYVlpQ1htSytDQ0ZvCjFXcC9FSGVVRFUvZExxR3huQXUw
            UU91dEphd253bGN4dXROMXd1MGdVbXMKLS0tIDhmZjB6VEYzTWF6M2lkMkwvUjc1
            Uzhwbkx5OEo3ZVRKdkRkazNXQ0VZNVEKfyQaiNKHN8Inx41IbvwRKd/sv2P3WlvI
            VoXvOZ2WFvRC300LgN+Ijzfz5tGPJpAg9y/qvb+T7vQeHsz0MiCEHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:e5vkLkScSJ4Tq/gKS5/iw+At3FoDQTreoCT9IwEx4WHZFnaqCOEm0+WnKy3oUWU7ngu7vbIhPk2nU/Lh9xvttPNQrlR/OHj2+qMOgpfyUmSlhgueQadC7MHq33GOwHdQFkY1DXUzG4p1E35URuTqPX/+A0tKZZIJDASl0AKByh4=,iv:xourEb0WGF3fNugoahg96+Y+VUr+Fo0T5ivQbLeoId0=,tag:KRrXwNVPr+UX5nk5q1sdVA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
