apiVersion: v1
kind: Secret
metadata:
    name: mimir-s3-secret
stringData:
    #ENC[AES256_GCM,data:Zeu+i3xytSdzaxTJ5qu7cJyYWZtnYOo=,iv:3iaqxv8tyZwoMJpCEGIMSbySP8Pve7fzWz+bbpPkr6Y=,tag:ontt22KT+WhmNupuocWNAg==,type:comment]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:1XC880mBvAD8lszlAvNH2MN5wB+9nnpJlA==,iv:9RaLt3Vnf/6UCOSXe8tULPPawNHLTJpKOWOa9KgWQoo=,tag:vwjgUUA9Bv2r/cqebcYLjw==,type:str]
    #ENC[AES256_GCM,data:YCV82om2bHID5Y6fkDBM0An8niIu6im/phqKixs=,iv:vpHllaiUuZ//KUkwk3bI4Hq0EUKstnU+4yRcWhiY+Ho=,tag:evDRA0r5rtSUWCI19QP3Rg==,type:comment]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:Ac0LAWu54FQ/ZplrRJpNKrwTl2W+6gRJBOO1phVBHQ==,iv:z7SYpKuPPE6mBTp6zjSbFxERLRyhJl0KSi51HYyB7Eg=,tag:K3ACMIMdPotg207iX3RkFg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzODFPWk1tb0pnNm1meFo3
            LzBKS2dSZGxoTWg1MkhvOVBpYXViQjcwZG1nCmZNQXFOV1JPK05nMm1SMXVNVEJU
            TUtDL2xjenhzS3FreWoxSmpMM2EzOVUKLS0tIFJyaCs0MWNmb2NLb1ZmMUp0MlBm
            ZWNGdnloUXl5SFhOYlNpTEZIK1FnRzAKg43ijPWNdMisprX1L928i6Bc/pmdL8tj
            38mAMCyT54ms15YIFldbFQY677or1EgSyINakmgxgOAUUo38VBzNmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQkJMbTdwVDkyWEQxRGd1
            WHYzRnZrWmd6VmtrU25zbHBhUXUvZkNUUGljCm5kbXlzMzdKdTBVT2pQblBOQXEv
            NlEvL2pmTkxIS3VPb3orTHlXeVdDb1UKLS0tIDBNQjBBNlZrZENtK25MUFFnZVYz
            N1RvLzVTWVkvcHg1UHVSbDBNSGNTNXcK09m3pWpVbfl9cA/gsScqdiZBDfjK7qhZ
            oEB/gsUGX1/cLjXrlvvzevs7E8SC0/loOKxet2aT2rwxPOqpCiz8Pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENXdLVWhQNVkyWEVkdTNn
            aTd6a2RiSXpKaVJvMTNaN01uNEdRYnJ2WVN3CjdMZkJna3NOQzB6Z1IrNnd5TFpa
            cXpoc1dHMDY2M3RzNkpsN05Xc1JnY2sKLS0tIFdSbnVsakpNNjRBb1RJNnl0Tjdj
            UHZweWxLQnBDZGpiV3p6T3QyaGt0L1UKMRa7BMhe31uXUSf9w5lCIVBUBjCRbL15
            Sm+/SL7jvnIB78IOd/gelMFavDUFbt+x1tavIu4+rQh6x3cTWXURUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:+Er/WNlTMsLUcHiZc4LsKmG0Po4WhQVDaaNXNfNPCQgAfKxSQG70fCBvvSfHMMCz+kSMcvY/VD+kWOhqAgEjIkre1eekScY4kjn01pxt2rq9Uw05DDicQ/H5fN1GwC4Ze+IcHYNDhgbI1oWjfgiGroXcYucnxCUrD7q2tg0id5A=,iv:yDyFXcS3XaH58peQ/qy/TCavIaSnvRmGdunbUg68E6g=,tag:u8BFIMqe2aLRRLnX3d/+3w==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
