apiVersion: v1
kind: Secret
metadata:
    name: mimir-s3-secret
stringData:
    #ENC[AES256_GCM,data:UIzdz0ClprxOMa3WFSWavxLHw9BsQug=,iv:0fjZhFrY0NNM/TElBBIyGKSbqxPxwPu6uixIaR9fhVw=,tag:vLQLmRvVaBjGQEQa3D4ugA==,type:comment]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:iXOzhAyQmJI5XMhoo4UxPZpr9v8LGWLFEg==,iv:S5b0AlzZuHDCqDXzU/ah8rO5eDaQXybWOCLyOLuFktM=,tag:ZHO3S6wdYJ2tUB1ItLEsOA==,type:str]
    #ENC[AES256_GCM,data:VGM2on/esjgqXGY/Yp2h083AmfCJyRTtdVd+ZAg=,iv:YKwrTIbH98xO0gUJAxlSrqOcWkvMQZjrJCznUiv+7TA=,tag:V1PPWUvOH1RszdQd6fpd+g==,type:comment]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:ZhyYLwuFsX4W0XzMywwZCKCmj7ex+XFigQZ9ATp4DQ==,iv:sQbwxs4MauqRx4EaUmy114IiqxruFprKeF7uSjAYVXE=,tag:NRxkJr7Cr7H5kHTyPI4N5w==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeHhOLzFPMEJoUHlTaFlI
            LzRHOThXbzMrVFEwUVprRkkzS00yQWpNVFg0CkZmaWE5MHgzalhFcnM3TjJkb2h6
            a3hxSjdZV05ybGxxamF2aTRZckdaSncKLS0tIG9KNHZxUk5ZTnJzQWZBbVFhbC82
            NW5WK0hvRE1yaFl4Q0ZDRlcvTWZMajQKIWEJfnfDU9t8+PthNXQ1+C6xgofQlyYa
            FQnFo46vGn9cVNf2qT49NfZ5/wlC3q0urDlLeGwkP8XzpZGFUu4qzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWWJaNDlGK2Q3RUVPdklQ
            NkFwanJ2ZDRxdkMxYjkyVUJsaThJQlp5VWdNClBSVXZqcXB4ak1LdWNaOE5pNUU0
            V1FyZ2RyVW85TkdvOFJya050SmZJMG8KLS0tIEtaMzQ0YzFyTFZvWFlWbEVPVmQ1
            MWI5bmJTaXBidkZWWStUMnJUMmZMTFkKUtzNDN584yrNRivXnsw1FfcZ/kQ9crzu
            +c63ahhr4Ennj4uGdGmrgPEL5dJoyYkP5CHMGDAYWPegJ5SEnadiww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L1ViakpUdVhINE5jaGJk
            QnRna2lyOTF5TVpka3FXU3dzalJMQk52YVNVCnVmM1NWZEVKdExDSUtKSGJpdzBY
            Sjl4d1NQdm9YaU9iVDJjVEczbmJSVTQKLS0tIEZhSm02N3Bad1k3eWR3bjU0aWhR
            NzE3Zi9aQURLUUNzNTFiNzJJcWQ2T1EKko7uVXJIrNj5AZXvEEpy7FXALBCaFf4G
            p3+rBTQOC6DpioBDGd8ldfY17bv5lyoW85x9v3GD1vJzHqiKxV9KXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YWlVQVdsK1Z0TlVuamV4
            TlduOFBpTTZvTU95K0pZSVBoWjB3UDF3QUNjCkVnT3h6U0RPckZpNkdYZ2p5Vk5E
            bStMZ0hMNHlsWGJ1VDMrYi85Q21BWUEKLS0tIHhFVXZxdmc4a3hSR0J5cGhWcExz
            ZGJwMDlXdVlabzFrRXRuYWZVUUN6UlEKp2bJqtcQCbvhpa05UrJ9cQKt2OPzZ4UO
            6T9xSi2ifNOhBDMgt0PQBVwFA+8P0g0m7vWJmEPgc00Dk9h5v52aFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:GZCPdVwRmQT0DUehtKG5AF8OAMR4pQxAaApI+tEQahI/1sCE2YSlhaf7R7aqU7tNk4UiBcX3/1s3lbnshij0DetuiRxoQI/LPYvuh2sxR9mI2LwPhKgX0wmFTe84Ax1pbM0qN+iGZiw7UmJCY+Fm+fgYC+/0tNLx5yR5xiIDDmA=,iv:Lzb1YpVTl9syOnz69/DEia0baUsO1VwHHrB1gIiHgQw=,tag:nsL+ZCatkpt5HhHfyq7Q3g==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
