apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-redis
    namespace: argocd
stringData:
    auth: ENC[AES256_GCM,data:zPkH2OSaHz+Ua7i/mqM8sF2MHmrrM3W8,iv:WsNx1geVPFb276o+mdW59X5FzMYjqasfXYyKxB4+h4A=,tag:HaI7JhEQ1rEGH5DXB1pMeQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPank3RnN4WlZmb1JZZ1RI
            RW5WQTJ4dlczUEp5ajRndDljOEROaTVzQ1d3CllBc3g3cDV1RHM3K2RWOGF2WktF
            T3A5WG5OY2Nla2diOFlFRVZvTEtwZ00KLS0tIGpBSi9wcHI0bG4yWURqYzJadjVY
            dzlSbEJZdGVDV0xNQnRmQy9NUmk3WWcKzbzqr1BR+uwZoz7y6mzWL0K5K9JWh2pw
            JK2IFXDyuoW9iUVX24su+nWyEBFK9UY4gnjWA/ISl4hvL9/5FZaDDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbWFFcXFLMC90UWdJQjdp
            MjV0eXhGcE9NT2RqOG5YbWRIWTN1OXZ6dURrCncyZjZQZEhYRldlVFJhdE9Bc0pQ
            NXpBSWUyZkZLNUQ3d3FpaHVCM3Y2MGsKLS0tIHdPTGtvZGFPY1lLOVM1eUNnbUxR
            ZkE2WXNMN0ZWMDZJRzN5NW1wbEllTjgKkp3d6fpfygHSR4VDnI5oOHz+wLOgEUkA
            cANt7SMoDy7jT2uZVNlGj3QHfbg1s/t2YuZCMHQOscrrWzNuR2HIpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SUxMdXRnbG40TFBxSUJj
            TmtvdHJOM2d3VHFWTkpxMnBTTVNuSnVHYUhRClVwNjhFbE9jb2V2ZWJrY3BXTUF3
            bTM2Y3lsT3ZHbU1MdDJPaFl4NVptL0UKLS0tIHNka0lFRzBHQmtsTnRKWCsrOE9G
            RmR4SThBcTdFbUNCNmdnbEV1dkx0dGsKzgWjrPtCbhng4rfZ9Hc3CXrP5jxt9mrM
            cX5dg4tiJ7cH+4KYKRHBjxD++p5aQQwMCaYNzHC0vhxgrtdLfPGEwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUzErZ0dzUWZmd2JHNnAr
            Mkl4Sy9keFN6RitKd0NSaFlGdkw2cXhpdUJjCnZHOFA2RkFEcjg4R1NTWGZYM3Bw
            ZktXeEdOeWcrclJDbHBnYU92NzlacDQKLS0tIG5vSzZxSjcvZEhiZTRkR0JQZ3FK
            TFo5c25uTXF1Y3FOZlVpNnRNVzZId1UKL+OR4FjztSUu7fama6E6npD+OLSZpzjz
            Y22FFJJNB1B6xU33FQadynk/rseiI2c66ZoEYQw8/6MlkMBc/eoqFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T19:48:17Z"
    mac: ENC[AES256_GCM,data:j6Z/cZ7Va8HFhDykk5BvpOXQqKNyBQyj8x9Z7uvuL5SOw4RDC/KnDfIk/GuTRvAI/VyfzdGQNmF4xpFKKiSSZ17up9/n0VkORfyEZuxeMshgtzi3f3sGLN+AJxesxcOaZPlXohCIKnzNn3AJcTmigyY9pDpX+gvDrnjwHW796pc=,iv:hW3VWWWTMh9fEtjMZbPRAvqP6qJZUjec5TXbOx1ICHQ=,tag:Rws3jsya3fs29K7zh65NFw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
