apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    tailscale.clientID: ENC[AES256_GCM,data:H7mq4g1S4sqi2wyNrMve/J6HNJWYu750aHxovSv5QMs=,iv:AlRdUbx3GQUPXmLWo3zb16V6pHNmiTuTK6MJReNaZvA=,tag:yLNV2Mkq20VbROmRolKh5g==,type:str]
    tailscale.clientSecret: ENC[AES256_GCM,data:8RFwIyNIW4cs0SKjgIRCQbNcGSSLyGGCpFYFcCvzH9XkrBAo96mDpev0D69q7cIkebIbI5fT3N0v9IMX8hZBAA==,iv:+Z6Kdo+LRXA5L2y33dPmN2JQGJ5h9UNmdeAliGwKTtk=,tag:zuqkrQio7MKUwohqFK+iuA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxall5V1JNTmJlMGJ3SVBX
            bDY0WURSNWN1MGhvcUtpTTNOa3lTUmJxUW5RClFTY2xTMTVpaldram9oejU4QW9j
            dUlLZVZ2LzNJVGlyL0kxUVFKYUh6QlkKLS0tIFAyd1dyVXNUMkYxYUc3YzNOOUFj
            NFpEaU1PZmFBM3BkTFArcGxPS01FUEUKFO8tsncwJmTosFHLgZk1+KXP8XFDNkEh
            ekTVe+QyaADx9fdRtOWxwJmFETuu6Sw2W/Ban1RqRbD785UJrCEkAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc3ZGenF2Tm41SVRWaE9x
            RGEvaHI1TVZQejdZZ0ZLaC82a0cyY1RleUhJCjc3aUFjcUpJYTIxYWQrOHlnSERn
            dGdUenlaR0d0K20zTnRjTmtneENCNkUKLS0tIDFmaWU0VDJqd04xUHpQYmJJR2R2
            eGRFSUh6TEZTRHNDR2l1Q0o3YWh4ZlEKRV8FBzTr8K4BZHphHsgYoxtdty+E4DwD
            GsRD67m8W0dWV3BcnQ++uJdJ1dTsbk7UxSx/SvH72wBz4ct8wvGpcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVGdEYS9GWEJIWlJpS2hP
            R1hVT0RiRmNxSlpjVHBWV3pLRm1aempUbVJBCmp4V0dPR2c2UDJqT0ZFbDFJNjZG
            Y3JEU0ZSMHNVbFlkcWR2TEVLY0RwOUkKLS0tIDZOUVkxWnNsMUdKVmlhYXczclFC
            YzNXMy9VTVJvYVhaS1AvQmZvN0d6ZHcK6EL6Rg0E99IMiE21HJc4zQ8XVaesIvQM
            1xZa3f7cDTlfUtWtQbZAdzNUcAKULMPQ31rcCUdux2VyL7xXz9Rl6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN1UySnUxblVYTncrcUto
            WlRIV00wNVUvWjNlalhQUVlTcWo1amR3YkZRCnBWa2NBcTJEKzl0emdkaTZzYTJx
            L0tYb2t2M3JpRi9LMDNVNmM1RXZxRUkKLS0tIFlIaUxxWnIzUUhHSGtLZitEd0Zt
            T0l1dEs4V2pFRnJIRVlqSVZlajlTdDgKSUaoSd3lXekz51EiANokTDk9PrAkucl2
            NW+TMQtG8w46HJuyLeuYhpnPR2lETB7+9ayfiCV0nnCrLYntYC1YRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T13:24:36Z"
    mac: ENC[AES256_GCM,data:T1rTRKt5Pv0QAM7EHkh6rRppL3Fi+/Vl2gHE9y7JPH0GR16EBNB7IoI+lScLGZQVQRMNs41iaTOxL4tj76246/IP0hBo5l+DOKrbdr8wxLMGX3K3+meKDOrVoJReAv6k0Wd6QzqXWWBxsjrIntonpkpeJB3MKI7mzRn1j3r4sag=,iv:fIu1P0wUq4uz13BsZ7i94AVFO0NtuAG0nIGDszMKujU=,tag:nfBg65zxk5DL9Jk2nlXN3w==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
