apiVersion: v1
kind: Secret
metadata:
    name: tka-tailscale
    namespace: tka-system
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:sAlzzbKlFg9hZ3MYXL9ZyhGq76TLwjdInBk6GF2Mq+On6TvvNPsxsCRQV/dFkYAlbXqNv+pfT7ytFmVfHg==,iv:tADTYJKj0dGrzqRAAH4HcnBYdTlUSvRbJkLLzEkXFHU=,tag:d5NFi4HzRZf/0BRVzd+tAQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYODVzZVp6bTRxQjM1bSt1
            elpmVEI3a0FyUjYyNG5QWmxqZjN6NCtpSVc0ClJnSHlESmNpd0tmYWxRTHBZbVY2
            UFdWcDVRVERtZnUvQlF6bDAxbXMrUHMKLS0tIG0xWkdGZ1JPQXl6LyszU1ZWdUpz
            UmU0TEMxNWFTbFBDRmxTcUJQNS9rNVEKFUyPuEZoTVxFKDNeEC96+8LnT/s1nWG6
            c/66ja/+zlykivPS0GMojkPK8J54RxQvTYsdrJVasXg9WI5d537VFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRDVwd2dzWkdkdDhyN2RI
            QWVKRHgwcElGTXR0cnVqaG1zQVdGejVQT1NjCkpPN3NTUGlCdVJTTzcrS0lEalpN
            ekFqZlp1TlBsMlhKcjBDcmpZelpEblkKLS0tIDl5cDRlaFRsTHQrRXNDa3huZHlh
            Zld2YUFHL1phc2ExN0h3NG96UjFpSmMKs/CJZkyFNyse4D0Qsjg04r4QDEsTDWRO
            HyMYRCzTsO+ynuSnO2h2RkYIZHv+CvAE7O3ljxsaY6rhiozcYc30wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubUtQMHFGMC95UEF4RU5C
            YnpCekxCby9jWHN5VURmb2JUZGNENXJRR0FrCmh5bG5rSm9oVXRMNWdPQnJ4WTVl
            U3VENWpITnZLZmJNZEtFQXJnNUlyMmsKLS0tIFV0TkFsMnlHaU0yTjNPcVh4bjFp
            Y0UxY2g3TDFodlhydmVrMXVTVFRMQmsKSzG2fJHzk554KdIwyqOlgZt3KdkGb7Em
            ZA8/q8oix4wVj6Peqmq3qXnLNZSxknLUJ0Zv1PFqlTS2YJ9Up+Pqew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:M9tyxTaMtr4QZ7mqL3DSi60rwyRFusvmuU9KfHtQElNL/iMTFd/66GmMJXibhzI1zhcV+KDanaBWIjmazRI1Skc1Vfj81AU0AUXgV5cWuO8iQMVQP8yiZcLwIV6NiUlI8sOgO5dHLWY1ayJ60IA9mbinzuPOfdNoCpOapq+dU6g=,iv:NToMudMu034ymyKl6vavlxM/D4csZB7VxrQgE4DmgJc=,tag:yKYynsM6VwXpMruRjsy1Qw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
