apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:nMkl3UheIs8mTrBbDa5MMem7XVnF6fZahhA0Mg5Yakvt43Wpm7LGC4sTVZSpbZj+,iv:1z6Ops5jtvJ6+TqCf9QBliySERhjllDCwf7WLHdC/Ck=,tag:oKRcEopxDWfdFPMh6fM8mA==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:T/bEkQHJoHi0Cz2IfffDGb85RQaxAYOW8kRCtL91o1ct66n3rAM6TPbLkvrK9iUp,iv:5F5B5RVADSdSKJvSHGF34OJzR661Aq5A7azWwKmP3y0=,tag:iZi+DuXnASBj328dl470hg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:iwXNBctm4NugDALiwqbQ9Hkcdz//gKTrwhtV4GES/GHYmNXury7s/U/fmdlRFw4W,iv:h1M1oaONiB4olQvhUstvgszkCy/sarJ6OfRRkAuW0fc=,tag:kFZePF++7OHY1Qm2waQHQQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:sM6ZlfOuFtDCmCgeLCxnRCdDeJOc1vTnsfN6hIx6d24XRFWVTSZ/ddLraZjuy7xcEEKBEWhwT7y+fTxmyP3fTzTRpxsQ90lzS9euecQg11CvqhzWWzG/x84w+0uQXR2ZEzWlsG51oYUxYQpemfQuXwf+E1R9sj2Z3tXydHqBNVKTsWetqi7bPV79yNu4uL1ReacdcHhK+4tuX/LCXqeA9wA+SAE=,iv:qeQuJjiH6nPZQYtonnQoIwTa9gkqlyudgP1cy9KEtkA=,tag:CiravwRMNJIsol3246RsEg==,type:str]
    DISABLE_SIGNUPS: ENC[AES256_GCM,data:hRhrrg==,iv:cl6fNeEbVWSEBR1KlNfkKpIVdQY44kfAfG1d6F0wW8I=,tag:8Fc0ZROdyIgYTU0ISIqvBQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMm85dUd5RlZCVWwrL3U3
            RnF3ejNTQmdmZTEwM2N2dFVvOFRxblo1MUJrCmp5ODNDbzYvYjFROG5OdXpMckln
            UzJQaE45L2cxSE1Ob215ZFpITTlYU1kKLS0tIEFtbEdWSXlYMFRCYTRmMUVJUDN1
            T2VMdkxlVlpvWTdZWjQ1S3FSZ2xVQWMKXlfEXKx+jtIBNyMd5oQNNixmxJLVLo/a
            yve6NoyXi2vlfE8lY5tqFKcmjuFq2ny0iePmqpML/buuceQRfKM8DQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUWh6c2JKL3RnT1R6TUpu
            RGwybklNMjRTM2tWdjQ2ZGRVV0pCSGhpZXpNCkorRGhiNERTb0lHUmk2M084c3Av
            ajNEbHdzaHhvV3k2S0x4NGxVSllGOWcKLS0tIFJtek5ocXQvaDErdDdYMFVCSmx1
            VExqZFcwL04zV0twUURWWVhnN1h2ckEKehwLSo14dsdr/JxE8ewmd/P8GRULEdZt
            r0CzvtsSFgRxjA0JYqb5MsB2XJg65C/IVrzwRp7LftXDAeSSLDuu8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0lIWlowNmhwVGpXcmV5
            cUFOQURQek5MYWRyS21aN1dSY1FYZmt6WUE4CmpiUTQ2dW5nTWR6V2IvVjZ1S1hZ
            TngvQlpwMkdoKytSNmRuOXF3RnhWcDgKLS0tIGE3ZzdYZE1xR0s3RXVrYm1FL0hQ
            V21PcDkyanEwcCtyQXJEbVVaOE1hd2MK5cyZBLd0C9yQ8d9+enrOXy0045Wr4579
            3VPsFZiXf2mPm/mbs7EFb4Nx0TPYH3haKSlsIB1Ux5Y56VB9vuBsFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:5s36zxUG5SLSi+ugc6eftk3OJK1vEqNAqWHnXEZ6edExkwsw2Vh4PfGPS6YWhu6gVglpmRdpeqFkAYrOMo+QZS/OwtzVboNHMxaa7c3Z/+bilJT3gZjyIBaKi1nARYBa18s2oeOefAbs6v5r2ReE1dpxQtF8g78oC5VdVClFvXE=,iv:zPLibOkwFTKStsJ71/pjet5lVGVHJ2CglIyuRp+ZkAk=,tag:lK8IVMAy+SU04XkAmknwxQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
