apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-redis
    namespace: argocd
stringData:
    auth: ENC[AES256_GCM,data:DP4CEJIgypUvNlv9OhxIncwL8aWxPZI2,iv:tebXkbTftoVzdg7upkusG19W7Qqm/6bv4MVpHFXjskA=,tag:+LO9gavBzSzRTcpqyEn36Q==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbDZQRGxGakl1NzdhaVgv
            OGZJR1ZQdzk1OEpxTUUvSTF1M3BqcXY1WmpFCkU3dXlscmJCNkFhd1FQL1BFQ3Yz
            bDVmN3gvc0htMkxBdFFoeDFiTDVBV28KLS0tIGpaSXplME4rTEFqcmFUU0xKWFlK
            ekxiM2Zrci92UnpQdGtGbExKaG9JUEUKF/S57jDp36rmQx4Tc4AkZcZ8kF6792EK
            jbWs8dh0r6GrYST2qizcSOH1oUF/7S6P4ORjXVkiIAdZvB8H7ayVmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYVNHd3VMSkdxRi9jaWd0
            NVRMQkUxVU14a2NtaFNIaTdqMERGaW1WQVR3CmpKeG5ZaTQ4eHBES0F5NUZ0SU4v
            WXdYZk1KUUxjK3RtQTA5bmErLy9ONVkKLS0tIDlKZ3ZqTFZiR0EwcEJ0ZU83c0xa
            RHBWdHpGeEtCQ1luMndubkRkY3ZBYzgK4+YyQQgN7nCfVrDlK33YC8txFFCRyStV
            /2zW+W3ueA7TvBKHR5H8WnFRnDnZvYHwBI8uX02SdgbmkMMFqvp69Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWmQ1ZmIzUUxnbEdLVENB
            Ym9MZmJENUVYN1hjTVpGdVhUNmFIUlZoNXc4ClROVkdzZnpMdU5uRXJMeThtd1dC
            YkdPTW5CTDI2c2xzd2NOaktMeWFCWE0KLS0tIEY3M1Bxc1d3UUpJcFJDMXUzRlFv
            aTZ4UHN3cXFDaTBySUk4Q2hTakZPNmsK2DIGdYNzlX2KptCrPHaCbL2z7OsVaouv
            zbexA1e3/iCMjLSVUBfiMOmnCfBGlDrMCkzrxW5dhGL970Mn+sHSJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:6N43zNGFi8iUCKKDBjhhcJmuXirWr3ohkkMD6q62GV1MAp8EKk7BdDy1AA4B4aNVBwWpe0oJwrOJ6BzM/uIg8FieY9ZjKY3HXLsatWsWCxv2hlrPPUhJpmjU9311E86IcwgG/UXNeASlVsdQidkpzuhUY7ZXfhw77j2F5hZBkG8=,iv:mCL0EdVeB689sxA5UeJt+/BGHBq4UdmipvG1aagTRes=,tag:/dKBf60IevUZWY2ruCX3wg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
