apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-redis
    namespace: argocd
stringData:
    auth: ENC[AES256_GCM,data:l9oKCTMi2sVtTf9dfvwLKnO7WKIQsQpx,iv:XwamTfztWht1ojBWOAWF7Bf6TwFGWVzELM47jvBQ1vA=,tag:IPXz+bt/hpp6ZzKXkYChHA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSmpldjJ6Z3pKeFhnWXZR
            Z0RnN1RXTytJVkpoem1mOWxVaUpEZEJWUUNRCmljK2dTM0VQcCs5SklMOHhkUG42
            REErcnA0elppNDdCbWcrQUhEUDlPaGsKLS0tIFlQMTk3ZWlzUUNvWnNpRHJQa3dU
            N25Ha1J3Zk94M1dsMW1Sc1ZwVW83MXcKDfGdWxr52K9mN0YOUiZmFDfbJykaYscV
            PQ6xDZ000vseHq2n+i9oqnn+SCafODFMik8w9dPHgF4uQdUWdKHTfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aXJHQUdBN25hUGcvZkJt
            YmRzczlRTlU5eGdGcUFHelFOd2xGR2pkVm40CkVkb0o0RUFEbU82NmVUZ3A5T0E1
            TGQ5MW5jQTUwcFRMU3Q3eU9PY0NtOWsKLS0tIDNtbjFLL0FjWlR3TmlRejlPbUN6
            Wk1ZenFLYjlRMUt3OW5XRnRDSGwwakEKBORvfzLcCM+Gj4rYUshM+S/7T16YblOd
            89HJ7TRPbPEJjp0UdA+oHksueW8go9ncv8CKTmDUkuINP80xEmLvAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdWhDeThyK0VLNXJ4YUpp
            WUI0QjlsOHdJbHVZOSs5YzRYSkJEQmd1VHdzCkVBSVhsUVJzVnlVM1l0QWtpKzY2
            N3VnV0Erdm8vLzNVQitPU0ZUTWtCbVUKLS0tIFIyM09lSkx2d1gvUjRoaWwySENZ
            VndkZ0RKSGsvamZ6RGFoMWZNNkxUbk0KYXKykHprdciyYDcL1yR9JKfvotgAxvPV
            FF7Y+5pUwSFS3F/bEO9TN/l8NNL2YjzyYj+bBaKOzUz0Wu/BpeZHmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwelhhOC9RT2RVSFUvUER1
            TDdmV00wd3hCak01VUQ2U09XSUZyYkVFdG5JCnkxRHFTL1JycjBEQXJCUUpMbERW
            WXcyRHNSL214WnZJUzhFRjZVTjl3WjgKLS0tIDY3ZmRWR3dSeDdBRWJ5WEhwUE1C
            NDROSmJCMmxOeTFpR2diUGxlNERRRWMKGGCh0fZFUj000aJS1b26+6dXBQR1W1Sz
            WiqAKaw2qubx+OclfZD9N09Mk5DlnTZyJ3lJgauIm+eVWBSFTIbI9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:ZPvf9n8YMm0QFdoBH+Vneu1s6wQOtz0RTk98clWl4wWVfbq5sondezhVK0RA8hC9f6NnkG6pkuQx/PY+btX5uExykjUngvtsBO2AGni7w32Rs/Va3zPEhG7j4h+DnUPc/aAGAQjAYSeoshkhJZUom4PrdRFbxIF3aSbIbuic1Wo=,iv:OtoaqAYVHTcuSZ+y0UbDQJML8IBer2Kxl9eFCCfOWo4=,tag:/1hmXWsTV6+4J08pOSa3+Q==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
