apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: helm-secrets
    namespace: argocd
stringData:
    age_private_key: ENC[AES256_GCM,data:e5Pupaqywu+H1UJvy0CYXF6W4wRuZSrurqwTxMCIzeajJl4IqgvYBqeOnhIkuL05AsSLLHKmIRXmwzvQ7UMIDs2GZYwQY4Y5Nwc=,iv:uqQKVUkzo+xY8F8/vtnha2yADWUimBTedm2ub1ZfJfY=,tag:jo1gX7YO41hn8SW4jjJUoQ==,type:str]
    age_public_key: ENC[AES256_GCM,data:zNH5Q74KlqA4cXV1Sg+obJds5NkMD9W4vXfAI5bqohVCqLnkoKqlbvRnXhFPmR1/HVgyNuHAJkiQSDgPxSU=,iv:QlYsLy/vUuJK3aQIdDmvjN7J0nyeKl1RQoQ4jTTK0x0=,tag:lQRd0vG+KrkaT8mTzkOKfg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTJzQmYrcUFCd01qeXFY
            UFRRVDBURUI0SVJTZGlWQ0h1MzF4NWgya3pFClFwdXVSMnNNdngrUTR6cWY5czBa
            MWZHRWZTZlFCY2k5L3FiTk5NTXMyMTAKLS0tIHI2Nzh2UUh0YURrb05YUlQwbDZx
            T2pDNUhwdDUzTlVEM3RBdkxZajRWNUUKVKb86YveuwFLKQLnbNnUYfZJWe7kLQw9
            BjBdcFGnPBDkkW8I1xynrqyWewZCNZerZMaACwwlpHjKCk6U6CkXFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSTdxSDZoNWhDc1dhWE90
            My9YV0pWdG40YktpYWNqcmRFazBXQTNQRldvCnh1VlExTmVidWRQcjBMZG9KRHZi
            WDFzV1U2Qk1mV3hVWEtaTTkzWVM5NVUKLS0tIDNDbTBIeUdibGl6OVVzcEEzWGRZ
            VjAyTzlPbGZ2eTEyUWs5TFdRSE1PbU0Kh6IAW1Kyxmysl4x+ZY/zYy3U7DmRJpb+
            0EoTO00qiQXtmu1BPWUYLI79JhltTvKpzaGdMMlMIiaHIzm5XiPUDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb1dxODNxU1hlcFkxRE9m
            b053VzBCd24wbm5FZUYrTWVNOVZRdzlDNkJJCnA3MkEzbWF1WVA3bTRZTVgvbkd4
            R3hTNlNHWEg2dGhKODNhKzdFUDdjdTgKLS0tIEllOEJRNllBNW05ajB6bm5sWnpB
            U1JSUld2M0p5L0ZjMDQ0aFNGYWovbHMKWfkoHhz/pHqBlr2ssa16pThkLhPvGaJf
            Banu3BE8W6Mkyp6PSCVoZbl8WQ/f9YUvEwQ/GaDYlVqwDbjjwAQEXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:5uENmebbYH/bMX4sF3M2qp9Juz63T4KHKXDWSK5sDs44tjygFIjO7LeWFnlWnzxihgiZOV5h+fYM5n2DF2pjOuakELSsMtdsn7Wl3xTHv5eNQsiHsZEW8RhudvvODKm/Issw16W7fHQUWkzYvdskKz3e+Xuu6mdeo4+Jc3vPwPM=,iv:sti6zLmyx+r61i3BC0DLeyZH4HMs1RYaF0sx7u7n94M=,tag:hzERuZflCrVWhcVen1IBzA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
