apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token
stringData:
    api-token: ENC[AES256_GCM,data:IODOpv7PlfCrh8XY1KyC7F+nIZegdNDNiLdhKajno1hfW0xvufi3ig==,iv:+17GfXsfnLX7oFmSkmlqMwPiGBUE2HajxgcPmLSSDYg=,tag:p73dVDvTL7VkBmK2jJF8Sw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVElFdVRLbE8yQ014RWhs
            eWx1ajRSVzVaZ0J2WVkrSVJaRE90NFNBOENnCjhhZjdiNkIyMUVldjl3QjI4WGJX
            ODFnYnZabzNwc21qVEovMGthR3FiSTgKLS0tIGlkVUZTTUtQZEtsTWpqNmF4VFQx
            bFI2ZmR3djdKUEFibFZwcXhpZXFUdDQKLhhwWBGPHU8TsZStufDkFr8dUeOU6OkA
            LyjcAO+Iv+OZbKK2eAxH+2moR5LkKeJ5a6I/28oeO2mqq/XsXDtwDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWmt1MzFMWExQYkZsSS8r
            QWE5M1lQVGNnWnh5YUd5b0hsbmZHYUkxaDJvClhuZGpQRU1mYUg4RER2SHpLclhX
            QkJtYUVyUUhBVGRnNk5kWlp4VzB5c1kKLS0tIGt5MlFmeU1BVDVvVEtKWVE3cVk3
            aVFkS2UwMUE0am1PcW82eFNudVArM2MKyaDT3BQjM66OK+YomEnXf4b9y7e4Hh6X
            tBelAqgy0G59ZXEBzBVOklM24lYzAlmfm4p4bvME95jztL7rb72rkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd3FyY3R0Yk9zRUhpZTB3
            K1hOdWNDd08vUWFlMGJsWTRGdU5QejhXR0FvClByR0xoZG9LV0swVk9EbDVRYVov
            djRCT2lvWUFHUU1tZTk3dFQxaGhvV3cKLS0tIDBLdC9HeHhXdFNieDFBMk5Mb1Jw
            SjBld1B3MlFrbjV5UHZraHNNTEVTdW8Kg0oyBvzuMijGAhArOt/K2e3uCgfgrgY/
            0s/MMZYR9FEaRXHdL5BgvAPrmkN7id2rWuRFnwfk25qoL6aWtD71PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:6VmJLWEDWZZpkPQs/z7ByeWjz8YgBy8RAAWGQ422WwoZyWKKXCvxkIy+8gUmoIoTY+y4m3/5W4rzIflAqKUMlEmkBVjVUJIEBlIh9U/JCtUC/bnix0ojTKyz324Kzcp6m+bxwx1RXosDTT2oOOaOXtuugr7JnpRmfamGMUnN2EY=,iv:UBYO+W4poE85m6dE9wALkLBDTSTlsUlRmOFLWKswrAA=,tag:UwSobbNblciTgCqqJsHlnA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
