apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: static-pages
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    app-id: ENC[AES256_GCM,data:AYPPUt+ABkW8O4sus3MkFH5nHScqVZtTyg==,iv:amxxxR2NXnw+FNsjdz/bqCMK/efAgZYr/VXzni7utR8=,tag:8wZp/K/874UYys0dkcM0vQ==,type:str]
    s3-secret: ENC[AES256_GCM,data:0kWXg0MMwS53zD36KrG3bXhGIvl+ngQcuQIkARVXrQ==,iv:qu/9osuUlEfG4aJa/62h3+L0t27l3tmCZVTTFBwE/eg=,tag:cAr0HbSMJ9aoxikZX/qUyg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZJNGRGeWtCc1cvaVR5
            TFd2QXRrUTdZdUZkWjlZbDRKa3ZGUk1XWTNBCkhOY2NWU0RaNVBOTmNYUzdRbk5a
            b0J4UlN0Vjh2TFJkRU1Gd3VVNEQvaXcKLS0tIFN1TW1wdmtTT0VzWDJrM2EwQ3ow
            V0o5cFRyMTQ0ZVRvcU9NOXNkMlhXSGMKJ+8gnJy5tXADOoD1ioKN3ufoUMXu21wv
            j9Gk16uIUKrf9QqT34u4iY3rOmbhloKRrF8ZuW4m1+gs7fHWdL+eUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0NuVFREank0MS81YTc5
            cmVad2FpOEowa2NzYVI5bE1sdmQwK2hCU2lzCndDUUxjczgyMjBEdURaSnJmTnp0
            cDh2TkE3bnBsZW4zaHo2NVFlWTd3MXcKLS0tIC9QUmhIdXEreW5PMytSay9QT1VG
            L3FTNXcyeXFXVjAwR21kMVhIRUR2MFEKmxRM92cDKXXdddUAsaesz1rjLz6KVpBc
            mb4/SBflQNdYGcrHWGfK+EMwpKJHMByj5bs7VXVcVtHK8qgHjgHsFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMEg0b0xxU0tiMlNQeEdN
            SlppSHJXMW1EclE2Z1N3cW5oeUdxa3FMY1hFCitCeWJjRWVuMjNCTFBTZUtmdklh
            Sy85eW9hOE1TaTVObXpPNTVrL2xqb3cKLS0tIFNnS0luMEVDcnhUVjgwZG4xc292
            RTF1L1pVZnovTE5VUDVydmFpN3pxdzQKAg0gdol4NTHpJCSKC6puBQIkZDUQtChq
            rnG6j4DV7veNmjVb3uXsXgF3CjkTp9nlwu3OrNDQwnrZWRHN98HrWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:6l6PCtI8JEf28oQ32m/+9a0DCqO2hRH5avNi+3YeLjotNytMZFWx0BKTmQ+4WMruncHcf8XQxVDnEn+GfGcP/scD+xkDRfo+Df/pivoWiggUfDRe28d0JthesRAjwssB8Hi+leTKR+Dbc3hfwj1XwMewUd4XR/ZV7ForkMQs+jM=,iv:vC+pPpy2mgNDRAnTwvVnJkUAi1gXbCLVkbr712umOwk=,tag:h5FTytKODeD5D+V3xslVIw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
