apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: static-pages
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    app-id: ENC[AES256_GCM,data:yawggrkYHJFUdS8hz/fktNuYVvO3mtyYig==,iv:b+Jpppvwt91rCLrVugLKAC0HiCTr/FrmrfwDhSx+n3M=,tag:8eS3W+o1AaYbibs/yuH/0Q==,type:str]
    s3-secret: ENC[AES256_GCM,data:D6FPqmICUDASGlkX5H2YuLkXQ+C/SodEv94bx7396g==,iv:DsXqQHGg2y9LAwGOyYIImYgcz7Id9p245S8UwVhgR7k=,tag:oefYX/SScujKDAywRi6izQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4enFJNDEzQmRtMnNNdXVZ
            NFNZVEdvMFJITERMZ28vaUIwMVF4b3l4U0E0CmNQYTJKMEgyTUV6MXU2UHRQRnN5
            U254TnQrRm5WL0RPYmxuQmRrRGJ0c0EKLS0tIGQ3YnZ2YjI4bFZ4dHo1M1FPR1JY
            THIxTmY5RFhEUEF1YkZmb01BRHczZk0KLO2oY7bAJPVy8/iiF1YWCn0nKnQyEZ0E
            XYAcVFxfKqqD0L7INR0RdNkynAPkXKjlszM8oEwtveVV1fmvoq3CFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbzM3cVRRMDdHU0NmUzZ6
            a0JqNHI0dXBKL3ZZcG82NWhQY0ZSZ0hGR1Q4CnZra29LTEJEVGNwR3l1STF0NHd6
            VGxJaWZoSk1KYmZBVzZJdlNCeURmazAKLS0tIHh3V3JEaEVzWHNYZTRSZEZneGhC
            aXE3eXJiVTVVT3NrUkVzSmlNUFRXT2MKzJWYHNnH2Zphb3jBSL9UvPheZgxcII2C
            3yjGiV7TN9YK0HVdU2hpI2bQhtFoXx5EnU+8I6x6xtZqzOHRaYG9CA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMG9XRE1Nc2ExUEJlOG9a
            ZVBHZXMyZVVHZ0d6YkZ1Y0FIWEQxTnROMXhvCnYzMEkxaTJNQnpnY1IxVEhnZmJT
            N2xQdXZVQWIwcmVMWlhXdCtidmQ3VkkKLS0tIC90TDM5WGtoNEI5VTc3d0VIK0Y4
            M3lRZzNPSmJnUktiVG9ibHN4MmhkSjgKfZ2ObuyvKs0o1COUWrYJUImJYePfrfgi
            ee92uOOHdr0wJFOuFm10cJcS4Q3G9MOJGnsP2mIVFCND759L1ThOSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbG9TZjFEL1Y4Mk14Vy8r
            Y1Fsa1JycDJobVp4YncvK0wwTVlTdDJONUhNCnNyQWRHemx2ZDg1SjY5RFBmZ2Yx
            TU9VWktHdEJqcG1TRTdrNjhib2pqZG8KLS0tIFltNTJhRkZaQ25Cc0laV0hmZW9X
            YUU4Rk14VjdlK2huNUt6M2tMaHI4ZWsKtRcQ0wh1QPunYs4k29Nji3NyVtQQJakE
            +LJOT41L6KyUmCuFOxr9ZrHxmWJShzCN9yThp368rMoOb85CFFIOQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:6t8qtaxkkiyZuacxRIRjqj7ElEhg9huMDzQTS0eFgV4QUX+NOVqSi8jGg+YsfyPfXAJc/czRuz0BkwicwqAcLwdyqpOg9SOnOtvS6H+0wy515lOQj9GOxr8XheZ2cWVXtFGrVT/+m6fZQylXx6Z5w4Bsf7KOcfin6JAswSNnKRs=,iv:jt89+CS2AMmMvOPdIL51tnm2mB0o1eFNKROD3dg1qdI=,tag:fppye28ienYxo1qIL6HT+A==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
