apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:GZdWAnT7ijtrZM86N0DlFaCbYwlMkgRnTQ==,iv:YCoHpNwx8bBvPTP7+dK5paWskW5CPpKUebYGQ+qmuLY=,tag:B0TXKPj1gyBgCtgph3zl1A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:nnJlSK4Ovrfi9Oiyd3OEpkLJ5COT/YfiYYVwk+lPEg==,iv:7G14IKHvbAHK4X+MBjKQdge122FcK4AbEgJ0N/zCg20=,tag:c5rh+5uHM3sQQZwSk8V75g==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYlUrNEV3QWZkZ3hzY3Ey
            SHI4QVNobjNVNVNVYnJLT1A1RC8zN0FNVDNzCkJsOXRqRHUvbEh2S0x3NXpJWFhi
            Z0I0M1FJUWhvZllZMTNQYVMyKzc3cWsKLS0tIHF6Qnl2QkNjTExJV3dtMWRlUnJD
            SDFydXpqMC9iRFJFMHRmZHRNRlcrcmMKaY/P/GYePbsigCv4i3BT01UAk22vtJmQ
            /sgg3aJVCdftnAXEYo/WvkgbuBRjfw0vaOHiNoC55CvQcGLcqghOzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmZjOERWcnY3N2V5bWRM
            MDcramtVbVBaZktOY1VoV3BCWEd2NmhkbFQwCkhDQkpmbkhlMkhQQ3Q1dklWOVpS
            UGZxdFdabWs1M3RUVWQ0R0RWU2d6b2cKLS0tIHVJOGRtRTdqdlRmSDJ3OTVicHZw
            NFVieWN5VFFnRmxJcTM5T0xxbkJDRHcKhr8wBvcTY9Z1wSzaHjoELSr2J2HccY6z
            up6RTXR/5KocuOoBYXDztzNuIMN7dLheIz9zc8TzvIbjghgx31T2IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTUFBbjhublp6dHRjQVdF
            TnkwQWQ1cEo2YWJFYXRCVGd3bUdHUjBaRkFBCldWVmtjRms3UHk5ZE14UjNBTFUz
            Um9lM3hJYVNtL1NkMlh1MWZmUFIwdncKLS0tIFQxRXNOWUdlRmsxNlp2em9QRDhV
            Z0pTYnovMUg1VGNrKzR5WlEwcEtYNEUKa6m3FMT+UQ6XcYUZFlnyI1kweYfZ4LD9
            y15gw+jF3u5oNXZTDevM2U8aVPCNev0bm9TMdDyy1suiaZwMcn2AoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:3nwI6weiyZlxX6cIqFEXWqIlXKsFfJyeE0ixB1R/bICOxY+cc2eQ0Gngecd8NgZAI4JE+C2ldhEgNasdgUSdP5DbbC4vgSsHfcQnrm+mwU7xXEn1XSNapqlcJhKOKmUBNDIH9MY7QCb/i9Pn19oqoqwR7QChECOaJgchoZ/lXGw=,iv:05c5Sqd5kOOGqmmURiUnLLyue5rtkk3rY9X39is7fDc=,tag:lt2ruwZO7UxTlCI0ItaGSQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
