apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/coredns/cluster/labk3s
    repoURL: https://github.com/SpechtLabs/k8s-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
