apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-meta-labk3s
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-apps/labk3s
    repoURL: https://github.com/SpechtLabs/k8s-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
