apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: holmes-secrets
    namespace: robusta
stringData:
    openAiKey: ENC[AES256_GCM,data:IDdzYko55mdeBNBnimL9F0ec8Zq9Gw5zFR688fSsCnm7CF/trAuv4cHA+//qYJaKpjCSlNZ1KZY/JMO/4sf/SNIzXx++/KjWtB34umWz7/INa884gtgrFPxu3lX2PwRvrAoYPKyf+nPueEZikPeDZMjYgnkWbkEDMxOO3PhMCorZD7RmfIGcqKQRxgLOIa5svQbKWtZg77dUqsvNJZ5yAwViOX0=,iv:nRqd0ZRh9rP0vLik61A5RNxX/rTVE7j8FkbgcGHv2rY=,tag:Bx4KRpiJ7fZDBYag4HQ0Gg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNXNLWTdldzd6eUR5aHEz
            VmdzYWpwSmdBMWduaHZza3pzcmkxbTBzU2hnCjJnb2MzenhsN3Z4b010bDdkdU8x
            Z2VzSWJUQ0Q0STNMUlBPeXgzMm5VVGsKLS0tIDFMTGp3QnBmenIwQk5aYTc1QUla
            ckhIaEdMNElTZ1FqM2NHdVZMRDlhTFkK7tHDwMM0eZJVB15x/yuB/fs2YznFcTu9
            uJz40KmNoA9MnXFiZLtEYHFZFMAtUFECNVkgTfxjrpZFUmAq31vExg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYlZ6TldZWDhRNS8wb2NV
            K2JoRUNrdzJva2YyeW5Eb1NHdEo4WEVvMmlvClVURzhWeit5WUtNaUdEYXpEeXZW
            OEdxL1RXTS9qaHBPb2RNL0phS2JGSFUKLS0tIEFQdE1PR2hsQUhyVjNhOXp1WHlD
            blRPdTV2Rml0ZHZwK1hGQStOMEM2b1EK2Pl9Ue7ayBULwnDSAeyssRQtoyCLVpGU
            Z3IAO1hmBnC1qx8gMcnmYG6CLM1EhBZi4hXUmD/RK+5EeNJpYcHllw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRHBDVHRKV1o0SEV4U215
            cjJkS1BlRC9aTlZLZjg5aWU3QXJZTzNOYWlvCkE4dUZqN0FBdFlNTFhUOElRN1ZN
            by9OTUpCQWhQT1R6amhtbWNMbzlBY2cKLS0tIE9xMGQyamFVL1Z2Nlp3MVVKVUJM
            NDhZYTJjSUl3TmZJekg5M3dKOHZ0dXcKvVkdeb5rB3IVgyGlG+8L0M1HVYZ+/MG4
            l/OAudrvOHmfxH4NAf9LYvIEIIPl5XdaKTQlzDALcGyEUzBZugw8qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbldGdk9oTURud0taNzha
            dDFoOWU2R2E5MXgrQjdhbU10bEhoK1RjazFZCmdPemVaNHN5SnJXWHk1Z0dQQ3dt
            ZkEwWTZWOGhkZnJaUmo4STk1OGhJYjAKLS0tIFNBRld6U3Z4VWRRWHd3R1h0ZG1M
            RHJ1VWVDYzlhMURDT1lkMW5nQUVkTDgKKO/KChDpkksxyxzduwwOo8pTjIg1zqDq
            NxWSnGXjabXTbDAWod6SLLO9DZqgdNDcdWvmFiwauzpbu821aCkTeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:XOWDrJfZgnKoXjRJfmaVkV5DlzAYnurgAt/iQLFBbPohinZSmlg08oT578TKGdEmIqSMM2MF5X+SVw1Yb5cHXwgsn4jR6jGIpZmmhbjSjYBtiZtveaOuYdHxojdvS64tkj6XjVz5hb0IYBClVCSmUv80s0PkwG7VDUnFumUsVBA=,iv:2C30yVwEx8zR+nfV83UQVE4+fYkhlikB/nfz23L3XXw=,tag:P7HK96n1HmcVxNtpcCk60g==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
