apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    admin-password: ENC[AES256_GCM,data:ayj/U20xkL5zOuMNGZbVEK6kreCW766XFKLJ29g=,iv:zzEc8oWXcugMJrUKxVS+p30rN9UC8o01ZH8iY49CnZY=,tag:K8EN5tvuKLfB0SoCVyeIyg==,type:str]
    admin-user: ENC[AES256_GCM,data:yNnsCFA=,iv:r7PvbVNHmGQL57wyw1lq3UHDgl3x00VQntSObTxaCkQ=,tag:XY3T7oYJMQi5Y6VR3ZxGVw==,type:str]
    ldap-toml: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWTVkY0ZqRXpYTzFabGh2
            a3dhTFFXVTZXN1FZQUExcjBBYjBNRnFjUmdnCkZkbENFYnVlSjdBbHQ3S3pOS0R1
            YVZiaEQ2cGFOQUdnSFZOTmJVbVNqcDQKLS0tIDRTOTF3cVIxRGRtTGRSUEVIbVB2
            bzZRU01rSnh1MlFxUk5ubzhOZFBqZ3cKZHfOPPnCzCLSREUmRtVpEOUgcaznG9xX
            RQ4Kc05ufw05MVrpWmauVpxeGoqQ6OrfXf8jtwgRdbp9M8gSQoVzrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQVREbUlUci81TjVmYWVD
            QjQyclNUMUpIbEhpdXNmOGV5cUlEZDIyOTJ3CkpGbGlzd3hWb25sOEx2TU5GeFMv
            dzJKRllDMHQzdnRzMmVtSUVsUThYNVEKLS0tIEROUGg0aDVzczduU0ZPL3FSTzI4
            SW5PeVR2VU9DT0x6RzgzbmlGLzIwQXcK9YFgDJ20nCvzWOzqlq384/Npb4cVoXXw
            gN/Qz8nmYUEvuF2XRd8XUdNCIVH24eqpiGrq47wSvihtNFKsYBU86g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadER0cUVVZlN1aEpsaGMr
            K0E5ZWJpQjI4eUVsWEEycFdkU2oxWUJwMTNZCkJzNHVoaVJpUUtGNFBXek1uU2tM
            Zm1ORXNMdmkxRXNQU3VUbHdpMGsvTEEKLS0tIGg1Q3l6cHVsQ0Z4bXVVNW1HaExq
            cFpSVks5bGhUY2hjR3poYUxzU0dDMGcKutNEynyAVySL7FYq9NT1MZ7AizfhMMCS
            hGG0vN3sPYzZSmPHXX5OK6TuzVG2BtwfPsaEOb/Q/9/Pt9f8K2yIRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMFRKRGltaXZwOTBxN0Nz
            Q3lFbGRUNmFzNDVSTEVVNXdGQ0c4OXFUNkVrCjVVa1VmRVZnci9ZdzlPL09QL0dU
            eThQaFRMYVYwREF1YXFkZm9QKzE3SjAKLS0tIEhnd253dmxvMDUwWVA5OTBEeUJN
            RVhwc1RiY0puOG1zdUROVGxaNjhDckkKid64ZajM4iReMq9gczDyHEuf8mvGGlPe
            GpDNnTomAdp/WpsEJmQaZZzPF/AVhW8ZVLP/gORKh+5c3SZXWZ+QfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:MW5Rq2ShLvOWTfHbRmYVTxkmuKGLB6hPoMwYrClcbzjYNpGX6XORmWo0y6wbYysiwvUmSOSCAQDQgs8qZv5lpXWS2z0FMcFblS8qGmrnvY3NlWk+jHG//4pYpufr8jkopRfX87fhXpP4jTZPqJtBD7G2MLdWbsY+NOMBU5dFTAM=,iv:O6G136I52kfVwRmZtDjaVPKYiM0CkluHO1zBwPLwKrw=,tag:5b8QOs4vjTOubfO4E0nmLw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
