apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    admin-password: ENC[AES256_GCM,data:L+fB+BetttUYThQV7koeqa9Z2NjWfY5EQyyTTEI=,iv:VKKmCpxA4hlZ+5cUQPP138qR9zd5fkq/JbtCMniaACg=,tag:VmjhyK6kXTFH7j85di4p8w==,type:str]
    admin-user: ENC[AES256_GCM,data:xkgtHi0=,iv:UccnMOHNQQT+eGCoex2F+wONjQTfEvyP5FHeI9V2rkM=,tag:CCkjnMCpz9GaqPbLPXaOJA==,type:str]
    ldap-toml: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ampBTUhhVTFITUhMc0ph
            NjlDY3JEQzZYaEdGSnI1UkdPNk03cVdZR2lZCjBVYUNHS0F2aDY4NXA0M0szRTNZ
            ZUgzSFZHV2YzMG41ZUp4ZDlvOVlHRmcKLS0tIEhZdHVRbFBFUGx5Y1ZETnRDM21H
            VFJtVU51REgvanpCeDFrbTB2eFdGSDAKQ1w/okq5oHOBI0uHtBVnpAB2dNFimbbd
            ceBQVaTxsUe/1tvBNVdzg9rPIjLYDsPC6mv7KNjKqgxRtQ9lUCrKuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1p2RUp5V2xsV2luOHpW
            MHBVUDBnUG8xUHRVakdSTythUmF6dENkemxRCmNSdUVsMjY2YXRJNFR3ZE5lRVZu
            OGM3a3lDNDc1OXFrNHlSK0ZmMDBXZXMKLS0tIEpvSUVTcnVmcmVYTURaalFnSndH
            RzFEUXp3UzE2ci9TQ1plMG8yRncrTTAKum8kZ5hdwXhacRNhaO6HWJ3fcn3RgM18
            x1+kBWUovU6VEHD8VGrKMZT87bQKY2bCt8u+pYENVCFUQ2+5tt1PLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaempFN1pZbitlRGhtSHgv
            dXIxZXUzV2NNSTlhcEp4MUF3NDlVNnpidVNFCnhtWkJuQ2RLV0Rzbk1SRVd5enJm
            ZUY2aUhSZFFLMkVWRUh6UHdzRzR2VmsKLS0tIEVsQnJEMFk1YXo1aG1lNnZoNEg5
            VEtiV1BPeGZWZVlYWnE1REdiaDcvNW8KVyiiRoValoQr8uL0tUAphjJO+tvNoghG
            wiGntDbLJzlC9oa9Rgv2NVMhIL5iDClgr54MVcKLZj6Y9W13mzk22w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:shFM6jlRt+IQNcfYUZyEniJR1Lx3wqryd5ub9vsxiOyEGly9MdDv03N15fYubDQn/nDcId7ud5LVyVMatn4qOULpM8joQtvxRiJhJ75hy0EJsLyT0f00A0ZeoinRn4Z+Eke9BVdCQ8G0/J5SLAJWO4jiCmO2lbFpNmDVZiEJQi8=,iv:vHm/qCMYCIU4pxGSVrhf4e59OyebUUjXlSSgG7skr+c=,tag:vUXr2WLsUL8sL1npzL1iXg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
