apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: observability
stringData:
    auth_github_client_id: ENC[AES256_GCM,data:ckDnOX90cEtV7w8XrdvpTPGdKxc=,iv:kJyh1hNef5i40ILIfC50PxycG9UNTMWddbNBSHAV4fc=,tag:5rXJTIACaZOrMouF2ZfDnA==,type:str]
    auth_github_client_secret: ENC[AES256_GCM,data:7t+UpWBwxCnZIA3+Ft6sLP4d1RRW31QaxWf+6gqgn6Bk+i2U3XGQaQ==,iv:shxCWgPtRsiv1qcZZj/KoXZ/WrO+HcD507QbKEi3HT0=,tag:5vN/h1eKkZ8ynpS1SdE4fQ==,type:str]
    auth_github_allowed_organizations: ENC[AES256_GCM,data:r5u9oay+20myuA==,iv:NdhDAM1an78tG2YRjTYHP6OAI1sAm3DS0cRThmCT25E=,tag:A+x8nJ12NI5XpA6e65o2tQ==,type:str]
    auth_github_team_ids: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MzNUVlhMbnBaMElCdWNC
            MnZwN3VPWkExdjBNWGZjdmhHR042OFJwQ2hvCklhaFFSSlBTcXhWWElBOTlLT3Y1
            RS8rTG0vbzF6ZlNWUEY5VnlGSUtjVzQKLS0tIHhua3VrV25VMTFTOUxOc2ZFU1M0
            ZnJJWUJFd2wvVWhTaXhpRHdrdXVwc3MK/oBIuztKRGsiBqHNz++hyWTBnuFSlSSR
            Amt2PzEY++HZAue1pJCyG+sceYUC/fa53fWiXEgklTGD3atQFVxR0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VmhXM0tVQXAyOWQrbkJU
            RmRZaFdDZGY5a0hnRE5sSXlwdklxMHRZdVc4CkE3NXIzOTdrWDNBQ3FIT3MwdGRG
            TEFOYm50V3I1b1ZiN2ZqdEV2dzVYQkUKLS0tIDhHQ1JGTHliZDFVMS9Fdlh3NndS
            T2lEZzVTdlhOQkx5RWoydlRQM3FXSE0KF9yIyZ7hq3R+sbxdSiLwOUjPbhCT4j7i
            d35pBfth4esHECCzKrzrkCA2BtyfHBSCpsSEI0xEXxsJC9NOaePUGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabERKZm8wVWYyZlozVkRB
            Zmt5dzN5d2oyY0FOZFJWOC8reUFHYmpqbDFBCktZZ1RrZGg2WWxrVlVNaUpnR2ZQ
            MWh5b1ErSkVqcW5nSTJjZFBaM1krRU0KLS0tIGRsZW1iL25KTENFcnhheHlsSVVr
            eC81SmQxUUM2L040eWRyNHROVkN0SzAKMSBioWjHKlFKQ8W+hac6RHFqnR5hj3j8
            U0aclTr48j4HIZ804dvqJkraeOTD1d/AqcpJBvePp+2VuYCCdypTsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:EAL8cMRtzr6Y3Qg++MYhM6ol8jfuw8FvW332++E2x/xxlH20ptQz1O5XGvEDzx4wE2jph8pRc1pRBiRO4cR1+71cVBKETbS437P6SvE/t3YK0uusabfF9ga0udL81K28SzVZ8I10iHnuFEnOqzGV61Seq+Ye2qyiqmqjwT2oY8w=,iv:U+rn1u8BXKmrMO1Q63DkoT1ILct6k7GwTjw8bMlZHNY=,tag:x82/KB8NM7yZk+fHlWXEBg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
