apiVersion: v1
kind: Secret
metadata:
    name: grafana-pdc-agent
    namespace: observability
stringData:
    cluster: ENC[AES256_GCM,data:CrWNEm6Tcap6HWkSUhE=,iv:miETKvnDNCnDZlK/ToaShN3H6k2l9/6n3brSvlP+UqM=,tag:e6CtaJvYPztg/G0ptDdXpg==,type:str]
    hosted-grafana-id: ENC[AES256_GCM,data:8n4xgbj7,iv:6xoTbw2csIIiKEztBn1I3imQGuSeY/LCkICLrWvJf/Y=,tag:SX17CrjI4d1V8qV4El/mvw==,type:str]
    token: ENC[AES256_GCM,data:cSFpR7VI6TJL0F7KqQrArh55IsLtYg+8Sa3+6N98tXAK+QulFePHquLFzus03/RcnIviFNVRbJEpal3/EoBGLv/t/fJwpRjmDfMqvxq0ojZA2XGRxfSFWMc9vsV6k1TY/kpB6r77Jcp+bMkgRJtnnQ/6UlkHqFbO0wp7H2lB4quljscZVl/C0OzmEjak4aYY/KaW0g==,iv:5ezmaFufMzfbgwhlokX3vIhaN8u1XVubbvKxn0BSPBs=,tag:rz7xWg8Cw/5zmAqu/41azQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXh5SnVYOHhmL1ZjRjNz
            WTZFbERoUGZCU0gvNWczS3p2WWhRUUJSSkhjClBNN0E4akNzQ2FveXVqZnJIZktR
            VmVqcVB6RUZ4VTY4TUJzSnBzdzlFejAKLS0tIGpKREJTdy9PNThRN09qeHhLd1d1
            bVl1NndDTE1IN2hBL0RUUk0yMkZSdEUK2LcxBFHo+NhwurxcKK4/Std9fAmp4XgE
            6c8ZD/JolZSb0cR4FavA9NdVuKKYwcv+VYw3LpnD4hlT/f9uzb1j8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2NOWnYyclVHM1JTcXY2
            T21sRGM0T2lKUE4rS1hIU2h5OGhHQ1BYZVRnCnRmNlB1RzVPZktTWUpsNHhvUEtF
            SldyRVh5blo3YVppTnpxQ0dtcFUxUFUKLS0tIGhvN1FsRHBqQ1g1N0grekJlbmtO
            MVdnemE1OVFub1d6S28rVmRjQ01BaEEKQkc7crHobwYgUzwOKuBXSjUbU1N0ql6e
            KbZxXSrjsOL3Vx7VG/NhNI4Q3cRPCt1CH6P6c9QTpetF6t+Hr5T3iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcDVPZ0U3WmZUUjFhZDBS
            Ujd0bXNKSUNIS3BzMDllb2pvUXQ5SG9iWUVRCnV5U1F6R3QybGJxTDAyTHJ3elFH
            c0o3MWEvOU02NElPSWZiRWovdGdVc2cKLS0tIDRKNUNobkkzeTZwanJWS25EanVT
            MFRNNnhSY0RSb1Ewc1M4L2Y2MFdqT2sKAdWNaPq/R5CaqMJZfBE/GHwRDG35eyHi
            IOKl4bPaNCzmez3IquCRvFMu4JlzzmaWKkWynur7W2u2xhslJGtwnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:GxRM68NDuucGL6pmqJPL0daVGWKn7RrINjU6VtLhpHNHNovZNeuwQs8fuUtTl3aNm+kFZCHcE7SMGDwdxcGXd+EsFUjfdfTnmBY0ROD9aqoJEDfqjXa3VMre4bBxqrCzVbmZmCOrm7hcBDh/2HEP13M1Qgr5u47lMAzQTsCmQxs=,iv:/Inlv/G6QzKfLadSc6MR7d5baCGGmY2lax6wimChq1M=,tag:n8wG/cuubBdwm8seBQGTMA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
