apiVersion: v1
kind: Secret
metadata:
    name: grafana-pdc-agent
    namespace: observability
stringData:
    cluster: ENC[AES256_GCM,data:nwJ9J9xNQnyPZao2Tl0=,iv:pOrh7YYx8/7DDL2vShOzKcPgyPoGle70QKCzk7fUnD4=,tag:3oouHv126bnCJFhiUibxVg==,type:str]
    hosted-grafana-id: ENC[AES256_GCM,data:c0p+5NyM,iv:2qfFn90eDhLnfKqKOO8WLvsqq7aXrohLAH9PMwF4eRo=,tag:nuo+axD9Xx4UjlM4lWJGeA==,type:str]
    token: ENC[AES256_GCM,data:7XhDkk63DrZF6QXEE1fSTCa5f37VZVqA9ZhmJZA0lWLij4K8SE5vKQtHNUoIlZVIoNj4M+QhZQOR6ieDx6nbPOfbbQt3bC6VNrxNQIkQNbmK0oX/zHORQWBpjEp/FVYJH8VFHclRMP+f06nvuqwRy097BOj0tHrJdekjpgpwQJA3ltS9gK0Aw+7vEcSxpFkiaudXbQ==,iv:DByd6rKFKgnhH11jGZtjqh/ktFiLA4O9Wt8soX5k6qI=,tag:CaaOCEeYvHUQ4XxXcvNnqw==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeE5aRE9BeVVZRktCN0RK
            eVJIbnVJYk51ajdkUFhDSy9nMElFTmRwUHpJCmhldUplbEl0OElCVWRtTi94akpU
            aUt1M0lqdGxteUlDaU5VTC9qd2pEQ0EKLS0tIFdzQ0M4V1l3eEJhZFJPQm4wdHJI
            VC94QmJ2SVpOSG4zek1ZL0pYRUo0MG8KV9kzps8ChFVdMrNDTfVeQWjwmMGH01iS
            1L7OVIimhVvqKeXdYJ8Rb6QVJekNihN76GDJzR2OuaOCp7u9Okqp4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYWR0OGJVN3ZtblFjUXJQ
            dWpuWENxYzMyc0xzb2g2YUlHeEhUMzY2YlFZCmhTZnlLajdLYTlDR0lGcmFpNERt
            cFJBYXRaMUVtamlnSndFckpUc2tsTFUKLS0tIEVpL3lJd2Z1S3h2bEtMTlBGeVFY
            NUlTYTlGQWE0K3FvWUlrYTRXbmVudVEKnrrcL4pfBUdpc4iR+F08A9UpIAtf1LYy
            k/1/WxdKB4yUefUMMrNzOJIZj0XxoTQbPDF/fyqWlauDWALJE/Mm3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVGxSdlVlYjNudVJsYkdt
            bUJlYlVQK1hJRTVHWFlCdFd6UWsvbjl5MVUwCjIxUlBUbXJDaFdGdzFRY1NLZGts
            OWNCY1VoSUNMT01Ydk1IbjFxQ1NxUUEKLS0tIFVXZWZnVlByNXJrajJ0bEkwS3kv
            Q2cvdXFvblNsMUhoTFpUOFRhSVl2RkkKlDxiXq2q7vRJLrjSY2MqLdCKd7ALVAbD
            Au5gY+YDa4TU/xK0nazkAZkAYbQp9cPHcn27Ew0m5UKZOO272eyBeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU3NOZjF3Y20xeU9sdmEx
            bXJpQ21ianFUWkp5cGpqbFBmSnY1MDh1dFVZClMyMlY5V0pONjd4VkxPRE5SRS9S
            YUpoWDZIUUh0R29ZK1FtcHZQRlVMS0EKLS0tIHZ0RUJvRDErbTgrUU1RVUF4K0pa
            U1NnRXJHcTlBYzdTUkpvVnpIYUUzaWsKcSX8N3OVb4run+fSg0o9AkYjl7SCq/EL
            uUww2Lgj8E7IeEGW8JeTgXpEuwL4LickOPewSTCt6Bi4LAWaP3yc1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:bnSng81OvICLjVoG2FA9YWJYVCu7hZZq1qpb+c93zQ09tASY4UNN4pxJQx0mQV6yg3ufV+9Ynz7HK+zmsRAoVVf97nM39KLZiJNJ15HP//ow7LTwkingFiWUbs2FVo7O+CjfyZ+OOFwRZwGX3MBN4usTv+ZaEgKaoIy6q6nY4wY=,iv:noOHWjq+lpD3FZCYMMTEMABVmV95ViWqTZBtRn6/UZ4=,tag:xTsjAISEqW4kwOfNzvn/fw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
