apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: grafana-agent-operator
            path: apps/grafana-agent-operator/cluster/specht-labs
          - name: grafana-promtail
            path: apps/grafana-promtail/cluster/specht-labs
          - name: grafana-loki
            path: apps/grafana-loki/cluster/specht-labs
          - name: grafana-tempo
            path: apps/grafana-tempo/cluster/specht-labs
          - name: grafana-vulture
            path: apps/grafana-vulture/cluster/specht-labs
          - name: grafana-mimir
            path: apps/grafana-mimir/cluster/specht-labs
          - name: grafana
            path: apps/grafana/cluster/specht-labs
          #- name: grafana-oncall
          #  path: apps/grafana-oncall/cluster/specht-labs
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      # No finalizers here on purpose! This stuff is critical and shouldn't be finalized easily^^
      #finalizers:
      #  - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: "observability"
        server: https://kubernetes.default.svc
      project: default
      source:
        path: "{{path}}"
        repoURL: https://github.com/SpechtLabs/k8s-deployment.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
