apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    client_id: ENC[AES256_GCM,data:qOtxQIr2zZOj+8GZ0GN6n5I=,iv:aaxSqaDpD/6LD20ISS9DHs0RgCUH9GdSmUt71eAAHwM=,tag:yvcKrO6qbF++8ahbtX5/Mg==,type:str]
    client_secret: ENC[AES256_GCM,data:35DCBJ8WFABGAYSQGisg6taqbvff1V8coY7unAbM8YehnTfUBMUlx68Asu3iAqUN+qNh7g2wVpY1/M6x+v45,iv:X0oXeKB5MITHrG4aQBdNVm/cUUVaxumYqM3ERe68Qbs=,tag:7GbOdi9cRX5AFAfCOprmVA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bEZQM0Y2WlBSTmxESEVU
            UzlXQVJWT21PbC84cU9GRGpCS0ZYUTNWMGtNCm9ZZHNYVFZKaE8waWk3QzFSUFJh
            SFRWNTR4M3ZmNEFlYzFlL2VnUDlYVlEKLS0tIEZDVFZIVDd1aUduZURlelRwd3lX
            VHlkdmU0Z3ZNNUswdzFKMVd3ZDlVd00KQklUCLi1ozRtK7Pp88WV2OoMSs21XAq2
            IHggcfTtgRqNPYDtqGZLzF6tlijX5TZmAaM38mGiFWp7fHQhM60xyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdXhLejU2cmI0OFdEZEth
            clhnVkFLUGFmRWxaWHVSUFZQcENaMXowa2hvCjV5SEYvazlBSUJ4N21Sb1JEVVU0
            a0YvQ2ZyS1p2V3BqckZIWlBNZ2FuN28KLS0tIFRjQ0xjWTBadUs0bVAwNDlERk43
            d1BENmNNVHMyVnZZaDN5SVp2NFdMSEEKX3GYeVEE0O7c/6sIdk4wF73gMSMz8QJr
            Jxy9mpwAdZmmy5xU1j6RyOzP5bUFaCEbWjTKEIvb1Dvx3bLkkhGu9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUVowdm53SVJ2N0xWY2pK
            RWVoZHN1bHd6VHdFQnRuRHI4TnpUUXJCN1NZCkRRQzRjU2xaZVRVa05BSDd5WVY1
            eEtiTFoxakpPaVFlVFBQUTVLdUtTSW8KLS0tIHk5SW9CVzlrclBZK0RLQ3doNDhJ
            YTArZ013bmUvNXFIM0FESDJGWmpYNU0K5S/6xPReFlhbvGNFD5n+ziGYfDpLsL8I
            IFxy7083aJjzSL0IgcAtLrWE/qFZAD9H5KkvEcsl/ka0SEijIKkQ0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VG1XTXJEeDR6cnpmYmg5
            K3ZSR3cvakh5Qmhla1NDU2dyYnpGNVU4alI4CnBJckJYRnF5a0hnUHdUWFBtdUhu
            dWJBWWQ3aU9vMnhwdlIxcTBCcHRVdFEKLS0tIE8yVVFCZWRZZUpka05nQ3NhaUk4
            dHlFNlBOTlg1V1k5RzBIM1FLOW9HMkkKGjYJc955ogYtGyVEdQe23wm7tiZpecI6
            KPw//IXENqBDl0A+4IdUjc23nfdkPjT3DRHLCx6YubFbsx5WpKt02g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:lwk+V5nXnucVDgPFH5s20lbsN8jdYNGNqzpSm9nbIFjrE4m5mpbH801EqvXtWnBTF7hclcmP83rfuj9YzCmwY6zB/9yXXXZrTfb1uV2NItTeGJUB9wm+ncpSXGw/LWUa36fIDqZ3Dt+zeq4VuLVC4iA3WoxYq8GKSUMur98F6vg=,iv:IUbUD1M3Krz166QL8oLa5GQThlg4Ezh+LHa/JU/pASI=,tag:ZEW49Gj5ubb6SivAOsMgTw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
