apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:t1b/7qjBJQm/BZgrMdwJnSiyyqz60SD2rHvXk6W+aUiyTpHp2D4otSag5mBjQpJp,iv:5M7HCp6WxwFN3efsa8FM/IZggJHw4Vu5FzPRPUhGVIs=,tag:Q4/+Kj893nXh+x97QdyUPA==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:DsH1tq/XeEiGqlB+9Wzclz0F+3jcfUtiZjBWtLfVO5tr+2dtqa+2yTBb5M1tQ10n,iv:UTBclDTypuMsUkCmv7+Khptbl/bWVxKhRnssrKgIn/4=,tag:42SrIhRqhwJugiQKBTkJ6w==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:JVACtxq3AXJIgYHtb9GScU4u0p8qt1r6UFj+ZwaY7ulsPlPlfTk7GueuhPeF0u5B,iv:9Ex+r/qVOjao5ZI97jrEcArVTOglGBb3yzrDv4ABMcg=,tag:3stuWBj8c1muZgj63+pnrA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Rx+zXaZfADGgGB5P15J02AMaWsFfTysKywA88P7fD2coPVAabmjMeJdtL5qr7V+4Qms7b/QJUzF/gw4RRN8Ceo4sUjbFPpi3kBdzv2pCVmmUQ+P74gCJ6HuvCFxjtm8yrBMR3WirtuHJ46KMIbdnL5k2A/DI1hdWOvfHVSoUcsXOz/7OMW+UZZMgzkPH0zG3Xnms5PbHZq6xEOEQEsTrCfrpKWc=,iv:FFlUR8u16puZScF2OHmdsCWywfIaHQVDtBL4ht/OLcI=,tag:s2VbrnM35EAapi7NFdPaCQ==,type:str]
    DISABLE_SIGNUPS: ENC[AES256_GCM,data:CKLXkg==,iv:xfgE/8902qE+Sv0/EDGZt0GIIYB/ODHMBDjpCZy/qxo=,tag:FoYTm2JA9B50xFgxNZPL1w==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeWllUGQvNzUwejIwL05t
            bXJoK05ZcGxzeGNsQ3ZpVXdJMGpQSjdSdkZnClkvQVFSMWErbmMvamxKQVBRRi9S
            U2hlcWRNNkZkZVhJYkFqTnJiczlHR00KLS0tIHNXWE5ZYS94YkNycGJLTWx3ZEh3
            ZTZwUjk2N3hONExNOHN2aDJwV21sOUUK4pb44Ywww2tkG128O+tLlWPUOMueLN83
            sNIVLnVyV2PhoAa8V8B8HXI4QFVw9DGNRicfre3GyeUxaZ3VU52JgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTDVtdFhFcWl4MDVhRXJu
            VHB2YU1uWGpOcXpxSmVlY0ZLdjROUWFUUUZZCjJtbUxYTkN4OVJhWmRjWTE3WHov
            YjZnbGNlTE1XMzFlOUxmVXd6NGU2NlkKLS0tIFdMd0F3cGhtOC9IYWI4LzljbVVF
            SzFHREJWUWVJbEZwMWx3ZTNjeXY4S2MKWBO0kOjEBA/LjTnA7st/tCuSKRZobMAb
            vmde9BKRW5JPymJkaMUJFcsBgAwneDrlxJJtfGitgBj62EcnYx0pQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc2srSGpXYWIzeDFFMWxM
            S3RvbVFjbTJVN2VhSDlJeG0zbFZSOEdiVTFVCjA2dUZGdWllT0VNd3p1NWZEQXJz
            ay9SQVV2anYvUEpVUzVqclo3RWkyRk0KLS0tIHFzcnBRN3VDT1pDZ2VSRmQ2akRj
            MUpqNWxKQWtsQWRvQ0s5Sm9XOWR6TUUK8KZpInzIaERxacj2/SuH+3OSWu6ppBHZ
            PUwhARAkj9n0wWNbTKT9VT4ayJ8dYRL0a2yQ1UA9PYWv1VqQmXP8WA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMERHUDNURnZwd1FsRmxC
            RHg5Nk5hdEw0VjkvQ0RwQVlsVSs4YkdidEE0Ckx3WkRvbmJwbXBPVXpDM0kwcW91
            cjhGZHBtemwralJ3NlBwems1RzhidWsKLS0tIHh6bHJVU2cxVFl1R3pORDBJNWVs
            WUtBUW16YkRQc0pLRUZXQ3MydkwxSHcKOfdfpHfvLtw7pmLuKxbClEVVg5FW6nCW
            kjw76LFKXN7wj9ODqMYFFNph5yO5Q8ibMVd+ELwg/eNu3sAVMCHhUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:Gp46t76QGnUWP6Zg+AYu5m5ynXJIPALZekF6ZlEAXw+rOAFnJPNSp+b4EObVy9qjRJlfpE7lEuWyCnvTC+z+6lJBPucukgDBIPUDD8zigJQfibEp8XcDZS87h2Ng1isW4jIXnJKlhAg2UpBP0qWOC3a+eIiCE+BkO4/aYPNmuhI=,iv:AotNLGCNKkG6wHqVW7w7ExGqERq1ZVRHZMlk7IqtYRI=,tag:o1zBMPQffkWGdKgLWfKmQA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
