apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hetzner
    namespace: default
    labels:
        caph.environment: owned
        clusterctl.cluster.x-k8s.io/move: ""
    finalizers:
        - hetznercluster.infrastructure.cluster.x-k8s.io/secret
stringData:
    hcloud: ENC[AES256_GCM,data:pQLmgdDYFBov9hb9Q1wCevOJ0jSW0a4uTfvJ2TaZtqITQNFWOpLygQklI4wFImdRYXAhAGfOhHiHMmi/zfFrlg==,iv:4AiOY4Mqjz05aqsA0ToR+82Bbclgmr4rTHJtRYdwvWw=,tag:Y3dXPH9jmCAM70xi063upg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQm0xeFJ2SU81YXVtSzZk
            TVNpN2RYaWUrRmEzNnJzbzNaR1RwOEhNZTNBCm9MbDhxYlk0Vm0yc0svRndDZjg1
            K256UUZQNVdCYUVpNnNLcGRqcEo4YlkKLS0tIFc4QlhpcElMbFh4YzJMWG81WWtl
            TzhFSzBmdzVDODd1dEQ4bGpoM3kxSm8KhL2u3LKb9Ov+ixiC0/Tda7LJ6Ojlfb7c
            bMxN9O8Sj4zO0RLnJledNuhyjL4BBufXeVUqxfpK42BVbvezxbLmxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1EwL3I3TUJHcmQ0NlBU
            NjltOGEwbmxtR2dmdTRpSTdmSGtLS0h3djM4CjBnd0hGWUZJd1JDcDlKVWFGOGUy
            UUtpc0VGbEdwb3dDZE05WldOekYyeWMKLS0tIFRkR05lV05Ea0FnR2t3U1ZhMkVC
            dDdSZDRQRkRwKzJqUWZXdDI0aVo4bncK4k37ERXkoQ1Ljw7SLqQTrMEMAHt45IFY
            rq9/gcBqkbuI99sILrkQSBVUXrySsMKyVcbiutKyE9ffFMx4P0NTpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c3Y2U25rcjRBM3ozOGlD
            QXcvSlJFQ2ZtK1IxNTF4RWFwdGVzZFZ5em1nCkZ5RlNFS1Q5aDAwRHA4Skd1bFBP
            WHNTbGRsc0M1SzZ1VnB6QTVSYTErbzAKLS0tIFQwZXZEOGlxZGhpTTZwZlpMU2ZL
            QjQrdzdNVWV2S0VPYVZ5d1NId3RPYWMKptUeE5OAb7EeHPHE2Ir/9ya5WXHCj1UT
            Sfem07mewops9fEZlMKmYjE19WzKpCkV82TQgT0dmhQCkoaFbv/zwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:44Z"
    mac: ENC[AES256_GCM,data:qOaQ+Hbho8BkcJ1rp4eIyrfX/vWddpAEVjO6T1shWRzuzjHq/ZNyXFC/Ij+8+IK/TBtx8CWsrig0t6c0BSw568cRommp+TTUdqRoOmTkxBFI352Umgl37T8GUFrJohI2vZYVP8Q3UtdS0aR00T1LaoxsJYVNH5g6ctGPyf3zqaE=,iv:eBl8FbvAWCg4XOiqig1ii9Xf2lbuvo/s3SDkjRyyClk=,tag:qW55SPf6rPNuQZdeGauUQQ==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
