apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: hetzner
    namespace: default
    labels:
        caph.environment: owned
        clusterctl.cluster.x-k8s.io/move: ""
    finalizers:
        - hetznercluster.infrastructure.cluster.x-k8s.io/secret
stringData:
    hcloud: ENC[AES256_GCM,data:8tSdogvo3dbgr0TWhzHCdUis92GMWwh/DonP31V4WaJuCcoH7k6U5TmPc9zYhWPoNDoMEfq7j9DLE0rRwkATUA==,iv:yzB91ghklqLNg6eOWYncqy/s7Mp8xpIGhPHfaOiuH2E=,tag:ZjjgapwU2jM35WzNYEZteA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0JDOHdBemlObldDbmtN
            aEJVejc4a1A3VFh6Tm91bFI3aEFRYTJ2TXg4Clp2cm1ONFZFVERKOWJnbVk5aEpz
            NGpTN1EzS2ZLOTZYR05INlhPREM1YWMKLS0tIGNVeVd6SkRna0MvWlYzbzlXQk1R
            OXkwKytHdC9KNkZqdm1Hd2FLN0J0UTgKNaMqQUXGKRRfjP4p3M/KacZP5g0GZueG
            V1B90jHHlFA4YYHqKvdLKfJszfTyvOpWEqWkJbeCzR8+GjaaegOg6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZFRoVFFKWUp2YTBIWUVH
            RUtrTTE2dUZMZ3laSHhDbmVRTXdoZ1ZqM1M4CmZLV1ZiRkZRT2dkUzhmbXUrb0ZZ
            RmFJZU50eXVueisra3pSczMrdDhhTWcKLS0tIHQwZ0QxamovVWJ5amxlRzhBK1J6
            NCsvTXcvdzdJWlg2b1BxSXJGK1JnZkEKDDGxpQDmNxF9nDj2LZqIeG23T8SrdCPc
            QWt3wzvTNLvZ/h76jzwZmBQFmDyub0pputNmjkoYwnenoqgxtj7kkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUHFCbHhBVENnUFRnblJL
            dWRrZG12VE14cWQzYVB5aFNlVmkzYVcwa3pzCktKTDVRUkZFTVBCemwzYmxHZm95
            VVF0YTRGSFRKbVdNME1jUG5XN0hlZE0KLS0tIGxiT2xtL0dlNExZajRmTEcrNDRK
            c2cvdUZqaHRZTmtxVDZJcGcxRkkzSk0KgraNYzVADb+fht4nMH7H1IVQ8F6m4x6y
            s9LkMcy/3JWcLnE0G29RSnko/Bxwz0pIIB98DxeDDtN6j/TabruKEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXRiUnU3UmNtWXVKeW1y
            d3BoeXROdkdGY2EwMXJ2bkxHQ2RBT2ZvaFhJCmxEMVFpVW1uY0NraTFiUWpISnVv
            SnI5bHBJNzlBckJoNjNrZDFoOUdQaEUKLS0tIDNBMytST1U4L0dCRHgwRUVVSDhI
            Z1ZKR3Nsc3I1WEtNVkYwTUpPeVEwclUKRNtaKHJgJ6YN/ih5Lhh027nfMSDpsmYT
            Qxxg0Nutwt/Syyt++Vlo7+KyM0y2+6f2Nj4TvJs78p0iA3kXQ8sDzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:FmLNkrWXJ83GBaimSBQasux2dPKqlTjAvX6XYfrTeO7y1A2bwIX9zZXSBdu8ASR+UT2k9HhLmEV5ydq9bKBeWhlDK6gQpP8pbz2V1ldOmpSBB6iwDhwJXPcyFg63jKRZTkcVgY+WiAq9hyfEw0I91ssq0eApI3ifAUcsaUj6tls=,iv:N1P0PlUIuL/4Ml3/Y/0iPDXl9Of+SQy4u+RhotpDUxs=,tag:9Hehjv9eG1ix6j5s0IxXWg==,type:str]
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.12.2
