apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: loki-objstore
    namespace: lgtm
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:q8EQ3L5olCrMyyVuXrC+6dakx0Q=,iv:l7JV27hdWnvl5etCsyj8a1jwL9fycjOGChUllHsHiKQ=,tag:Lj4TZulFytmcc20MmpLOhg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u56boTfcSGd9agQ83Q3QRkWPvFA57aEU4zxeIwFQF9XxGFCo2l2ncw==,iv:Z29x6yruNmoAarGhmG+rG+BN2MSguUuvWQlw0jNZI5w=,tag:9DfjmI7gXIItebqsWvT/Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNjgvZjE1blY0S2RtanQ5
            bWt0S3NsZDVDcU4wVWhUWFJRQW93L0hzN2dJClY3Vm0wYjFBQWdZZUtkMC9WTE51
            UXVNVDJvQmUvdGZkb25uc05jbkFyTUUKLS0tIGVjWkNrQVZDNjByT3FHdm83NXhV
            WnpUSUlsZ3hYbFB5cWxhdlcxSHZ3WTgKvKie1jHB4Oy5c7UeqkVFQYNXkb8HeCeE
            XbLne86ud+5v//Z6+vAf+INwE3yRcPeqrm++IBlC7F94C+hUcHAoSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOGIzTUh0K243WEhPd3RH
            NUVNcDYycWFHQ0o0a3B4dGVpZ0N4aVlCb0RRCi9QTGNEZmNiUEhKVXI3dHZQdjdT
            ZnR0M0VDVUlOVDNwYTBNcm9Vc1NiVU0KLS0tIFY5blQ4M1lxMEl1K2hZc3BzUFRx
            K1dBQnk3ZFdSTTY4ZGJoQ2xodGZNWlkKS6lw5gynpX55SJ7Kn9+BBjspAo+9+9ky
            1gwWxLMLFwW2qT7R+FOo68qu3WTuUgRt6Pd1Qm+nYNNIPG17ESha5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cU15Y2p0aXU4bHp3OWRk
            eXpBUWJFTUlRUDlhZm9XS21zcytaT0RMcHo0CmNWOVAreithMklaSERLWm0yRzVN
            Tjg1cnlVVkNzK3ZySjBDMzBsRWZOaVEKLS0tIFdMa05seGNEdmd0TU05NG9jQkhZ
            ZW4rMzlqcW55dHQyVE9QK1p6a21EQ1kKGSoTQ2HF7olTqRQ5MOCtFy8PckrfPE9r
            DGE+YwP8P4POZiveHJk0l8lt0dAWHBRRr3Ox1rGGBozXzgLDWn660w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSFpmVmlYaWsvMlhudSs5
            Z1IrMHpwVjA1WVYyMjgrQXlXZFZZdEF0SFdZCldlcXFMTGd4R3dHQkZRSFBtbFY5
            QXBFeWRnbUNqbmsxT2MvZUF5NU9LZ0EKLS0tIDhwWFdFRHlRT2U4M1ZLdHR1Si82
            U2E1SnJXbktYQWZLdEFjSWdEanRmbUEKMqCuDdf6XuGWnKEiITqsheESBnVS5P/T
            gGHAAfvR9zgpGKvcO2IjPdg57IARkukBd4OCnVZxQvdwULhioRxGDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    lastmodified: "2026-06-17T21:26:37Z"
    mac: ENC[AES256_GCM,data:TrKFISqbEct4V49gVQLYIkudul0HHnQ+fAZfQfTyY5NOpYKV6VTUlRSjreeM7Ovg6kgk1cnZ0ViTZeY9uUpInhDY7AHNi2NQ+EKUpFdlN5txB/QrTkrJFp36xzGTW8pxgLUQTB16J3PzdrDb3NHFB+FaGm8QYcXlcSIwo58Wrtg=,iv:TIcZYxk6lKvuQuzge1gvhE8Zkis51Qa2osyU+OHQ94U=,tag:4/OTAcP/+pHQHYDKOgC3SQ==,type:str]
    version: 3.13.1
