apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-secret
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:bJiZGfc6a9/CAjZ6tsqtsH2A9zUT+77G5w==,iv:POO1GNjRx7yet0IRw/K0sMBHwtN6Sxwpj7JFBxE8788=,tag:KmC2bD++UxMEV28/OhRCyQ==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:x6btCdId/AsNP1LpNuT0QVLXwPj2BD1OBIkUnCXUyw==,iv:NIu6NEpxNl/N/LrCrQz+ugQveDVdmQmmdGhUFcHDpMI=,tag:om9GcdX1odLM9FCZeLAwnQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWxEaUpJN3BlRmNLVy9T
            aDEwbDF6NnJDYVpPQUJsbVQ3dDYzdElMZEg4ClhNNkZRK2VrQkNTOVNaNzc1WTdz
            a3lIS0FreFVHa2hkbHBqUXdLSUhmZHcKLS0tIElJMW1mUkp1ZW11ZWdVV3daVVZu
            ZHk2eTBTSnZTR1ZzUmRld0dONTJLUjgK26j/zjBXpB1zmQrE6pu4Jze4AcKSevIM
            Bvsc/X7TWwt/XfYU3d0UtloU7lGGXqv4ioo+Rh1QBC7WOLv7ARE61w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLzV6SUFteC8wY1lxTm55
            dkNiZmxsMUVPSGRSYjgzYUlMb2Y0Qk1QTUNzCjV5VUx2Tkh3OXZFaHdhNVVqQzZY
            bEVuU09jRUxsZldPTEZ3UzlCTjdWVDAKLS0tIEhRQXhWVkpzbFI5ZHk1NTNSWGo2
            YTc2VWU0K0FVenhKTWxYWDVCVit1NHMKghO7ggGR5KoAkrnlMgrxMo17XHT1aHbr
            NDo46SiHK1ABIJdk4NNo7zQVUR8G6cTpzwANljASkwxPY+b7Xk4BNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBY3V5N0Q0dXhiVEJwME4w
            Y2pqbkpDalFzUW1OUm5xSW1XTGJGbHFmSUVVCkpZLzl2bkQza045d3FjdTlDbEZH
            MnE3dURtTHZvb1h6OTFoWFZMNHZmU0UKLS0tIGJkbVJqV0kzbE9GcWFvTWtsQWVt
            WStyWWlEVnY4aVhkM2dTUStqaXBjYkEKA9gl03C6kcyod0do5zbycrnryqmQeEJC
            RO6oxN061Bob1NkD22sqdvycJJmP9pVFEjnAdn/53QZgnQjze+KvHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb3J6S1VIOEtBRjNwdnVt
            ZGR3Yk1RekpRYWJxcFUyb1dtSERnZUd0K0JzCkJyKzRxeWEwYTBCK0xoQThRZnh2
            VzlGTE9PZVNidEVWS3U2WWFBUktyVmMKLS0tIE1CTjFDU251K2FEdnI3UG5KQzhq
            MkViVFlnN1ZiTHIwaHB5V2EzZDZKVDgKuALmcHyCUz6CMOjt2cCFJ9Uxdq7MRxbd
            UDLvZUyWjAeS2p8tV57To7cxdf/zUF8Xlu5kl0fsUYWjwlOJ4d+ezw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:IQzU42bfgxleww7Krrrb+7Zu9UcNIHFz+bu/omDKYQcCleSr98nFURafkaYiHA5MoGt1KQzev7mV/M+UTYEl6wH9LcLvtI6374lscMZNsw7SA4O0GVzGeDfxWUxaIYM/pd37noPdasUpD57Dve8bYlBz4F2JNVjqZ0HkZHNarSs=,iv:8v6oI4ZksDTiuTJgRKCJJQ9HzxMEM4k/w7pAUsGz6Hk=,tag:VCYCYEEUYsU/2t/A3GPkpw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
