apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-sa
    namespace: grafana-operator
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oFycUafzWLUJsIQ/5YBwcHOvQuMUYObKkzb7e1qMsHLNXY8dQA393bKRJEH4aw==,iv:sgS4005IqF8gID/6kV9aw9evwSUTzl1gkKWFANn16FQ=,tag:NDB8M2EKJqfQtX+02QPayA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaDBBSC91N1lqS2pOSnFM
            cjJiUGVLR0daWTdPdVZjcGZya0xjOEEwSlJBCmF5ZkRsZUUzMEtGMmtLNTFwWjcy
            ZjRCZlZxa1gyRCtRblhzS2FnWThOR0UKLS0tICt4UTJJOXBGN2ZKcGpMOFIxSFBi
            MzNuZktyOHlvb1N1TW51ZUVRdTFXbkkKcKBX1chbYibi8e9P02szvoFNIjQWdPGK
            9jtyk0UehQJejZINvCb32JcYkxVw66Jq7zfCLquw5j/3GndtNOHAKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTDI4VkI5T2MvUnRxcDU3
            amczMVZhY2hiK2orYXVMVlZtWVo2S2E1UVJnCjRXM3A5djFiZGpXdG1IVWZZa3pG
            amZCZUVKYlVBMnN0bUVqRE5HcTlFYncKLS0tIG9CSk52eGxoSnkza1JzRktybDVF
            UG56SU5KODB2a1NSb0o0UGlkYThNU2cKdt2BDOiYHUkfffnRqoKGLO4gfhIBVHjZ
            3U0vmRkX1z2lY/wu5zzXDwqEZRYN7Qty3Eo1oJc6Ib3mYIZtKb2frg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRHQ3M2JqUXdqa3FZUG5w
            RHRUbm9RYTZjN21VOCtnSThMOE43VnJVcXgwCm1wMk8wT2VXQ0xRQmI5VlFkdlpU
            ZDROMnV6bWlzb21FUlFkZS8vR2ttWVUKLS0tIGxZVUFHWkZYTXNQUHh5cmNXR2Fr
            dUh0Y0trYlBkL3J6bno0cmJhV2ZIMHMKasv1ZR24B6QeJusEWaKPhSyESPFkprFs
            7PzWqVlBJyKkEDT9MjEMD8gsec8MD3juLC7u7s2EkF0q6GsLNAXc6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS3orVEN5WUhLRGRvSlRJ
            Um02ZFI3VzZ4bC8yNlJHZGRaT0ltWEt5OTJrCjlMMUtQWE42VnNTa3hmM00ySkRy
            cnhUKzlSOExXeHYyblYyNjZSZFpGcWcKLS0tIEFOalhqMm8rMFdhYzd1ME5nS0NB
            QXdRZXRyRHFaZ21VeGZhZE1HS1g3MG8KlfQpP6ra8BLxNp69eKPdipYeLUDlZBm0
            7/sTmWKAQcL5aAwfnufD5fiRE8FcxIHGgLZEiJBvSDIoV+NXvhfq7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T16:52:10Z"
    mac: ENC[AES256_GCM,data:CUzrk12Er6ybIK+otcUb1mBs4XVjapexAxUEhHnWfUF5x7ZTrdBTu14DSzskuJMUjFLNSlhgE7KTmWFw0fCx6x/XUyfVdwtXIPf/lOpnQWQPtQkErVPymru02JxRFUoJpDpH2e5FKGrc5fFPMxzuyqeDeKCoGrB29voF4vLa+n8=,iv:AFs7ob06h1pp6kbyJislqDgWO/sXfpQ6MI9f4OC+uDc=,tag:NcgrtKlUSFQMrOnS6cU+Bg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
