apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    admin-password: ENC[AES256_GCM,data:xQUcvd40e9OpielfO1izmilnNklf9uakAoLptrs=,iv:D8mjHupV5btEoH2MoRBQ8byXUGzURVESlYtiMPa+5fQ=,tag:mG9pgKj2hskhYI7aoeGiew==,type:str]
    admin-user: ENC[AES256_GCM,data:gOgY80g=,iv:UamKGsCZo3bMfRBHrOr83WHdRLBcm/aK0IB4ZGLqRM4=,tag:rH7f0ELlzJWfxyfKsOShnA==,type:str]
    ldap-toml: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SXBZd3VxQnZ2RUptTkps
            OEtkYlhUdlNYbUV0c0FqWElBcTh6WUI1TzNZCkpWRnh0UDdiRFdwMkhoL1ZseC9y
            VVIyN2FjTGpwanFlNXIzOHk2ZG1EUHcKLS0tIEFsUTFEdm53eS8rZlAya2JYc2Z1
            amRKbm5oMlFmb0dRTnVtTlBoZjZaamMKCK7QvQO5ChdoDcMmO/bhYpZgzzkU6sZd
            rhsquLtzW8BwWJpqwyKygSLQMwdX7xflVYG/REuQnigq8KQRpD9acA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1pEVitvandXR2p0aklq
            Tm9CUkxHK3Fmc1hsQnVVbEFpakl1UkFkTkFzCk9PWTZibk5rRHlJQ3V0MVVGT0cy
            dG5wL2VJNFloeXNKYmpvOVJFdUVlb1kKLS0tIC9tSktCMzMzOEs5Ym03ZWFKUnhW
            d2Q1ZjhtYlRUTWNiK1U1clRKZ2k2dE0KL8y3GqWEWQDg6TB0g5m61pHRhwdHcYJA
            nUUJV2R/yEiTBSqv13oADS4tBxAzeRhJsRchLXdhtjabAWn8vvW45w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU3VMcTNzd2pzeXFFWlZo
            NHR2cU9BaC81SXNwR01wMjQraGcwRzEySFJZCnN0NGhKNmZFdHd1bCt3eDJpNmIr
            UjNYMWJPYmUwRWFQU3FuNVlHN1VQTmcKLS0tICtUOFF4NlREZWZtTnZXMk5iTEVt
            eU8zT2htN1UvZiswZWNyVDE4OGQ5N2MKHauSD7n+cEosv0R9Za/IXdhEXy9IQcpp
            d51EHlAJghAJCy/Vytj39bU7VwMZvZw1kz5zRSiSr3PHXe8Q6oe0sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:876fykEpVsuxb28Nd3ZjKESjTyVIN2MDFeUV5daxkrSrtPIHHItm/04RLNVhPdaYHd4cAYBP125RBOJc+Ot7dRoIkKPt9ivtqZ2+uytWCnAQCyRZKY6kjf9oi+jIGajsOvcFu5SmYmkkr6v9QrXJBJDf+NbOLRukaMFc8amg46U=,iv:zbbrcR2Z+kqj0/Q6LkxFuuGvxvt1cViT3bYLhcDcm6g=,tag:gknKTdfpL5VXHqrOA0Sy+w==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
