apiVersion: v1
kind: Secret
metadata:
    name: grafana-oncall
    namespace: observability
stringData:
    MIRAGE_SECRET_KEY: ENC[AES256_GCM,data:kFQaMtAkJcyUwuzfUy7Hh+QIr2/x5puP2zTxSgHGKG9AiqPKqOSdDLom92YDsrCa1YyNOeM2,iv:YQCmGwzCbYpRDT5Ku5p9d0q4qAISWg8iGawsPd6wFkM=,tag:TcF30MDqH/uP3tAafHRJfg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:kC7szQsrAfDISzAOnl+Lcm4SvyJs2cDpAW73DxEtAdfPxnnAQlnJ1odBVxJCWI4A+7T4zrz4,iv:bypgTfKeG3Nf1Zg7ypGFMJBDfPPbYoka9+8PxjpnC6Q=,tag:cioncf2L6a9CK/P1WYkJhQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb2pZRFV5WUd0Sm5wUVJX
            V1Vjd0N4ZUZNbGNEdnkxV0RhbldSdEJjVkFvCkJWRWFmbzRRemxGS1hjZXlWWWsr
            WTBUQVlGK1IyemVjVEcyYjNOaFdNdmMKLS0tIHJ0STF6ajRWSjFqTFk4dnBoNXlt
            QmFYbEJoaFR1SlprNVl3T2RTaE11NVkKlbox+tt7ViBKWGX+6xVJAWVssIhltF0Z
            fDJVt/5i04/CdWPqtxDkteXCI0+pFy8iUwRZlwgkWEOMs9qshkFdTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2hHWWhOajZhU3FQQUtL
            ajhDT1l5TzhnVVQzTVBsejVwT1RZQjkvR0RzCnFwYXlZY1JkVDVoU1RicHA1Y0hH
            emNVSW92U1M5ekpZbnJhajkvaFkwSFkKLS0tIE1nN3pFd2RBdk52VkJzMWcrQUtP
            UCtlb0N2diswMHdpekNwYnlJbG0xMkkKToMpj+4umfo1AWG3AmD49MLUQgmX4jXl
            05Hau5UK44XtQGiwlzlykUvmRDJiUCImpmnrfuo8cqZ8oqpUxxQIaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXBzeURlNThKaG55M29w
            Y2Z2eGc5TXJxazN0SnYrS0xOcS91QTRVZlFVCld5UzFicm15OE9uNk9kVDBCUnFF
            b0Q2aU05ZDBEdXdMdDEycEVsVHA2VXcKLS0tIFJXRjJ3VEVrOWpFRXBZc0cyNnlM
            RlVDRDl6cmNLWXA1aWVTNWxNSy8zUGcK3KSxCoZyhT0ORHijMZvoDbK7Nfib6XJl
            3JxunSITewX/u+RBAgXB3sNhWN85AEQ5QV4egFnOPHL3Jf/48wIu/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:wz/3LY0PoxXfB/2UWUmiOHdOVFI3mk2z2NSMoca/DHSImqCWHcXAw4YWELYE0O7rkamlXgAAIvhqPXfinqfWBy7IKRnKzxmcDaAZb6zNUi5l7oGWuLAdp6RxPNcdz+pspQsvXWpu3S/SwW25kN92eIKBy4tdqhKMEH/L2/AxFR4=,iv:Gh+WQLfOccHgX08XkMhlZbljvL3u0w32gqtfv7mjYak=,tag:gyKiAiFAplYloKUmZubIiw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
