apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-postgresql
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    password: ENC[AES256_GCM,data:pEAxHjk1bZRjju0WIueTNfyscA==,iv:o/wrsA5GJH8Qq4tt6wxX4msj35y6e0ykNofQFtsYyS0=,tag:aVyQKxA7ytrKIlSZZ6KWdA==,type:str]
    postgres-password: ENC[AES256_GCM,data:Gym2mqZqBx07Ke0iPJCa6F8cu6nlVbVxu7/Z38GZ0ftP,iv:HZIIVb/PJgBaxl4QQ/cOK6VqUfKy2e3Cf/dAfPm+P54=,tag:uOrsc02VOBR8m9CVWsuQzA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbEJtM0d0Qjk1K2h5MzJI
            MlNIdHYrRDA5YXhOdGFxRE8rQUFWYWhnNGhvCldWa2UzTkVhbGJhYUF5ZTcrTU5Y
            VmtGb2duODdSc3VjNVV2a1lya2pyMFkKLS0tIE5vSDRBSjROT0NhNGoxWmZ4TzlF
            QW1mbGdLMEFBZUhpZ0ozZ3JwdlF3dFEKK3kPzAbNdv0wUfLbr0LE1PC5P4TanWo4
            BLLJ1YEWu049Dz+iZY+a46GKdAxx6ZCmyOZORQ6OahHQz3DxaQHSyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRnRsNlBaekt3UlVvTnh5
            M1diZFBhczZNZXdPaXlHdm55M0tQOWZaU0VrCkx0TlFYU2ZPU0hiR2wyS2RHSDdQ
            VFRXdFVpTm5aWW02VUF6blNmT0lYWE0KLS0tIEdwWktpdkxodzFWcnNxeXBtSklQ
            L0tPeXVrWnY5eWFMMml4dXc4STN5Y0UKhfIzXITRL+dODcIZlQIOgooU+7MoCpgc
            cNPlBa+EWgFqrbwMbvXwgSkZif1v4MXzn0THUkawS4N2szr8Dsp4Sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UzJKNjZVWnpweE5jS3pt
            dFdjY0UrUkpBaTJ2MkF3b0FkelhhOGM5N2w4CnJZUDByM01rOXJkVWNSNE1OeWRO
            dStsYVdRTXhraTM5ZWV0MVVHR3V3RzgKLS0tIHFGSWtCUUNnS1NkNm1rbWZLLzZn
            dkF2ZWZOOXAvMjByQUVsZm1qQmk5aDgKzYTjNt7+kaR6Uv9P69V3ZiG+V9GK4iky
            lEiINHbtFuoXwJxHai6gLLjAkbvuAI2DTg26mY7ylS5lJIhUWHynSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:VCCYc97tkIALvZ6mq82+5IhG9Y8Gtsf+CINXCK95G7H0ljA81H9LD38FnIoSGXibP0zx1gS1gILureJ7uLAtgtTHPsDf0WNqnego9Zt8UdSSWoTV+vMMJb2M4ldhinrTs/f+O9naC4DG4sZqCPMv/YJZVM1B9D9N1t5HcvHmuEs=,iv:QEAFv10cJiKF6Pa2Dz0gGj7pULCItQ+jStvRfKaj9eo=,tag:lSC4Fzc8/fz6mQPyF+0g0A==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
