apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-postgresql
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    password: ENC[AES256_GCM,data:t1A4qRUdjpCTjJ/Onj2s1SGa/Q==,iv:pL3WaE7xAf68q4JWLnDawlLQU87NOe14ZHd2lDNg6Qk=,tag:tYrIQ4zycPVqJOOG0kd6NQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:Gc+X6k6kW+CqkYzGXbFTkseKFjdll7dYsQFuY43IeO4d,iv:At/8/VYuz6HX90wOu3hqspMCvHQbCX01hpxN1RIA3uU=,tag:iGah4kKpZE7Z2K/sJcuofg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldjBTcHNvZ0FEeUtVVk5X
            RTVIbWhCdHlzckNPL25SUUQ3TmxtZkJRemdjCjNIVzdJekV6dk9Gd1hmdlNBZWdH
            K3I5N3puZEpvTHIyNVFNOXg2QURNdXcKLS0tIEI0S1NFcFBnV0xjMkpOb3BPZ3kz
            ZWYvNmFXdEh2RHpYa0JtTWZXYlZYdTQKBmDQLEQJKiMOEtGarjOR7ag0feGJ4AUQ
            kTTLn9MKiHzyv2bx0SiuWwhiPwW4axlRov5sNQTR2Hqm3PjZLq/Xgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZklFWXRmRVYzRTVPc29m
            a1JMdndWS2RyRUVtOERHdnlpWE1TSSsrN21vCkJYd1lhaEt6WlFxak5CUWJhdWY1
            alI0eXFsTy9nRitBbzc3V2hwV25aUkkKLS0tIHl4djJoYzBDM3orYzlCQzBwcW1B
            ODNaWXp0TzA2UVh6WHJVS2p5Rzh4TGsK54pMXbfxL9bVRZ28eqMTEghyeUziUpiQ
            3IutIa3LW45FprFXfPa7k9WcVhprgqXv5h8W9Rf5bKCrCibdsRr6pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMnFDTnJmRy8xZHcxV3dY
            NDJ5WTZVbEV2V0twR2ltbDJ5L09BenZGZ3pJCmwwYmlMenI3ZlBVNld3Nk9PVXUv
            dmVwYUFzd0o1ZEhEM0d3MllLMGtjV2sKLS0tIFBvZ214M0ZiMW9VQko2RGl6ZTF2
            M3ltcUdwbEM2VGkwS3dIeEJQYUtQK28Kf688TFFdcIIYOsD8fKngR3q/h3PFYZ0E
            WZ+cU2yMHAdWT5KiwGNXYXgQFhG53qAe1VjGv4Nl0JC951mgP+tYdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbWxQT3c0b0psVU1hbzNY
            ZktsdGFaNUE4OFBXWlVNK1MrWXpXcG9pQ0NRClFOZUxIbGRsTDR4bHI4VXVNek80
            bnZnYzd6aHhMZTZITEd2ZTAxTmZiWGsKLS0tIHRic05aVXBZcVNZbU9TRnFaK0hI
            UGlZcGlvT1h1S3ZPRDZGTjhZR01yd28KfU12ugX3L3RbrVLEJPZdxfeBqQu7uvJD
            mKM2nF+uXFEvWmHY2+v8YRb16StDAaBuggsYOUcspmvyI8ZmfWpc7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:J6bwVn3Ce7F83kT5NjqekIiSB8Z1it5YRF8wnxyr+su0LNc6ovaHhTrHGWuyPTn/LPpuwTFKctXe2AoresPQP9Evr7vlPCZP3tiu0cLwVUA/mZHzcal1WEZGDtdM8fXfYgi+Abfb7a57IiKbrZuB5mnUKEiEylUtRvBUMGABDF0=,iv:l8PaikwVSIPIM1s0qB8VYN4Y3H3tKY56RmDw0tbH5i0=,tag:bqRPAD6Lf4KO2gRW67W1Xg==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
