apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-rabbitmq
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:GX7IkPHxfL42Bbk2feX4sBbCnjaBDgL61pIp2j5YUgg=,iv:o8J4bOoTyRbcmBTTyViW4s/ZZLAN6TJfO6o7q1uLKrY=,tag:JuSB1rF9OUioVP6aZmWqdA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:i8MAK1AHrVzfpCBX2cT//g==,iv:n/Jrld3WNw4AnJJu/Y7vFC33KajY0BkbMt/nr/Cc3OQ=,tag:Fn6Eiy1Ad+KIjoAUPVad6w==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc1hMQ1R3K2JCbFRtcDNv
            MXFpMXlRRE9TU1F1dE9IZnROdUZMU0puK1ZnCkFrTUZRdGk5OEplS1ZZTzRZYkJN
            L1Z6ZXc0anJrbTdyQ2dVWjd3ZEhzczAKLS0tIFlSZWxrWEsyVVNHL0Q5Ukhya3ZJ
            MDNZQTJmQmlVRElXUUM5MVk1OGR5bkEKJozXk1PEdldY0fjuwyuHma9ZvxlEeSBu
            nj/GFxLewONOzoAikB8hB5yU4eKKNJDR/ne2VLtFmhOMVHLTs8w47g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVitPWjIxazVEQnVnTVZo
            ZUxlYVhpQ3hzem9pNjNVNVN6VTk3NnZQN1ZVCmhSTmxZVFVLU1VEVGRDVTc1OW1x
            aWQrQ1QwUllPWmpRQjBKT1hZVCtpeGsKLS0tIHBRUm1HY205N2cyWW1Famw3NlEx
            SjNFZTZrZ2NaUUNOanVTakNDaHdPOU0KFYfdfKo8ujr1UEN52jaWm9yZqf19jvJE
            OAUNf+QI14CWsLsNtrnOd3vIV7mk63k3u3C9BjhKPPEYbGC3kbB4kw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdE5ORzA2Z25ZYzVETXUv
            dHNxcmp3WkNMbjdkalNqTG5aL3p6VkFFT2pVCklHZ0JjVE02VGoyaVoxUkdPbXVH
            VkZrTENzUjVEb2U4NzJaOWRmQm1jQlUKLS0tIHFpMW4rb00zaHVNZjRWZmUrekpj
            Vk5KSWIzOWxWTFRtZWlEeDVlZUVBSGsKihkgmRbSNSJmoA6bsPQXbohXu2tU1lCb
            5oMb95sxYtskYDvJ8+QDo/FB1LGKJbkCz7L3jb0y/OaH00qrKPrX1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:jOBX0GxlOJSMwMjCkvno7IjHFsV6EIfFFg+nkV90DqpBUF/vo346x+qtXdiTH8+Vs3t5QVOx5PTnVB3gS8bLA7D3N/b4f/QM+2b/U0OpOTXM0/umeQ+5SXnR36UhsjM/pLHY5OMVCNhogwybXRt39prwkGjg667TX8WDAxff8r0=,iv:UKkru96pGqLcY4ugY21d2sqs84ehEgXWzB8iEq70qro=,tag:emck1R8RcAimQmyI/AnelQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
