apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-rabbitmq
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:Fp5XlZc47cbR88NhC6Oy0ZdaUc6rW3b2DmlNrcIdZXk=,iv:eWuzCEpf4QuLTNJbs8fJ1phTgRjTNbWxzTWtKy7QxhU=,tag:0MtThOSf1ubs5dMIshH0vw==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:LS/NoREWubIEVdzXiGuDXg==,iv:tof2Pz18prZmLUAhHb/1rhJZo+EM3Rp1sR5u4eaUwM4=,tag:TeDpVpLl3e07Jp6F+sJy3g==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSDFjYXRGY2NSZ01EeXBO
            U0ZHTlJ4bTk4Z243Y0laWTlseFlLTUl0bngwCkJ6Vm9SeDR0SzRBTnIra21Ra3kv
            U3Vpb2grVzR2Y1psOGxrdDNoNEFLUWcKLS0tIGNueGJOKzFiY2NYWWUwNnJ2dVZZ
            VzhBbEljTzU3WmpJOHlEZ04zbWJpZ3MKQNboTzGg9ZAwLyR5iCT3Ab9GD2aSgLby
            Fu22+2EyAaKzMAiMUfzyYAsZYjjM2tELzeD3djKJ/1qNSKaGFbWR/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdnlsRUxOeWFITTMxOFQ4
            enRNN1hIOFAxWWV5OFdPcTRpUVB2d2psR1FNCmN0T21EWDVwckd1OEZGNStZWHE0
            dVkwVS9obzlCMHNFWlFRWkNWMFdxNlUKLS0tIERIOGJreHdjK25SYjhXK1FkZE1S
            eVlDekpmd1FTaFVwWm5JRXVxRXZ1K3MKsXFgprB9kEJBgSX3ZlL6xVwurfNGYKlC
            gegcM2sKVuNx1ZKwLZItinzXV+26cbODYezh0Qxy7ior7q2SyMQGVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeGJ3RWlsL3hmTjdPOUky
            aXduNkxSaXZpVk4zek1jSnZ5WDNnekhwbkZjCit3M3ZuRzcvUEYwbFpVOUU1Yi9D
            T1h5eFMxWm1ZclVGZHVFRjJObnA0ak0KLS0tIFkvYU45OEV0UUtsSW53NUUzWFRQ
            aWZmQi9idHJMOWVodzN6ZWp6WXRNZ0kK4GU2wRsJWSogVn1vZOuendPY5xxDaI4w
            Zq8XKipchNn5DnXAPbdPJRTYMOrqKOy2KoV0X+xZSGak3lEttO+ZPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcUI2WVFZVjhmZEdySHJp
            dVgzOHBtSks5eGYzZzkxSFYyZ05xdnY4dUVnClNwRnh3R3ZydGRUS2IrT2lSb0Zy
            bE1tbFNVYlpvTDdnWk15OFcrbTh2SnMKLS0tIFEzb2xPbzZxUU1yQ3F1S2NvRWxs
            Ni9jRW1uNWN0eTdWSVV6U1FMejFocHMKNeBTvyWuHJhS4f50wDwJ0AhkS1lcBy0Z
            Cq587qf6cnYsB20dTDAqtv8/CvqwfLuimxBc7F7W1dMB1JJgI9p0MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:vgtC0BDtV3GTCk5dwLmO7UMgPtCU87L5QV5Hqxzn7WS1SuVxBIPQdXqLEoZNkg+fkRYCfj8amhd2bdp+vflcWioyzqlAbJfmonfFdTho1qTVpIQuGU9nGrWH3p5YSDT3CD+5mhFcn1iNV7tjVOwij/PlWMzXQblIe2VTtNVvfLY=,iv:HPCovYNP3b2oXtthLapfeSNlqEL3ayLlQ2ci0CTZ0Vo=,tag:dI8TV1uo4Zb16DT7pIcpQA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
