apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-redis
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    redis-password: ENC[AES256_GCM,data:R4gbtDNRYJSZE3F/ztzgLmklsws=,iv:K7txgZVX5KaKSgbr32fflM+6vr/s0Dga5LQzi9X8Jk4=,tag:HDm6dgOrVjurzdGDdRA9IA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aTVLK3EzMXR3L3FvOHNu
            SmtkcVd1bnF1WnhBUEg5NHdPTkxrQ0VPbG1RCmRDeWZXNG9oUmFOMmt0Ry9NSkF3
            WW9sTS84MEtqdWh0RmN4TnoxSlhMK3cKLS0tIExvdytzeEE4by9JWjNsamYxTlF5
            VVBYV1Bnd2M2MEdyMDRsT1JwNk9BWjgKwoCNIl/LS1d8V6SLLSQ37Fg/HAg1X62h
            rXDwgMxOnXTpsZgL58NjviDxl6Q/TtwdpEg7K/z9P106cP5cNW3rcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN2pJamR1Mkw4d0t1NVFX
            ZFhkcWdEREJrVEJnMFozNTJVZ1A2UXJHbW4wCkJyZzdmeDBSVDhHWTY4MnFkcElx
            UWpoTk5TM2FVdzVsSUQzeHRUYkJaQ2cKLS0tIE5wcjRiZDlESDNSNHYwdTNWbzVC
            UmZWY0FHbG5UbjNDSXNHRnR6YzFyYzQKQoA7Im5KXa3AypbsCVYpCUo4deAJoBLv
            uHJ0tfteK+y/As/Ga4lKjbSMNca0kckFJIeheA2wIqRuCINfqoeJ9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZjNYQUFKNUc5NjI1ODBI
            eDZUSC9TUDIvUGgyeUtQRnE1OFdjMVk5NFZrCmVSWlhrUm0wWW1rcEw3KzJtcFFl
            UCtveEd1RFFpdVNnMmNWdFRqNUxHdnMKLS0tIFkwWTRnSm5ZcFNhNDJVclRWV3gr
            OFNDTC9HQ2lDN05aL0xnWTZoV2Q0SkUKxEJspdLUNlDXQ7ayY53pNHG5PkTskAy8
            rli+I06YI1iFaPkiM0DqAF0hj/XRtUjoPFzQaZjzyJelVkoiZhiedw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:aJ4bSbSw7q/1jvMHLfsD1utQK5rKvBEFUD4rJ9wxVe1vUMZIIKDJdavlahbJBXFxof6Ve0Fej+wzpTfd2/121UdCUhOPQ7Hti/Oy+t45mK7F0AxQojVdLrIYsQJxteIe/ReYDc1ZI9zyaEHKX6laooAlh5VK3bO3a2Ux1fX/tXw=,iv:96t6NQRCcrhON/mrzbx+4pX3HYjGn2wR1e3QkHTRPXo=,tag:uyDZRl78LRe64mMMWBSNjQ==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
