apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-redis
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    redis-password: ENC[AES256_GCM,data:l0FpjAw0/SKpGLA+XIMum7FLk+4=,iv:zEz00riWs4jZp3+m640paQwvM5QdkE2+NSZe20eInHU=,tag:6JGMe5wdgpOY57r8yUXi/A==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vk1ibTBGVCtWYnFCeU5E
            VzdlTnpvOHRKNXR4clVJTzJWaWt2SUlhcWgwClRvb1BLQWd5WWkrVmkraFZXeHZR
            NkJkamx2bnBXV2N5UGZySldtWFd5amcKLS0tIGZWcVdqNlFJOWFqemhFS0FuUXBP
            RE00VEVLZjZkRHRyUklwVjB5N3krR00KldgE0+PNILbCt/d99pWTicyD6Pnsib1C
            pGKWaz/f8SjJE4EsX30V3fhlP2ZDGup/VY2KxY72Q+bhgR4pwNc6+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ0taMStGNVZqYW1xT0M3
            Q2VhbVZ1ekc0Wnlabm4zdzdtd1pjYVZLeVRrCnBIMGtNZnNRTGtlbFdoUUZSa1pZ
            WjViS1NNTG1KbzF1OHlWOU90bXFSVXcKLS0tIFpITWt1UjJLdlRXTUZ0RldZcEl0
            elRRNExHOGhnVDdZVVJBZENxSTBaOW8Kg5Ww/4i3YdO4a3Skh7LRLZu+tV+xEajd
            ztpBxAavpe2cTjOgeY0eg4t94ORos8yLDcT7O2R6ExSqOTRBYM1JkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMEdIZ2JkWVRzV2JpanNm
            RnIyM1NZSTl0V0pKSXQ5VHRGNDJWTmhzd0NNCm9VaHpVMVhtL0V5Q083MUVMRmtG
            QjROYUFoRUo2TGR3bzc5cHJBdUxYQWMKLS0tIFN5bnBOejhxNWZHUTFqM25hMEpt
            clpwOEFyNXEyZ091ZG4wVHNqTVhWWHMKnxrF3Y7m/d7N41J7joZpWo15Gz1UiBe4
            pxprb2KLxp5p5GRQJxGz1Tg1wL/Kspn+Ujx84/6hGU1CEu54IxAnJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TVltQXp3VksrREhLeVhL
            MVpGT2JuajdWdUZEeUVrMy9Samt2cXJYV1VJCjJrS0FKWU4zbndlWTJybHNSalMx
            YXZvaGFKQ1JkaXRheG9pWEpoaHU1eEkKLS0tIFlDdXJObUZOZlBWWFQ4RTN4NGps
            QVZzMm5ZUmlTOGN0NTFTR1AvWFBtS1UKeYrDgSHG+VX/JLq5EZMpvSex3TmvRGrP
            vQ0PZ36QMSmFmD24OmCL4dOjq65owB/ixTr1GCioPK7luAOXEE9EzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:FO1Rp7aXLyE53t/zlvGvkSRbazMSqo7J8Irf0yghrhYEEyDIpqu+LjNFnE9aujOEACgoJPVHc/tXxBErI3jtNJlHbcuk9S0an4yt1z4qWwuEx9Q5si4g1E+MLMk8+Wlk5EdUqLx25T2SvUaZyA/lEqGYVqb+cqYOpwRXjNGMRDo=,iv:L6JxQmN8fSIetfPLJlNoNjyR7ehM4oaaKJPZGXc7IHE=,tag:gG9aLY7N/U5trp+CyxYKGw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
