apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: slack-credentials
    namespace: observability
stringData:
    clientId: ENC[AES256_GCM,data:opiBCHlj3m75J6Ay0N36BitFYdfyc0lUN977,iv:YKGpXhrT3TdKktayGSZsqJayLwQ9XGuau1eCfJtJH7U=,tag:3padjlDmRFDCFr0Ov56Tjw==,type:str]
    clientSecret: ENC[AES256_GCM,data:dmcCKd0KqSbQNh+tx5/50d5CJOWiGF5sYj9/keHuWao=,iv:jqSPVZAB2GIpSzHrFThG4kuWwhT/cJ/Obb2N3Q1lgXM=,tag:JZuTp/4ntvR6MJ0uV6aPrg==,type:str]
    signingSecret: ENC[AES256_GCM,data:n9hwm3ylNugL9UHLI3ntwtXEXGFNjCWEZ6lcawNEUDo=,iv:2iva1gfggWWcRwuRpuPWepIoM/v2kOqjLyKpPdpaHkA=,tag:VPzPe/pKohcXFM21WoLGMg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWUUrVGFKVmp5ZWJtMWhC
            UXlwSElmbWhSOVZHR1ljcVdqVkp3VlFRcFNnCkl3VTFtVjlYcmt3WjlSdE5DejNQ
            bXMrRGRlTnlSaXNnRm5KYzhTa09GMlUKLS0tIDRVQVlJNzdTUnRvQ01pVGFJK3No
            bmJUbzRhNENvVlV6MVJXb2gzZitpMW8Ky1NS9flwLCGuQ1yzjs9oyrj+1FYORT+5
            AcPgFCFL0UzLXRtWGx+LWvbjWSFEkeAqBvwyKh1Piy8+tVX/pQXs/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUjMrZnRsQWs1Vnp5eHU3
            OTF0SUZudndYSkFZUUUrcFc1Q2s1c1dOZ1JjCng5eTM5UEdpdDFSRW9zVE1SQjJn
            bURYVmtLR0R1OGh6TDgxeGt6MzQzOEkKLS0tIEMzeG9kTWVLc2dEU1B4UUFycG1i
            SWJPaUJ1MktvVGpCSHY5Vi9Fcmw5TkUKWnAkjEcXgLcsHWEoPGTlej5dTRSHX6Y9
            RkEEedGIjoKjS76Snz/u/imin9k8ytIs1lDiSI8KYp9IA2SeWVnVzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraW80dmFsMEFCNDJDbzJK
            a2dlaVE1aEdtbVlTaStRb3BmN0lmRlA5VEVzCkxoMmNtTmVra3NOZThjM3gyY2JS
            WktYN2Jpa05DUGMyOFJQTEFZV2tkME0KLS0tIDBVc0dFTVNIamIzWC9rOWQzaXVT
            MEZiZ3VOVEpLM3JZUXpaWU1QODRtU2cKsqg+2FKutK1pPstONLeBgP1OucBQzbpJ
            NrlAsbaFO/zqbSSohLKBg5tQW5Wbcz3uf5KNzuRclgeBPyz8Rdreug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:l/MuWAlLIKgPYnddC40BwGiVZl3vcAwiN4lpz9JKguHT/Y+aAQwtTXQEHevgKXBpWIDwUPOfUtjMq7Qh0ZI3EEZmezZdFwfabmsLqUo+sk5xomLrr0B2fiYIYoofVmJzPWbVhur/WBZn4fgNtqpd3dkYggNTJDeqH7qqB32ZaZc=,iv:k0JIziEvk5+ONzQgwyfJf+ivVSTBLsifAyGvbm0YTcI=,tag:ORuj4SvlWd1R3u1fweMm1A==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
