apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: slack-credentials
    namespace: observability
stringData:
    clientId: ENC[AES256_GCM,data:EBqb2U4o6wNWFMXm76isDv31T8GY+ouQdz6y,iv:jSSDUbJpTcWWrPmWUkO9lM4///LBFIkDLQU6ojQvSs0=,tag:haTcI2tm1R6Ezct9QxFy4w==,type:str]
    clientSecret: ENC[AES256_GCM,data:Hn/iUonD/5ePU1ZUnb9xl1t/dKXoU/5eSIFYAWWv42Q=,iv:Ap3F3UjWFOrrTn/z1ywyytsmCtw2r4fYfIHSXCTN7J8=,tag:lNvmvkIHNVEYe2Tonb91Vg==,type:str]
    signingSecret: ENC[AES256_GCM,data:ZCOGGJt4O+bAbNTWoSH24pQK2b7rEKAVTS7duC6FSQA=,iv:XACxTYqOdGt31HLYkIaa1eNuy46SaHWYQLy0YqgcbW8=,tag:gcSzyllfcpUG8RXk0ivGzQ==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ1RTd0JDalZ1U0psZFVF
            TStyQkFEZjhMUXNSVTQvTUp1dUkwT1BMNFFzClpodUJBeGsvUmlRSHRHVklZRm5K
            emxLbi9pVm5jZEdYK1FUdVlaWE96UEUKLS0tIFN5K09aYjFkZ2ZMRGVCZHV5d3RK
            ZnlqYk0rR3JMVTJ6QzFZUmk3eUQ0Tm8K3XI1WzWTGsniuumT7edR3uRJzU4ew1RG
            bJEwddX8qkZqAotLIx24gocbLX1Jo1Bri+o6HkUAC34aOGg5yMcndg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NzkybUpYWVlVeERyL01j
            WGpGRUltQ05pY1NOTFQ4ZlBheG5aeDIzTUZVCjhaeVR2QXAxNjhwem4zWEtld0li
            eE44QXBOT05uSFlJZWNiM3dSejd4WHMKLS0tIEFuaVlGOWloNjI2MnJHeExFNkZv
            aHNHaGlPZGsyZFQ3MTJNNk9ha0ZNdEUKANYM2BJt3PB1M7+VHEkQbxcJ+iW9sN8b
            SP8VuNFNCr+3dxKe7Z0SKSpt6YNbxrzNSqAw/4mhet5gXYOevupEtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWkUxVVZRV0pLbVRsalZl
            RkhNQ0x4NTNrS29xcUh3U2VpMlRVNFNJd0FRCjZxU010d3RUT1g0QnZXQVhJUmtK
            OFpCOWlIR3NsWXBLdDlpRWNmQ1d0TlUKLS0tIGxhR2RjbjF2aXZpU2hFSUxSWjN6
            dVRQTnNpcVVPWGR1RUgycjZOMEh5UUEKyoiDnlhBG2rmM6SQKEn4DH3NenhGg9kc
            +gU+aeJH+e0HBdMH/nMmg1sIQDnrGa1xMRlUaHis9nLqqp7kxfyBKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM3JFcmpDMVVHcXJFeUF3
            TTdjM2lpaWZJdGN2UmRVd0dWR21ITWZ6cjNZCkNMUUk3SGVkVG9HSUFHODdIMzh2
            Qm1UalVDNG92eFF6MEdaWk1wMkM2K3MKLS0tIE11QUFrbURGNjVEaWxwcVBuRHFn
            b0lLN3ZRbWtjKzlNY0o4bXN5WnF4WTgKRM/wJRukq4SUnzk9OkcqMCqOHZghIPbJ
            GbhyCXafqFWHHZFEdLE4wVJtCMOZT7q1bl3eznDjJmb52m3AUUzOJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:xWP1IlprQDKq6lCfOvYdY/VZP5XSdDtCUk/yyR6c5T5bkRen/nj980F7wXTZi2o0di8jkqe8M4hwfH0PCKRcdImwaec50N1KE21R/E6hz3dDsuXlxwNWdBoZm0HqYYJbiooZRqNLDzjK5Jcf50OXUer1ZOm1EuXgjT/MDNpouvo=,iv:N3efbhyez1/qtziOzwUah4sk7OMy5/kiVcVYV/R5A7M=,tag:yn+CybDKbTzkjrnJnk5rMw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
