apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: oncall-telegram-token
    namespace: observability
stringData:
    token: ENC[AES256_GCM,data:tzZa/DFHwtkdh7/36lfPg3fbpxM+30oQB7LKqm1nWdVp7Yg8spJBDkizSnv+fw==,iv:Txvi/9YKXk9Ri8JvYYkQ7Ce9R+Vmor2HNd9tbMUyS7w=,tag:O/GHrlU5I+4o2iGXtUk7qg==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMmVHcm1sQkVaZ0EzN1hO
            a3I5d2F5T09KSThEOE1WYnU2V01vYWhaS1ZBCm40eUdSKy82Vm1nUytHeHNPYTA4
            ZUE0YW9YSUJjbm01UmRJYXk4bG9kY2sKLS0tIEFrTTdwOXU1MjRBR0N1N05ZaFNG
            YWxXSXlxM3JkcUdlMEhrNWVTNHJYaHMKH7Ncq2E+vToSLsWTFw3raZCMDhyWkIRY
            OxUs4gi5tLh/h0A7QtOfr1L4zy0oJo4rPHxyl3vucSbxXUpmRBw9jA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwall1L3hWTmVPV3NyVVFz
            VXhRcXVBN1c0Qzc4SUlSejdIVGkrUnNWWGp3CjJJQ3hrUkEvY0hXN2hXaDQxOTdF
            dGZhc2J3cmZaa1ViNDJqMnZiWWpseFEKLS0tIFo0bFQ0QzY3Yzkrc2RIOW5FUVcz
            eU00aEdnSGRUTmxIWFA5TGZ6VU9SMDQKJ1LuntSc1iGV7ZNK3QjxtVMWGunS6h5m
            MWXzDoIP5jmlncbnRvccIc3+pA7dYn1WH1fw3A+afazTn3q9BmLfPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV08xcHgwdHFmc2V6VkMy
            RlVaRU9jaGs2L1FKS0loSDhyYTlYZ291eGdzCm54ejk1aUt3TFUyUkgraTN6SXZx
            bFFYdTZYMlhiQjJVWDMvOElYeTdSNnMKLS0tIDBLZitBdUtETTJ0b3R0MWVtQ1U3
            Y2VOTlN0a2ZVMjFkOGVKOVJrR0owVXcKar88RYSG9c3wSR6RNYMv5X6KxTKWBXA9
            OmoVYsNLC3edtRR1oSvG36De3B9DDnC+VPchPe21wn03itruBKz1+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:14:45Z"
    mac: ENC[AES256_GCM,data:93C1KHURGcJb9CWbNgynaNTmExitHvlXw9ofstiEeSQoWgzEHTHLGkUfXW3wk7k+dZfePD9wk8LSNl/0FSk8heJgZ+kMW1r5AKT7nxc2d6JuOdohdKKR9/oNbSRTlFrb52KDSPM/zhWpuCVtIXf1FkFAXc5tpeoQYwpLbME84l0=,iv:EoYBiZbNB8KqH2JWRdFiG92DGlW8OLlrWB+C5QFMZ7I=,tag:/7lSmA8a3Mc2of0HU1Z+DA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
