apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: oncall-telegram-token
    namespace: observability
stringData:
    token: ENC[AES256_GCM,data:YmPWLEANTKj8OBqYE6mcP4fulBfYV2TzIJply1K4SP8SDm4eFcr5yXB1aLk7Dg==,iv:+XR9dQ3X5Ifql2NxpkVuECmOcyCrGOW87+2aVskeYes=,tag:3LokFco9M6MlmYCQqH9LgA==,type:str]
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYWFqZ0NYbWsxRzlKRFdq
            Mm9VRzNCRWpzM1FBUFhyanViczhhTVF6bGxjCmRUbkpkWUFEQWFTaW9VVEVoRnZw
            b044OEFrTFpHVzVJajY4Z3Q4dG10VXcKLS0tIGViL01iU3dreFJFSE14RldqS1Zu
            KzBPekxJM2dGbnp1em9BNW9EMmpGS3cK6qmbZkhkd/KMulIuxgrIM7vrM5Lr/c62
            VymArAAzYnM3i+Mfy1wLbfjCFkUjIJVcpwwFFrmhkmpqDqEFomWFZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVS94WFlhdDFCQ3hYemp1
            OStMVEJmWGJubk5nMTlRMDJPc3VDS1dnYjNvCnFQMVE0aTVOVnhSVnFHOUUvWFpo
            czhLQ0xHNHBPNURvS1BXVnNnRTYwbnMKLS0tIDZjYTBISEduT0s5MVF5MTl0ZEpF
            Y3hVTGpJZUlObUYzY1pqQ2dLTTZhMGsKir12Y6akBtVqJNR2PxKIjfXLxhb56Aay
            4D4fhcBgYVzySMZ6RJZp6isnFCGKNK2Xpz4HmVdQwpKFY6xhrI7fCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNURGRGR6S1hnVEpOeG92
            KzBrbVpMaCtVUWFCWXlkOGFSeWU2a2Y1RmhRCm9QOVpyQVRWWXBCdjljcWoxZkUy
            STlHRkMwKzdGdmVoc0dnU3VGYVpNYWcKLS0tIERSb3BnSitKQ3JOS1lVZkIzTDZW
            ZUZpQmJMZWhTQXZaUFNEai9HUVU1N2MKdr4uAosILbduKzMHaJE75Ry4paZu7Yy2
            KvgaJrGRysFOOXMzV95nPtOXGJRIBghijSgE9q5fY3biTzByAb8dsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSnRWK1J4dkFYZnlsUEIz
            eGtoeFZQbkdFYjFhejkzcEdJUlBUczM1c0hNClNDaVdDMThVZUd3S3NqNXVqd2dQ
            NEkyVEp1SDhkLys3YVVSTUl6TzZaeHcKLS0tIHQ4VUp3bnhxNzNOTFQzQ0xTM0lL
            SktpTGp1OGpYQThETXRwZGl5WHJtSFkKTMGPCaqhrvSBr0p3/PyqqSIIuiknDq9o
            JQiyMSWEAsNiaxo3XMLZ4x44rUrSTxr5LyZTyqyymv2jA91dKhkebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:Id4wZ+nWPtBucaJwQf6RuDnxNRzAxTCzfdrutlt6jN3nizOgQhv/+MCkv6bfL6idQ04rQsBFZ9gfvWPRELLcTGn242fPtAXZCUO8QT/pg8ttE088HTIousCBNBgzSzpuDMEKt+lquVpi/8pSI8l1+P5kZa7IKZDA/QntxaJgAjk=,iv:I3hjoLgMG5tXd7Nuv5z2NjMaqmOKzwS3+oWGCavW1mM=,tag:xdU/cvq65OSvxMAmVCWzWA==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
