apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-checker
    repo: https://mogensen.github.io/cert-checker
    version: 0.0.6
    releaseName: cert-checker
    namespace: cert-checker
    includeCRDs: true
    valuesFile: helm-values.yaml
