apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: observability
stringData:
    auth_github_client_id: ENC[AES256_GCM,data:9WS+MdfcYEe23tp7tc4O1OnxpAs=,iv:EMhVnp/IQnpjAdb9vZi/lfOO9nEmgQ/clVn2PwvZJI4=,tag:/Rhaips5aH6kiRE9ebfI3A==,type:str]
    auth_github_client_secret: ENC[AES256_GCM,data:srCWbg+eZpZlo9FL1YhwnOGyu6q+FtzpprobcexTuRDuXio4mb8cOg==,iv:OQnmU+NM38mvC8et+5rQfOAeAr412V3nTPioaUwbF1M=,tag:E4DkesEEF/GJM5JAdkauZw==,type:str]
    auth_github_allowed_organizations: ENC[AES256_GCM,data:JUktZ5WZnfJhaw==,iv:x2AqLA/F0pMYMUb3EDSgU5j9iwc5eB/Ns8Sx3zTOsvc=,tag:MRN/hgVMiGgplSRwUvrwAg==,type:str]
    auth_github_team_ids: ""
sops:
    age:
        - recipient: age1r9chn8pl3d4msxktw457x3xz2l8p04pwuyd7pkgldkmkakras5ks7tfsyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ1B5SGlZQkZiQlBPa29q
            b0pvQmJZQklkdzd5VXdMbCt1Zi80MWZVZ3kwCi92MWhQYWx2c013aEwzZ2RVSmxO
            N25FMFh0Wm5WS0JaUXBUbnJSRFpBckEKLS0tIFBEWERTTy83bWF1a0x3alB5Y2Zl
            YU5RT2lmNmJYUktNckFPM3pzVEtZTnMKf14qlWDjammfWtL4xZmqqQ86ux091fHv
            LwlgxmIjGnLhxuopV0wWKFMiECi9PDvv/DDP82ZyDhNnw7HaKSzCAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10hzpv26wext204acftvf2n8r6hmnnwxdpkngzaysllpwynccjvjsjvhq4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZlltTVdKU2EwTmIvd2Nl
            Q2ZJRTRBaEVaSURFdEtwVGhWcEtOQUFleXlVCllXRHovWHNtTzkxeU9pZmNsNDFv
            MHhYbFgvUHUrQmVZd0tlYjJNRHpxb2cKLS0tIHQ2OTZqL1JMNG9mY3BxQncvbG53
            Z3p0NW1TS2kzbUVXTE5hMTZaOE9uV2MKNRK/RdMYKEAwhw9Wqy0O7KxAgohlJ5bP
            EOm4lJtFqa3RPVUq1LQioM74lwU493OAycsOTZ4oKM3OvQ5fVtC09w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4lhmkmvr4lype9x4dm3y9lxk2uekqwwj65mp4c36tnph6ytfakqesnats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZXhtL3NLZVNMbzMzN3Fu
            RFdla3QxTkxYaS9waGxCTEVMc1UwVVhGN1VRCmZGa2lsMGsxRTl5cWpTWHkrMXp3
            akVic3pKV29acmRkZS9jMjREdWtvZEkKLS0tIGczUEJxbGlZQkQvMlk3Ujhkc2o2
            N2c4cEhCWXFScm54SFdtZWRvNkFkUFUKRpnNmVMQ4yjznt0JUBZtN5jE/2SvY3zE
            ldAc5gsvzHCThzD/Po0nym4j972log6aSbAWwN2Dxw83Udb1rqr8Gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15cq50fx3zeeqg5aqh06s6p9zsew3yjlggx3mzchqea6763uup5jsaz9pu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQkY1MXA3NFhuV2IwN2ZW
            YXJpSktSK3JWZjc4cFVNVlFaNnJvOGdZWDFZCnFZSnhyV0ZQQ3paVkxXZkljZzN6
            SjY1NEVHdVRtUjUwUEZrRVBTM1EzaDAKLS0tIDlROFQzT1N0RTBObERNSlZQWnJt
            c1UvZmRQOXlFRFdabjd5bHVidWVQVFEKiqndOUrYnTlHS0AG4cWMLX6jAIeRRJzh
            BO5g4cGlJ8BmK9kK2pKLG/ennmAqN4PSD0E3U5HgxHa2BtLscNXFDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T21:08:12Z"
    mac: ENC[AES256_GCM,data:deOr7GwgMut6XDADhV9G+vWY4W0YCJ354/TMNFjFq/UlW7AAdKg5a6epAuCmVzS6G8gh42Q7iPk1jUyGb2vUHrpmcK8bs/sKV8i5QUnDlJ8dshGsO371ixnrf5xH46jqLn50ZS9oEjjUsgCIMwi1uesitGIMl136xZQYjoIygfM=,iv:6b2Do2b8FOD5lepzhyK/hhPfObJX0KxeKUUnkso2jl0=,tag:Lv5r1jGch6SYGz64BU3fqw==,type:str]
    encrypted_regex: ^(data|stringData|spec|bot_token|chat_id|url|token|signing_key|account_id)$
    version: 3.12.2
